In [5]:
from bs4 import BeautifulSoup as bs
import os
import pandas as pd
import time
import requests
from selenium import webdriver

In [6]:
from splinter import Browser

In [7]:
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time

In [39]:
executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
browser = Browser('chrome', **executable_path, headless=False)

In [31]:
#22201
apartments_20009 = []

In [65]:
url = 'https://www.zillow.com/washington-dc-20009/apartments/1-bedrooms/7_p'
browser.visit(url)

In [66]:
html = browser.html
soup = bs(html,'html.parser')

In [67]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20009.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
2714 Quarry Rd NW APT B4, Washington, DC 20009
<div class="list-card-price">$1,650/mo</div>
1 bd
650 sqft
-------------
1415 T St NW, Washington, DC
None
$1,475+ 1 bd
None
-------------
1669 Columbia Rd NW APT 406, Washington, DC 20009
<div class="list-card-price">$2,400/mo</div>
1 bd
1,029 sqft
-------------
3019 15th St NW APT 4, Washington, DC 20009
<div class="list-card-price">$1,881/mo</div>
1 bd
800 sqft
-------------
1830 California St NW APT 4, Washington, DC 20009
<div class="list-card-price">$2,100/mo</div>
1 bd
650 sqft
-------------
1701 16th St NW APT 109, Washington, DC 20009
<div class="list-card-price">$2,300/mo</div>
1 bd
667 sqft
-------------
1900 S St NW APT 4, Washington, DC 20009
<div class="list-card-price">$1,775/mo</div>
1 bd
655 sqft
-------------
2620 16th St NW APT 705, Washington, DC 20009
<div class="list-card-price">$1,895/mo</div>
1 bd
693 sqft
-------------
1450 Harvard St NW, Washington, DC 20009
<div class="list-card-price">$1,685/mo</div>
1 bd
680 sqft
-------------
2040 Belmont Rd NW #423, Washington, DC 20009
<div class="list-card-price">$1,675/mo</div>
1 bd
523 sqft
-------------
2445 15th St NW #216, Washington, DC 20009
<div class="list-card-price">$1,780/mo</div>
1 bd
580 sqft
-------------
1319 Corcoran St NW APT 3, Washington, DC 20009
<div class="list-card-price">$1,850/mo</div>
1 bd
651 sqft
-------------
1904 T St NW APT A, Washington, DC 20009
<div class="list-card-price">$2,111/mo</div>
1 bd
-- sqft
-------------
1447 Chapin St NW APT 201, Washington, DC 20009
<div class="list-card-price">$1,975/mo</div>
1 bd
649 sqft
-------------
1718 Corcoran St NW APT 14, Washington, DC 20009
<div class="list-card-price">$2,380/mo</div>
1 bd
625 sqft
-------------
1605 Corcoran St NW, Washington, DC
None
$1,900+ 1 bd
None
-------------
1438 Fairmont St NW #T2, Washington, DC 20009
<div class="list-card-price">$1,400/mo</div>
1 bd
650 sqft
-------------
1221 Euclid St NW UNIT 1, Washington, DC 20009
<div class="list-card-price">$1,650/mo</div>
1 bd
800 sqft
-------------
1445 W St NW #B, Washington, DC 20009
<div class="list-card-price">$1,600/mo</div>
1 bd
552 sqft
-------------
1442 Corcoran St NW APT 3, Washington, DC 20009
<div class="list-card-price">$2,850/mo</div>
1 bd
769 sqft
-------------
2630 Adams Mill Rd NW UNIT 2, Washington, DC 20009
<div class="list-card-price">$1,800/mo</div>
1 bd
592 sqft
-------------
2000 16th St NW APT 506, Washington, DC 20009
<div class="list-card-price">$1,850/mo</div>
1 bd
450 sqft
-------------
1919 17th St NW, Washington, DC 20009
<div class="list-card-price">$1,775/mo</div>
1 bd
613 sqft
-------------
1615 Q St NW APT 713, Washington, DC 20009
<div class="list-card-price">$1,700/mo</div>
1 bd
485 sqft
-------------
1414 Belmont St NW APT 208, Washington, DC 20009
<div class="list-card-price">$1,975/mo</div>
1 bd
640 sqft
-------------
2426 Ontario Rd NW #202, Washington, DC 20009
<div class="list-card-price">$2,100/mo</div>
1 bd
507 sqft
-------------
1901 Columbia Rd NW APT 702, Washington, DC 20009
<div class="list-card-price">$2,195/mo</div>
1 bd
720 sqft
-------------
1844 Columbia Rd NW APT 301, Washington, DC 20009
<div class="list-card-price">$1,900/mo</div>
1 bd
500 sqft
-------------
2028 13th St NW APT B, Washington, DC 20009
<div class="list-card-price">$1,350/mo</div>
1 bd
640 sqft
-------------
1825 Biltmore St NW #A, Washington, DC 20009
<div class="list-card-price">$1,978/mo</div>
1 bd
490 sqft
-------------
1825 T St NW APT 502, Washington, DC 20009
<div class="list-card-price">$1,900/mo</div>
1 bd
650 sqft
-------------
1822 Vernon St NW APT 204, Washington, DC 20009
<div class="list-card-price">$1,900/mo</div>
1 bd
628 sqft
-------------
1611 Corcoran St NW APT B, Washington, DC 20009
<div class="list-card-price">$2,095/mo</div>
1 bd
523 sqft
-------------
2012 Kalorama Rd NW APT 5, Washington, DC 20009
<div class="list-card-price">$2,450/mo</div>
1 bd
668 sqft
-------------
2245 12th St NW, Washington, DC 20009
<div class="list-card-price">$2,648/mo</div>
1 bd
2,632 sqft
-------------
1826 Vernon St NW #4, Washington, DC 20009
<div class="list-card-price">$2,190/mo</div>
1 bd
458 sqft
-------------
1727 Corcoran St NW #B, Washington, DC 20009
<div class="list-card-price">$1,725/mo</div>
1 bd
450 sqft

In [68]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20009): 
    if word in stopwords:
        words.remove(word)

In [69]:
apartments_20009

[{'address': 'Highview & Castle Manor | 2505 13th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,736+ 1 bd',
  'sqft': None},
 {'address': 'Reed Row | 2101 Champlain St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,454+ 1 bd',
  'sqft': None},
 {'address': '1845 Kalorama Rd NW #3, Washington, DC 20009',
  'price_monthly': '$2,995/mo',
  'also_price': '1 bd',
  'sqft': '690 sqft'},
 {'address': 'The Melwood | 1803 Biltmore St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,745+ 1 bd',
  'sqft': None},
 {'address': '1919 19th St NW #401, Washington, DC 20009',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Argonne | 1629 Columbia Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,777+ 1 bd',
  'sqft': None},
 {'address': '2020 12th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,450+ 1 bd',
  'sqft': None},
 {'address': '1901 19th St NW APT 203, Washington, DC 20009',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '521 sqft'},
 {'address': '2400 16th St NW #7H6JJHZEU, Washington, DC 20009',
  'price_monthly': '$1,899+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'Corcoran House at Dupont Circle | 1616 18th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,967+ 1 bd',
  'sqft': None},
 {'address': 'The Clifton | 1315 Clifton St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,034+ 1 bd',
  'sqft': None},
 {'address': 'Camden Roosevelt | 2101 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,329+ 1 bd',
  'sqft': None},
 {'address': '1630 R Street, NW | 1630 R St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,699+ 1 bd',
  'sqft': None},
 {'address': 'The Dorchester House | 2480 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,877+ 1 bd',
  'sqft': None},
 {'address': 'Citadel | 1631 Kalorama Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,899+ 1 bd',
  'sqft': None},
 {'address': 'Capitol View on 14th | 2420 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '1706 U St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': 'The Corcoran | 1350 Corcoran St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,799+ 1 bd',
  'sqft': None},
 {'address': 'AME at Meridian Hill | 2601 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,104+ 1 bd',
  'sqft': None},
 {'address': '2032 Belmont Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'Dorchester West | 2425 17th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,850+ 1 bd',
  'sqft': None},
 {'address': '1819 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$1,954/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1920 S St NW, Washington, DC 20009',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '1390 V St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': 'Sonnet | 1441 U St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,170+ 1 bd',
  'sqft': None},
 {'address': '2900 Adams Mill Rd NW #604, Washington, DC 20009',
  'price_monthly': '$2,600/mo',
  'also_price': '1 bd',
  'sqft': '621 sqft'},
 {'address': 'The Louis | 1920 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,851+ 1 bd',
  'sqft': None},
 {'address': '1108 Columbia Rd NW APT 108, Washington, DC 20009',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': 'Chalfonte | 1601 Argonne Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,773+ 1 bd',
  'sqft': None},
 {'address': '1757 Q St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,500+ 1 bd',
  'sqft': None},
 {'address': '1826 Vernon St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,480+ 1 bd',
  'sqft': None},
 {'address': '2611 Adams Mill Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': 'Richman Towers | 3055 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,858+ 1 bd',
  'sqft': None},
 {'address': '2125 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,875+ 1 bd',
  'sqft': None},
 {'address': '14W Apartments | 1315 W St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,149+ 1 bd',
  'sqft': None},
 {'address': 'Park Ellison | 1700 Harvard St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'Harvard Village | 1829 Summit Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,542+ 1 bd',
  'sqft': None},
 {'address': '1614 17th St NW #43CJJZ19Z, Washington, DC 20009',
  'price_monthly': '$1,550+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'Warder Mansion | 2633 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,625+ 1 bd',
  'sqft': None},
 {'address': 'District | 1401 S St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,167+ 1 bd',
  'sqft': None},
 {'address': '2620 13th St NW #R4JB4426R, Washington, DC 20009',
  'price_monthly': '$1,850+/mo',
  'also_price': '1 bd',
  'sqft': '400 sqft'},
 {'address': 'The Ellington | 1301 U St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,936+ 1 bd',
  'sqft': None},
 {'address': 'Park Square | 2407 15th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': '2523 13th St NW #35JKC0FAT, Washington, DC 20009',
  'price_monthly': '$1,750+/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '3060 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': 'Columbia Uptown | 1375 Fairmont St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,618+ 1 bd',
  'sqft': None},
 {'address': '1413 S St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '1919 19th St NW APT 301, Washington, DC 20009',
  'price_monthly': '$1,880/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1921 19th St NW APT 3, Washington, DC 20009',
  'price_monthly': '$1,780/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1721 21st St NW APT T3, Washington, DC 20009',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Modera Sedici | 2700 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,160+ 1 bd',
  'sqft': None},
 {'address': '2331 15th St NW UNIT 103S, Washington, DC 20009',
  'price_monthly': '$2,550/mo',
  'also_price': '1 bd',
  'sqft': '651 sqft'},
 {'address': '2303 14th St NW APT 501, Washington, DC 20009',
  'price_monthly': '$3,128/mo',
  'also_price': '1 bd',
  'sqft': '973 sqft'},
 {'address': 'View 14 | 2303 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,919+ 1 bd',
  'sqft': None},
 {'address': 'Washington House | 2120 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': 'The Hepburn | 1901 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,344+ 1 bd',
  'sqft': None},
 {'address': 'Adams-Garden Towers | 2325 15th St, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': '1634 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,250+ 1 bd',
  'sqft': None},
 {'address': '1930 New Hampshire Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': 'OSLOadmo Co-Living | 1708 V St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$950+ 1 bd',
  'sqft': None},
 {'address': '1440 Chapin St NW APT 21, Washington, DC 20009',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '680 sqft'},
 {'address': '2801 15th St NW #X21D10PXK, Washington, DC 20009',
  'price_monthly': '$1,850+/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'The Policy | 1921 Kalorama Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,669+ 1 bd',
  'sqft': None},
 {'address': '1711 T St NW #5, Washington, DC 20009',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '775 sqft'},
 {'address': '1813 Vernon St NW #BASEMENT, Washington, DC 20009',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '2639 15th St NW APT 205, Washington, DC 20009',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '564 sqft'},
 {'address': '1320 R St NW APT 3, Washington, DC 20009',
  'price_monthly': '$1,964/mo',
  'also_price': '1 bd',
  'sqft': '686 sqft'},
 {'address': '1845 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '490 sqft'},
 {'address': '2407 20th St NW UNIT 98, Washington, DC 20009',
  'price_monthly': '$2,700/mo',
  'also_price': '1 bd',
  'sqft': '955 sqft'},
 {'address': '1465 Harvard St NW, Washington, DC 20009',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '674 sqft'},
 {'address': '1851 Columbia Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,870+ 1 bd',
  'sqft': None},
 {'address': '1735 New Hampshire Ave NW APT 605, Washington, DC 20009',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '574 sqft'},
 {'address': '1916 17th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,099+ 1 bd',
  'sqft': None},
 {'address': '2627 Adams Mill Rd NW APT 105, Washington, DC 20009',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20009',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1739 19th St NW APT 1, Washington, DC 20009',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '2,810 sqft'},
 {'address': '2422 17th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '1321 Fairmont St NW APT 3, Washington, DC 20009',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '425 sqft'},
 {'address': '1922 16th St NW APT 1, Washington, DC 20009',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '646 sqft'},
 {'address': '1514 Columbia Rd NW APT B, Washington, DC 20009',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1816 New Hampshire Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,425+ 1 bd',
  'sqft': None},
 {'address': '1862 Ontario Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '2318 18th St NW APT 1, Washington, DC 20009',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '944 sqft'},
 {'address': '2410 20th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': 'The Rodney | 1911 R St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,409+ 1 bd',
  'sqft': None},
 {'address': '1801 Belmont Rd NW APT 402, Washington, DC 20009',
  'price_monthly': '$1,780/mo',
  'also_price': '1 bd',
  'sqft': '463 sqft'},
 {'address': '1631 19th St NW #46, Washington, DC 20009',
  'price_monthly': '$2,750/mo',
  'also_price': '1 bd',
  'sqft': '718 sqft'},
 {'address': '1809 20th Street | 1809 20th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,300+ 1 bd',
  'sqft': None},
 {'address': '1621 T St NW APT 807, Washington, DC 20009',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '507 sqft'},
 {'address': '1912 T St NW #A, Washington, DC 20009',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '688 sqft'},
 {'address': '1603 Corcoran St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,075+ 1 bd',
  'sqft': None},
 {'address': '1620 15th St NW APT 1, Washington, DC 20009',
  'price_monthly': '$2,950/mo',
  'also_price': '1 bd',
  'sqft': '3,844 sqft'},
 {'address': '1827 19th St NW #1, Washington, DC 20009',
  'price_monthly': '$4,500/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': 'Connecticut Gardens | 1915 Kalorama Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,832+ 1 bd',
  'sqft': None},
 {'address': '1910 Kalorama Rd NW APT 507, Washington, DC 20009',
  'price_monthly': '$2,900/mo',
  'also_price': '1 bd',
  'sqft': '974 sqft'},
 {'address': '1801 Calvert St NW APT G8, Washington, DC 20009',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '621 sqft'},
 {'address': '2339 Ontario Rd NW APT 1, Washington, DC 20009',
  'price_monthly': '$1,690/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '1840 Vernon St NW APT 301, Washington, DC 20009',
  'price_monthly': '$2,499/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1615 New Hampshire Ave NW #56, Washington, DC 20009',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '665 sqft'},
 {'address': '2420 19th St NW UNIT 26, Washington, DC 20009',
  'price_monthly': '$2,750/mo',
  'also_price': '1 bd',
  'sqft': '1,007 sqft'},
 {'address': '1633 Q St NW #1043913, Washington, DC 20009',
  'price_monthly': '$3,091+/mo',
  'also_price': '1 bd',
  'sqft': '883 sqft'},
 {'address': '2031 13th St NW APT 2, Washington, DC 20009',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '578 sqft'},
 {'address': '1441 Harvard St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '2101 New Hampshire Ave NW #106, Washington, DC 20009',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '510 sqft'},
 {'address': '1841 Columbia Rd NW APT 714, Washington, DC 20009',
  'price_monthly': '$2,014/mo',
  'also_price': '1 bd',
  'sqft': '660 sqft'},
 {'address': 'Gelmarc Towers | 1930 Columbia Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,685+ 1 bd',
  'sqft': None},
 {'address': '1223 Harvard St NW FLOOR 1, Washington, DC 20009',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '2298 17th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '1736 Willard St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '1835 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '490 sqft'},
 {'address': '1926 16th St NW APT 1, Washington, DC 20009',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '2535 13th St NW APT 303, Washington, DC 20009',
  'price_monthly': '$1,689/mo',
  'also_price': '1 bd',
  'sqft': '503 sqft'},
 {'address': '1418 W St NW APT 403, Washington, DC 20009',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '670 sqft'},
 {'address': '2651 16th St NW APT 306, Washington, DC 20009',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '686 sqft'},
 {'address': '1744 Corcoran St NW APT 1, Washington, DC 20009',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '1612 Q St NW #1, Washington, DC 20009',
  'price_monthly': '$2,695/mo',
  'also_price': '1 bd',
  'sqft': '680 sqft'},
 {'address': '1903 Connecticut Ave NW #313, Washington, DC 20009',
  'price_monthly': '$2,580/mo',
  'also_price': '1 bd',
  'sqft': '506 sqft'},
 {'address': '1813 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$1,856/mo',
  'also_price': '1 bd',
  'sqft': '490 sqft'},
 {'address': 'The Cortland | 1756-1760 Euclid St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,615+ 1 bd',
  'sqft': None},
 {'address': '1619 R St NW APT 302, Washington, DC 20009',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': 'Rocksboro Apartments | 1717 R St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,779+ 1 bd',
  'sqft': None},
 {'address': '1347 Euclid St NW APT 202, Washington, DC 20009',
  'price_monthly': '$1,799/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1920 1/2 New Hampshire Ave NW, Washington, DC 20009',
  'price_monthly': '$1,925/mo',
  'also_price': '1 bd',
  'sqft': '670 sqft'},
 {'address': 'Park Meridian | 2637 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,638+ 1 bd',
  'sqft': None},
 {'address': '1929 18th St NW APT 401, Washington, DC 20009',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1427 Chapin St NW APT 204, Washington, DC 20009',
  'price_monthly': '$1,875/mo',
  'also_price': '1 bd',
  'sqft': '542 sqft'},
 {'address': '1826 Biltmore St NW APT 2, Washington, DC 20009',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '2440 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,780+ 1 bd',
  'sqft': None},
 {'address': '1736 18th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '2011 15th St NW UNIT 604, Washington, DC 20009',
  'price_monthly': '$2,625/mo',
  'also_price': '1 bd',
  'sqft': '662 sqft'},
 {'address': '1839 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1928 Calvert St NW APT 6, Washington, DC 20009',
  'price_monthly': '$1,499/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1607 Corcoran St NW APT A, Washington, DC 20009',
  'price_monthly': '$2,042/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1851 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$2,221/mo',
  'also_price': '1 bd',
  'sqft': '490 sqft'},
 {'address': '1829 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$1,975/mo',
  'also_price': '1 bd',
  'sqft': '490 sqft'},
 {'address': '1821 Biltmore St NW #A, Washington, DC 20009',
  'price_monthly': '$2,069/mo',
  'also_price': '1 bd',
  'sqft': '490 sqft'},
 {'address': '1601 18th St NW APT 616, Washington, DC 20009',
  'price_monthly': '$2,450/mo',
  'also_price': '1 bd',
  'sqft': '829 sqft'},
 {'address': '2010 Kalorama Rd NW, Washington, DC 20009',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '2231 Ontario | 2231 Ontario Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,849+ 1 bd',
  'sqft': None},
 {'address': '2314 17th St NW #B, Washington, DC 20009',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1910 T St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '1421 Q St NW APT 3, Washington, DC 20009',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '1,068 sqft'},
 {'address': '1815 S St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,395+ 1 bd',
  'sqft': None},
 {'address': '1811 S St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '1350 Florida Ave | 1350 Florida Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': '2388 Champlain St NW UNIT 1, Washington, DC 20009',

In [70]:
#STOP 
#STOP 
#STOP 
#STOP 
#STOP 

zip_code ="20009"

apts_20009_df = pd.DataFrame(apartments_20009)
apts_20009_df['also_price'] = apts_20009_df['also_price'].str[:-4]
apts_20009_df["Zip Code"] = zip_code
apts_20009_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"$1,736+",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"$2,454+",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","$2,995/mo",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"$1,745+",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","$1,950/mo",,600 sqft,20009
...,...,...,...,...,...
272,"1611 Corcoran St NW APT B, Washington, DC 20009","$2,095/mo",,523 sqft,20009
273,"2012 Kalorama Rd NW APT 5, Washington, DC 20009","$2,450/mo",,668 sqft,20009
274,"2245 12th St NW, Washington, DC 20009","$2,648/mo",,"2,632 sqft",20009
275,"1826 Vernon St NW #4, Washington, DC 20009","$2,190/mo",,458 sqft,20009
276,"1727 Corcoran St NW #B, Washington, DC 20009","$1,725/mo",,450 sqft,20009

In [71]:
#20002
apartments_20002 = []

In [87]:
url = 'https://www.zillow.com/washington-dc-20002/apartments/1-bedrooms/4_p'
browser.visit(url)

In [88]:
html = browser.html
soup = bs(html,'html.parser')

In [89]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20002.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
207 16th St NE, Washington, DC
None
$1,400+ 1 bd
None
-------------
1522 Queen St NE APT 2, Washington, DC 20002
<div class="list-card-price">$1,600/mo</div>
1 bd
650 sqft
-------------
1118 Penn St NE APT 4, Washington, DC 20002
<div class="list-card-price">$1,650/mo</div>
1 bd
725 sqft
-------------
1906 E St NE APT A, Washington, DC 20002
<div class="list-card-price">$1,550/mo</div>
1 bd
600 sqft
-------------
1125 Maryland Ave NE APT 6, Washington, DC 20002
<div class="list-card-price">$1,500/mo</div>
1 bd
434 sqft
-------------
523 8th St NE APT 303, Washington, DC 20002
<div class="list-card-price">$2,290/mo</div>
1 bd
766 sqft
-------------
802 E St NE #BASEMENT, Washington, DC 20002
<div class="list-card-price">$1,595/mo</div>
1 bd
500 sqft
-------------
1247 F St NE #3, Washington, DC 20002
<div class="list-card-price">$1,295/mo</div>
1 bd
-- sqft
-------------
11 Girard St NE #B, Washington, DC 20002
<div class="list-card-price">$1,375/mo</div>
1 bd
725 sqft
-------------
412 Constitution Ave NE #BASEMENT, Washington, DC 20002
<div class="list-card-price">$1,700/mo</div>
1 bd
-- sqft
-------------
221 9th St NE UNIT B, Washington, DC 20002
<div class="list-card-price">$1,995/mo</div>
1 bd
1,000 sqft
-------------
Coda at Bryant St | 600 Rhode Island Ave NE, Washington, DC
None
$1,805+ 1 bd
None
-------------
636 12th St NE APT 105, Washington, DC 20002
<div class="list-card-price">$1,300/mo</div>
1 bd
690 sqft
-------------
112 11th St NE APT B, Washington, DC 20002
<div class="list-card-price">$1,550/mo</div>
1 bd
600 sqft
-------------
Glenwood Apartments | 2315 Lincoln Rd NE, Washington, DC
None
$1,500+ 1 bd
None
-------------
2017 I St NE, Washington, DC 20002
<div class="list-card-price">$1,250/mo</div>
1 bd
600 sqft
-------------
1723 Lang Pl NE, Washington, DC 20002
<div class="list-card-price">$1,120/mo</div>
1 bd
500 sqft
-------------
821 Maryland Ave NE APT 203, Washington, DC 20002
<div class="list-card-price">$1,695/mo</div>
1 bd
-- sqft
-------------
228 10th St NE #12, Washington, DC 20002
<div class="list-card-price">$1,800/mo</div>
1 bd
-- sqft
-------------
1606 K St NE APT 2, Washington, DC 20002
<div class="list-card-price">$1,216/mo</div>
1 bd
-- sqft
-------------
1500 Oates St NE, Washington, DC 20002
<div class="list-card-price">$1,600/mo</div>
1 bd
3,602 sqft
-------------
1420 Trinidad Ave NE, Washington, DC 20002
<div class="list-card-price">$1,400/mo</div>
1 bd
750 sqft
-------------
1716 H St NE APT A, Washington, DC 20002
<div class="list-card-price">$1,200/mo</div>
1 bd
600 sqft
-------------
622 19th St NE, Washington, DC 20002
<div class="list-card-price">$2,460/mo</div>
1 bd
600 sqft
-------------
1715 Montello Ave NE APT 2, Washington, DC 20002
<div class="list-card-price">$1,525/mo</div>
1 bd
1,184 sqft
-------------
405 10th St NE APT 103, Washington, DC 20002
<div class="list-card-price">$1,695/mo</div>
1 bd
650 sqft
-------------
1229 Constitution Ave NE #BASEMENT, Washington, DC 20002
<div class="list-card-price">$1,595/mo</div>
1 bd
-- sqft
-------------
505 19th St NE, Washington, DC 20002
<div class="list-card-price">$1,700/mo</div>
1 bd
600 sqft
-------------
1825 Maryland Ave NE #APBK9ZZ9B, Washington, DC 20002
<div class="list-card-price">$1,575+/mo</div>
1 bd
-- sqft
-------------
1112 Raum St NE APT 1, Washington, DC 20002
<div class="list-card-price">$1,200/mo</div>
1 bd
-- sqft
-------------
1265 Simms Pl NE, Washington, DC
None
$1,216+ 1 bd
None
-------------
2018 N Capitol St NW #B, Washington, DC 20002
<div class="list-card-price">$1,475/mo</div>
1 bd
720 sqft
-------------
833 19th St NE, Washington, DC 20002
<div class="list-card-price">$1,750/mo</div>
1 bd
592 sqft
-------------
1521 Benning Rd NE #6R6JBGZFU, Washington, DC 20002
<div class="list-card-price">$1,053+/mo</div>
1 bd
-- sqft
-------------
623 A St NE APT 2, Washington, DC 20002
<div class="list-card-price">$2,750/mo</div>
1 bd
400 sqft
-------------
1431 E St NE APT 3, Washington, DC 20002
<div class="list-card-price">$1,650/mo</div>
1 bd
-- sqft

In [90]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20002): 
    if word in stopwords:
        words.remove(word)

In [91]:
apartments_20002

[{'address': '2 M Street | 2 M St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,805+ 1 bd',
  'sqft': None},
 {'address': 'Flats 130 at Constitution Square | 130 M St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,533+ 1 bd',
  'sqft': None},
 {'address': 'The Gale Eckington | 151 Q St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,380+ 1 bd',
  'sqft': None},
 {'address': '317 10th St NE APT 19, Washington, DC 20002',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '625 sqft'},
 {'address': 'The Gantry DC | 300 Morse St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': 'Ledger Union Market | 1320 4th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,250+ 1 bd',
  'sqft': None},
 {'address': '100K | 100 K St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,790+ 1 bd',
  'sqft': None},
 {'address': 'AVA NoMa | 55 M St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,745+ 1 bd',
  'sqft': None},
 {'address': 'Avalon First and M | 1160 1st St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,685+ 1 bd',
  'sqft': None},
 {'address': '1813 I St NE, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '575 sqft'},
 {'address': '700 Constitution Avenue, NE | 700 Constitution Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,999+ 1 bd',
  'sqft': None},
 {'address': 'AVA H Street | 318 I St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,645+ 1 bd',
  'sqft': None},
 {'address': 'Elevation at Washington Gateway | 100 Florida Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,459+ 1 bd',
  'sqft': None},
 {'address': 'Camden NoMa | 61 Pierce St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,625+ 1 bd',
  'sqft': None},
 {'address': 'i5 Union Market | 320 Florida Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,656+ 1 bd',
  'sqft': None},
 {'address': '2703 N Capitol St NE, Washington, DC 20002',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '855 sqft'},
 {'address': '217 Adams St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,490/mo',
  'also_price': '1 bd',
  'sqft': '3,232 sqft'},
 {'address': 'The Hecht Warehouse at Ivy City | 1401 New York Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,562+ 1 bd',
  'sqft': None},
 {'address': 'Union Heights | 1600 Maryland Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,581+ 1 bd',
  'sqft': None},
 {'address': '(undisclosed Address), Washington, DC 20002',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': 'Third & Rhode | 230 Rhode Island Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,375+ 1 bd',
  'sqft': None},
 {'address': '1120 Holbrook St NE #3, Washington, DC 20002',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '221 Constitution Ave NE, Washington, DC 20002',
  'price_monthly': '$1,678/mo',
  'also_price': '1 bd',
  'sqft': '568 sqft'},
 {'address': 'Union Place | 200 K St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,927+ 1 bd',
  'sqft': None},
 {'address': 'Avec on H Street | 901 H St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,720+ 1 bd',
  'sqft': None},
 {'address': 'The Aria | 300 L St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': '315 Franklin St NE #QHNTR5K3N, Washington, DC 20002',
  'price_monthly': '$1,400+/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': 'Senate Square | 201 I St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,055+ 1 bd',
  'sqft': None},
 {'address': '202 Oklahoma Ave NE APT 1, Washington, DC 20002',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '1,224 sqft'},
 {'address': '1350 Maryland Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '422 21st St NE #BASEMENT, Washington, DC 20002',
  'price_monthly': '$1,575/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '2321 4th St NE #5B1KVYYNY, Washington, DC 20002',
  'price_monthly': '$1,360+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '612 12th St NE APT 202, Washington, DC 20002',
  'price_monthly': '$1,346/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '500 25th Pl NE #103, Washington, DC 20002',
  'price_monthly': '$1,699/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': 'The Metropolitan Apartments | 200 Rhode Island Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '106 5th St NE #B, Washington, DC 20002',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': 'The Batley | 1270 4th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,770+ 1 bd',
  'sqft': None},
 {'address': 'RESA | 22 M St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,716+ 1 bd',
  'sqft': None},
 {'address': '412 3rd St NE APT 34, Washington, DC 20002',
  'price_monthly': '$1,625/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1869 Kendall St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,195/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'OSLOatlas Co-Living | 1219 Florida Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$950+ 1 bd',
  'sqft': None},
 {'address': '113 R St NE #B, Washington, DC 20002',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '2,598 sqft'},
 {'address': '319 14th St NE, Washington, DC 20002',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '720 sqft'},
 {'address': '509B 5th St NE, Washington, DC 20002',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '644 9th St NE UNIT B, Washington, DC 20002',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '333 2nd St NE APT 302, Washington, DC 20002',
  'price_monthly': '$1,899/mo',
  'also_price': '1 bd',
  'sqft': '605 sqft'},
 {'address': 'The Edison at Union Market | 1240 4th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '1020 11th St NE #B, Washington, DC 20002',
  'price_monthly': '$1,150/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1814 I St NE #5, Washington, DC 20002',
  'price_monthly': '$1,625/mo',
  'also_price': '1 bd',
  'sqft': '407 sqft'},
 {'address': '819 5th St NE, Washington, DC 20002',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '1825 H St NE APT B, Washington, DC 20002',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '238 14th Pl NE #BASEMENT, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1810 N Capitol St NW #3, Washington, DC 20002',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '950 sqft'},
 {'address': '1740 N Capitol St NW APT 1, Washington, DC 20002',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '122 6th St NE APT 1, Washington, DC 20002',
  'price_monthly': '$1,799/mo',
  'also_price': '1 bd',
  'sqft': '797 sqft'},
 {'address': '1231 Penn St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,499/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1111 Orren St NE #202, Washington, DC 20002',
  'price_monthly': '$2,149/mo',
  'also_price': '1 bd',
  'sqft': '528 sqft'},
 {'address': '624 Maryland Ave NE APT 9, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '14 S St NE APT 105, Washington, DC 20002',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '569 sqft'},
 {'address': '518 F St NE #B, Washington, DC 20002',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '532 sqft'},
 {'address': '604 19th St NE APT A, Washington, DC 20002',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '815 Maryland Ave. NE | 815 Maryland Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': '676 4th St NE, Washington, DC 20002',
  'price_monthly': '$1,975/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '360 H St NE APT 233, Washington, DC 20002',
  'price_monthly': '$2,106/mo',
  'also_price': '1 bd',
  'sqft': '709 sqft'},
 {'address': '1243 16th St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '2,560 sqft'},
 {'address': '1933 2nd St NE #4, Washington, DC 20002',
  'price_monthly': '$2,450/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '28 9th St NE, Washington, DC 20002',
  'price_monthly': '$1,825/mo',
  'also_price': '1 bd',
  'sqft': '1,050 sqft'},
 {'address': '729 K St NE, Washington, DC 20002',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '640 sqft'},
 {'address': '660 E St NE, Washington, DC 20002',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '725 sqft'},
 {'address': '434 13th St NE #2, Washington, DC 20002',
  'price_monthly': '$1,725/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '505 14th St NE, Washington, DC 20002',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '605 sqft'},
 {'address': '911 2nd St NE UNIT 608, Washington, DC 20002',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '689 sqft'},
 {'address': '215 I St NE #206, Washington, DC 20002',
  'price_monthly': '$2,650/mo',
  'also_price': '1 bd',
  'sqft': '754 sqft'},
 {'address': '1510 N Capitol St NW UNIT 303, Washington, DC 20002',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '533 sqft'},
 {'address': 'Fairway Park | 2100 Maryland Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,175+ 1 bd',
  'sqft': None},
 {'address': '925 19th St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,199/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '19 U St NE APT B, Washington, DC 20002',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '830 sqft'},
 {'address': '1254 16th St NE, Washington, DC 20002',
  'price_monthly': '$1,250/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '808 9th St NE #B, Washington, DC 20002',
  'price_monthly': '$2,050/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1201 I St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': '1348 E St NE, Washington, DC 20002',
  'price_monthly': '$1,825/mo',
  'also_price': '1 bd',
  'sqft': '820 sqft'},
 {'address': '1201 I St NE #3, Washington, DC 20002',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1401 Staples St NE APT 1, Washington, DC 20002',
  'price_monthly': '$1,230/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '819 D St NE #25, Washington, DC 20002',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1900 M St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '116 8th St NE #B, Washington, DC 20002',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '1,190 sqft'},
 {'address': '1101 W Virginia Ave NE #210, Washington, DC 20002',
  'price_monthly': '$1,200/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '855 19th St NE APT 3, Washington, DC 20002',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '315 G St NE, Washington, DC 20002',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '420 sqft'},
 {'address': '726 6th St NE APT B, Washington, DC 20002',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '520 sqft'},
 {'address': '401 13th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '2625 3rd St NE #204, Washington, DC 20002',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1364 Constitution Ave NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1219 16th St NE UNIT B, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Coda on H | 315 H St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,133+ 1 bd',
  'sqft': None},
 {'address': 'The Belgard | 33 N St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,545+ 1 bd',
  'sqft': None},
 {'address': '1124 E St NE #E, Washington, DC 20002',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '403 Constitution Ave NE UNIT 1, Washington, DC 20002',
  'price_monthly': '$2,350/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1508 F St NE UNIT 3, Washington, DC 20002',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '645 sqft'},
 {'address': '1230 Simms Pl NE #A, Washington, DC 20002',
  'price_monthly': '$1,050/mo',
  'also_price': '1 bd',
  'sqft': '560 sqft'},
 {'address': '1740 H St NE APT A, Washington, DC 20002',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '630 11th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,295+ 1 bd',
  'sqft': None},
 {'address': '1235 Penn St NE APT 3, Washington, DC 20002',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '252 Maryland Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,250+ 1 bd',
  'sqft': None},
 {'address': '121 4th St NE APT B, Washington, DC 20002',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '513 12th St NE APT 5, Washington, DC 20002',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '428 sqft'},
 {'address': '1253 16th St NE #B, Washington, DC 20002',
  'price_monthly': '$1,525/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'The Stanton | 816 E St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,641+ 1 bd',
  'sqft': None},
 {'address': '807 A St NE #3, Washington, DC 20002',
  'price_monthly': '$1,466/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1016 17th Pl NE #203, Washington, DC 20002',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '547 sqft'},
 {'address': '822 4th St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,445/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '443 10th St NE | 443 10th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,499+ 1 bd',
  'sqft': None},
 {'address': '1615 Gales St NE #1, Washington, DC 20002',
  'price_monthly': '$1,690/mo',
  'also_price': '1 bd',
  'sqft': '624 sqft'},
 {'address': 'Anthology | 625 H St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,927+ 1 bd',
  'sqft': None},
 {'address': '170 Todd Pl NE, Washington, DC 20002',
  'price_monthly': '$1,390/mo',
  'also_price': '1 bd',
  'sqft': '540 sqft'},
 {'address': '305 C St NE APT 407, Washington, DC 20002',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '644 Massachusetts Ave NE APT 402, Washington, DC 20002',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '535 sqft'},
 {'address': '611 A St NE #B, Washington, DC 20002',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1900-1900 And 1904 West Virginia Avenue Ne 2 #3-1-4, Washington, DC 20002',
  'price_monthly': '$1,275/mo',
  'also_price': '1 bd',
  'sqft': '575 sqft'},
 {'address': '209 16th St NE APT 6, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '525 sqft'},
 {'address': '207 16th St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '1522 Queen St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1118 Penn St NE APT 4, Washington, DC 20002',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '725 sqft'},
 {'address': '1906 E St NE APT A, Washington, DC 20002',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1125 Maryland Ave NE APT 6, Washington, DC 20002',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '434 sqft'},
 {'address': '523 8th St NE APT 303, Washington, DC 20002',
  'price_monthly': '$2,290/mo',
  'also_price': '1 bd',
  'sqft': '766 sqft'},
 {'address': '802 E St NE #BASEMENT, Washington, DC 20002',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '1247 F St NE #3, Washington, DC 20002',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '11 Girard St NE #B, Washington, DC 20002',
  'price_monthly': '$1,375/mo',
  'also_price': '1 bd',
  'sqft': '725 sqft'},
 {'address': '412 Constitution Ave NE #BASEMENT, Washington, DC 20002',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '221 9th St NE UNIT B, Washington, DC 20002',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': 'Coda at Bryant St | 600 Rhode Island Ave NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,805+ 1 bd',
  'sqft': None},
 {'address': '636 12th St NE APT 105, Washington, DC 20002',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '690 sqft'},
 {'address': '112 11th St NE APT B, Washington, DC 20002',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Glenwood Apartments | 2315 Lincoln Rd NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '2017 I St NE, Washington, DC 20002',
  'price_monthly': '$1,250/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1723 Lang Pl NE, Washington, DC 20002',
  'price_monthly': '$1,120/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '821 Maryland Ave NE APT 203, Washington, DC 20002',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '228 10th St NE #12, Washington, DC 20002',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1606 K St NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,216/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1500 Oates St NE, Washington, DC 20002',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '3,602 sqft'},
 {'address': '1420 Trinidad Ave NE, Washington, DC 20002',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1716 H St NE APT A, Washington, DC 20002',
  'price_monthly': '$1,200/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '622 19th St NE, Washington, DC 20002',
  'price_monthly': '$2,460/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1715 Montello Ave NE APT 2, Washington, DC 20002',
  'price_monthly': '$1,525/mo',
  'also_price': '1 bd',
  'sqft': '1,184 sqft'},

In [92]:
#STOP 
#STOP 
#STOP 
#STOP 
#STOP 

zip_code ="20002"

apts_20002_df = pd.DataFrame(apartments_20002)
apts_20002_df['also_price'] = apts_20002_df['also_price'].str[:-4]
apts_20002_df["Zip Code"] = zip_code
apts_20002_df

,address,price_monthly,also_price,sqft,Zip Code
0,"2 M Street | 2 M St NE, Washington, DC",None,"$1,805+",None,20002
1,Flats 130 at Constitution Square | 130 M St NE...,None,"$1,533+",None,20002
2,"The Gale Eckington | 151 Q St NE, Washington, DC",None,"$1,380+",None,20002
3,"317 10th St NE APT 19, Washington, DC 20002","$2,300/mo",,625 sqft,20002
4,"The Gantry DC | 300 Morse St NE, Washington, DC",None,"$1,995+",None,20002
...,...,...,...,...,...
151,"2018 N Capitol St NW #B, Washington, DC 20002","$1,475/mo",,720 sqft,20002
152,"833 19th St NE, Washington, DC 20002","$1,750/mo",,592 sqft,20002
153,"1521 Benning Rd NE #6R6JBGZFU, Washington, DC ...","$1,053+/mo",,-- sqft,20002
154,"623 A St NE APT 2, Washington, DC 20002","$2,750/mo",,400 sqft,20002
155,"1431 E St NE APT 3, Washington, DC 20002","$1,650/mo",,-- sqft,20002

In [93]:
#20001
apartments_20001 = []

In [114]:
url = 'https://www.zillow.com/washington-dc-20001/apartments/1-bedrooms/4_p'
browser.visit(url)

In [115]:
html = browser.html
soup = bs(html,'html.parser')

In [116]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20001.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
936 T St NW, Washington, DC 20001
<div class="list-card-price">$2,700/mo</div>
1 bd
3,344 sqft
-------------
67 Quincy Pl NW #B, Washington, DC 20001
<div class="list-card-price">$1,595/mo</div>
1 bd
600 sqft
-------------
122 W St NW #B, Washington, DC 20001
<div class="list-card-price">$1,900/mo</div>
1 bd
990 sqft
-------------
2112 Flagler Pl NW, Washington, DC 20001
<div class="list-card-price">$1,550/mo</div>
1 bd
1,774 sqft
-------------
419 Ridge St NW UNIT B, Washington, DC 20001
<div class="list-card-price">$3,195/mo</div>
1 bd
1,415 sqft
-------------
928 P St NW #2, Washington, DC 20001
<div class="list-card-price">$2,000/mo</div>
1 bd
672 sqft
-------------
1107 6th St NW #B, Washington, DC 20001
<div class="list-card-price">$2,195/mo</div>
1 bd
2,837 sqft
-------------
1109 6th St NW #B, Washington, DC 20001
<div class="list-card-price">$1,995/mo</div>
1 bd
3,004 sqft
-------------
200 P St NW #3, Washington, DC 20001
<div class="list-card-price">$1,250/mo</div>
1 bd
519 sqft
-------------
39 Florida Ave NW #1, Washington, DC 20001
<div class="list-card-price">$1,995/mo</div>
1 bd
502 sqft
-------------
1123 11th St NW #L1, Washington, DC 20001
<div class="list-card-price">$1,850/mo</div>
1 bd
774 sqft
-------------
460 New York Ave NW UNIT 402, Washington, DC 20001
<div class="list-card-price">$1,900/mo</div>
1 bd
580 sqft
-------------
1019 4th St NW #604, Washington, DC 20001
<div class="list-card-price">$1,610/mo</div>
1 bd
618 sqft
-------------
1628 11th St NW, Washington, DC 20001
<div class="list-card-price">$2,400/mo</div>
1 bd
751 sqft
-------------
1118 10th St NW APT 1, Washington, DC 20001
<div class="list-card-price">$2,895/mo</div>
1 bd
750 sqft
-------------
66 New York Ave NW APT 305, Washington, DC 20001
<div class="list-card-price">$1,500/mo</div>
1 bd
747 sqft
-------------
401 Massachusetts Ave NW, Washington, DC
None
$2,700+ 1 bd
None
-------------
1550 11th St NW APT 104, Washington, DC 20001
<div class="list-card-price">$1,875/mo</div>
1 bd
640 sqft
-------------
1505 9th St NW #A, Washington, DC 20001
<div class="list-card-price">$2,500/mo</div>
1 bd
603 sqft
-------------
1119 6th St NW, Washington, DC 20001
<div class="list-card-price">$1,700/mo</div>
1 bd
3,880 sqft
-------------
1111 11th St NW APT 302, Washington, DC 20001
<div class="list-card-price">$1,828/mo</div>
1 bd
643 sqft

In [117]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20001): 
    if word in stopwords:
        words.remove(word)

In [118]:
apartments_20001

[{'address': 'Mass Court | 300 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,530+ 1 bd',
  'sqft': None},
 {'address': '17 Seaton Pl NW #B, Washington, DC 20001',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '840 sqft'},
 {'address': '77 H | 77 H St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,745+ 1 bd',
  'sqft': None},
 {'address': '475 K St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,999+ 1 bd',
  'sqft': None},
 {'address': 'J Linea | 2009 8th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,910+ 1 bd',
  'sqft': None},
 {'address': 'Avalon at Gallery Place | 770 5th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,540+ 1 bd',
  'sqft': None},
 {'address': 'The Aspen | 1011 4th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,553+ 1 bd',
  'sqft': None},
 {'address': '450K | 450 K St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,984+ 1 bd',
  'sqft': None},
 {'address': 'Jefferson Marketplace | 1550 7th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,985+ 1 bd',
  'sqft': None},
 {'address': '7th Flats | 1825 7th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,619+ 1 bd',
  'sqft': None},
 {'address': '425 Mass | 425 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,575+ 1 bd',
  'sqft': None},
 {'address': '455 I St NW #1-209, Washington, DC 20001',
  'price_monthly': '$2,466/mo',
  'also_price': '1 bd',
  'sqft': '843 sqft'},
 {'address': 'Gables City Vista | 460 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,490+ 1 bd',
  'sqft': None},
 {'address': 'Newseum Residences | 565 Pennsylvania Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,965+ 1 bd',
  'sqft': None},
 {'address': '301 Massachusetts Ave NW APT 606, Washington, DC 20001',
  'price_monthly': '$1,790/mo',
  'also_price': '1 bd',
  'sqft': '452 sqft'},
 {'address': '555 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'City Market at O Street | 800 P St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,727+ 1 bd',
  'sqft': None},
 {'address': 'Yale West | 443 New York Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,863+ 1 bd',
  'sqft': None},
 {'address': '127 Seaton Pl NW #B, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '225 Morgan St NW #304, Washington, DC 20001',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1118 5th St NW APT A, Washington, DC 20001',
  'price_monthly': '$2,750/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': 'The Shay | 1924 8th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,581+ 1 bd',
  'sqft': None},
 {'address': 'The Wren DC | 965 Florida Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,805+ 1 bd',
  'sqft': None},
 {'address': '925 H St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,050+ 1 bd',
  'sqft': None},
 {'address': 'Lurgan Apartments | 915 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,961+ 1 bd',
  'sqft': None},
 {'address': 'Lyric 440 | 440 K St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,798+ 1 bd',
  'sqft': None},
 {'address': 'The Apartments at CityCenter | 825 10th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,651+ 1 bd',
  'sqft': None},
 {'address': '777 7th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': 'Colonel | 1250 9th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,910+ 1 bd',
  'sqft': None},
 {'address': 'Mount Vernon Plaza | 930 M St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '2120 Vermont Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': 'The Shaw | 618 T St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,405+ 1 bd',
  'sqft': None},
 {'address': '750 Hobart Pl NW #B, Washington, DC 20001',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '437 New York Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': '880 P | 880 P St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,192+ 1 bd',
  'sqft': None},
 {'address': '427 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'OSLOshaw Co-Living | 1734 6th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,185+ 1 bd',
  'sqft': None},
 {'address': '935 S St NW, Washington, DC 20001',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '1701 New Jersey Ave NW #BASEMENT, Washington, DC 20001',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '2004 11th St NW APT 134, Washington, DC 20001',
  'price_monthly': '$1,737/mo',
  'also_price': '1 bd',
  'sqft': '708 sqft'},
 {'address': '35 Seaton Pl NW, Washington, DC 20001',
  'price_monthly': '$1,575/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '75 Seaton Pl NW #B, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '2030 8th St NW UNIT 404, Washington, DC 20001',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '514 sqft'},
 {'address': '1907 3rd St NW APT 303, Washington, DC 20001',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '513 sqft'},
 {'address': '2020 Flagler Pl NW FLOOR 4, Washington, DC 20001',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': 'The Ashton at Judiciary Square | 750 3rd St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,276+ 1 bd',
  'sqft': None},
 {'address': '710 Q St NW #B, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '1111 11th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,150+ 1 bd',
  'sqft': None},
 {'address': '420-422 M St NW APT F, Washington, DC 20001',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '1,150 sqft'},
 {'address': '60 Q St NW #MB, Washington, DC 20001',
  'price_monthly': '$1,100/mo',
  'also_price': '1 bd',
  'sqft': '2,978 sqft'},
 {'address': '811 4th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': 'Atlantic Plumbing | 2112 8th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,020+ 1 bd',
  'sqft': None},
 {'address': '514 Hobart Pl NW UNIT 1, Washington, DC 20001',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '460 New York Ave NW, Washington, DC 20001',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '905 O St NW APT 2, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '410 sqft'},
 {'address': '57 N St NW #304, Washington, DC 20001',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '720 sqft'},
 {'address': '920 I St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,250+ 1 bd',
  'sqft': None},
 {'address': '66 V St NW #B, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '779 sqft'},
 {'address': '226 Bates St NW #A, Washington, DC 20001',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '1,902 sqft'},
 {'address': '65 U St NW #BASEMENT, Washington, DC 20001',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '3,080 sqft'},
 {'address': '6 Rhode Island Ave NW APT 3, Washington, DC 20001',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '428 sqft'},
 {'address': '1126 11th St NW #A, Washington, DC 20001',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '2608 Sherman Ave NW APT 104, Washington, DC 20001',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '512 sqft'},
 {'address': '216 Florida Ave NW APT 1, Washington, DC 20001',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '688 sqft'},
 {'address': '440 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,195+ 1 bd',
  'sqft': None},
 {'address': '703 6th St NW APT 1, Washington, DC 20001',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '409 sqft'},
 {'address': '425 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,932+ 1 bd',
  'sqft': None},
 {'address': '1881 3rd St NW APT 105, Washington, DC 20001',
  'price_monthly': '$1,799/mo',
  'also_price': '1 bd',
  'sqft': '675 sqft'},
 {'address': '1920 10th St NW APT 6, Washington, DC 20001',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2035 2nd St NW APT G204, Washington, DC 20001',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '624 sqft'},
 {'address': '2920 Georgia Ave NW UNIT 201, Washington, DC 20001',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '617 sqft'},
 {'address': '1907 3rd St NW APT 301, Washington, DC 20001',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '521 sqft'},
 {'address': '931 R St NW APT 1, Washington, DC 20001',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '345 Oakdale Pl NW APT 101, Washington, DC 20001',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '11 N St NW APT B, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1507 Marion St NW, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '744 sqft'},
 {'address': '42 T St NW APT 1, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '1616 11th St NW APT 102, Washington, DC 20001',
  'price_monthly': '$1,875/mo',
  'also_price': '1 bd',
  'sqft': '517 sqft'},
 {'address': '405 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '531 T St NW APT 205, Washington, DC 20001',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '416 M St NW, Washington, DC 20001',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '475 New York Ave NW UNIT 5, Washington, DC 20001',
  'price_monthly': '$2,449/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '111 Rhode Island Ave NW APT 2, Washington, DC 20001',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '123 W St NW #BASEMENT, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1923 9th St NW #3, Washington, DC 20001',
  'price_monthly': '$3,150/mo',
  'also_price': '1 bd',
  'sqft': '1,139 sqft'},
 {'address': '919 Florida Ave NW APT 501, Washington, DC 20001',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '742 sqft'},
 {'address': '1623 New Jersey Ave NW, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Lydian | 400 K St, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,034+ 1 bd',
  'sqft': None},
 {'address': '400 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,200+ 1 bd',
  'sqft': None},
 {'address': '607 Florida Ave NW FLOOR 2, Washington, DC 20001',
  'price_monthly': '$1,524/mo',
  'also_price': '1 bd',
  'sqft': '1,327 sqft'},
 {'address': '60 Channing St NW #BASEMENT, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2201 2nd St NW APT 13, Washington, DC 20001',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '720 sqft'},
 {'address': '32 W St NW, Washington, DC 20001',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1905 8th St NW, Washington, DC 20001',
  'price_monthly': '$1,590/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '904 French St NW #2, Washington, DC 20001',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '10 Florida Ave NW APT 302, Washington, DC 20001',
  'price_monthly': '$2,395/mo',
  'also_price': '1 bd',
  'sqft': '850 sqft'},
 {'address': '901 W | 901 W St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,905+ 1 bd',
  'sqft': None},
 {'address': '2533 11th St NW #B, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '2,220 sqft'},
 {'address': '508 Rhode Island Ave NW #3, Washington, DC 20001',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '660 sqft'},
 {'address': '1011 M St NW UNIT 901, Washington, DC 20001',
  'price_monthly': '$2,650/mo',
  'also_price': '1 bd',
  'sqft': '710 sqft'},
 {'address': '909 M St NW #B, Washington, DC 20001',
  'price_monthly': '$3,800/mo',
  'also_price': '1 bd',
  'sqft': '1,200 sqft'},
 {'address': 'Slowe | 1919 3rd St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,499+ 1 bd',
  'sqft': None},
 {'address': '56 New York Ave NW, Washington, DC 20001',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '90 R St NW APT B, Washington, DC 20001',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '52 Quincy Pl NW APT 105, Washington, DC 20001',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '513 sqft'},
 {'address': '760 5th St NW #1011, Washington, DC 20001',
  'price_monthly': '$2,560/mo',
  'also_price': '1 bd',
  'sqft': '580 sqft'},
 {'address': '907 M St NW #EB, Washington, DC 20001',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2312 1st St NW #B, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '916 G St NW APT 905, Washington, DC 20001',
  'price_monthly': '$2,450/mo',
  'also_price': '1 bd',
  'sqft': '593 sqft'},
 {'address': '1117 10th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,500+ 1 bd',
  'sqft': None},
 {'address': '721 Euclid St NW APT 1, Washington, DC 20001',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '620 sqft'},
 {'address': '717 Euclid St NW APT 1, Washington, DC 20001',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '440 K St APT 1108, Washington, DC 20001',
  'price_monthly': '$2,287/mo',
  'also_price': '1 bd',
  'sqft': '758 sqft'},
 {'address': '1117 10th St NW, Washington, DC 20001',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '1840 6th St NW #1, Washington, DC 20001',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '539 Florida Ave NW #2, Washington, DC 20001',
  'price_monthly': '$1,545/mo',
  'also_price': '1 bd',
  'sqft': '513 sqft'},
 {'address': 'Capital Plaza Apartments | 35 E St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,755+ 1 bd',
  'sqft': None},
 {'address': '435 R St NW #303, Washington, DC 20001',
  'price_monthly': '$2,495/mo',
  'also_price': '1 bd',
  'sqft': '627 sqft'},
 {'address': '471 M St NW APT C, Washington, DC 20001',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1631 6th St NW APT 8, Washington, DC 20001',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '936 T St NW, Washington, DC 20001',
  'price_monthly': '$2,700/mo',
  'also_price': '1 bd',
  'sqft': '3,344 sqft'},
 {'address': '67 Quincy Pl NW #B, Washington, DC 20001',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '122 W St NW #B, Washington, DC 20001',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '990 sqft'},
 {'address': '2112 Flagler Pl NW, Washington, DC 20001',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '1,774 sqft'},
 {'address': '419 Ridge St NW UNIT B, Washington, DC 20001',
  'price_monthly': '$3,195/mo',
  'also_price': '1 bd',
  'sqft': '1,415 sqft'},
 {'address': '928 P St NW #2, Washington, DC 20001',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '672 sqft'},
 {'address': '1107 6th St NW #B, Washington, DC 20001',
  'price_monthly': '$2,195/mo',
  'also_price': '1 bd',
  'sqft': '2,837 sqft'},
 {'address': '1109 6th St NW #B, Washington, DC 20001',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '3,004 sqft'},
 {'address': '200 P St NW #3, Washington, DC 20001',
  'price_monthly': '$1,250/mo',
  'also_price': '1 bd',
  'sqft': '519 sqft'},
 {'address': '39 Florida Ave NW #1, Washington, DC 20001',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '502 sqft'},
 {'address': '1123 11th St NW #L1, Washington, DC 20001',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '774 sqft'},
 {'address': '460 New York Ave NW UNIT 402, Washington, DC 20001',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '580 sqft'},
 {'address': '1019 4th St NW #604, Washington, DC 20001',
  'price_monthly': '$1,610/mo',
  'also_price': '1 bd',
  'sqft': '618 sqft'},
 {'address': '1628 11th St NW, Washington, DC 20001',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '751 sqft'},
 {'address': '1118 10th St NW APT 1, Washington, DC 20001',
  'price_monthly': '$2,895/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '66 New York Ave NW APT 305, Washington, DC 20001',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '747 sqft'},
 {'address': '401 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,700+ 1 bd',
  'sqft': None},
 {'address': '1550 11th St NW APT 104, Washington, DC 20001',
  'price_monthly': '$1,875/mo',
  'also_price': '1 bd',
  'sqft': '640 sqft'},
 {'address': '1505 9th St NW #A, Washington, DC 20001',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '603 sqft'},
 {'address': '1119 6th St NW, Washington, DC 20001',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '3,880 sqft'},
 {'address': '1111 11th St NW APT 302, Washington, DC 20001',
  'price_monthly': '$1,828/mo',
  'also_price': '1 bd',
  'sqft': '643 sqft'}]

In [119]:
zip_code ="20001"

apts_20001_df = pd.DataFrame(apartments_20001)
apts_20001_df['also_price'] = apts_20001_df['also_price'].str[:-4]
apts_20001_df["Zip Code"] = zip_code
apts_20001_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Mass Court | 300 Massachusetts Ave NW, Washing...",None,"$1,530+",None,20001
1,"17 Seaton Pl NW #B, Washington, DC 20001","$1,900/mo",,840 sqft,20001
2,"77 H | 77 H St NW, Washington, DC",None,"$1,745+",None,20001
3,"475 K St NW, Washington, DC",None,"$1,999+",None,20001
4,"J Linea | 2009 8th St NW, Washington, DC",None,"$1,910+",None,20001
...,...,...,...,...,...
136,"401 Massachusetts Ave NW, Washington, DC",None,"$2,700+",None,20001
137,"1550 11th St NW APT 104, Washington, DC 20001","$1,875/mo",,640 sqft,20001
138,"1505 9th St NW #A, Washington, DC 20001","$2,500/mo",,603 sqft,20001
139,"1119 6th St NW, Washington, DC 20001","$1,700/mo",,"3,880 sqft",20001
140,"1111 11th St NW APT 302, Washington, DC 20001","$1,828/mo",,643 sqft,20001

In [120]:
#22201
apartments_22201 = []

In [134]:
url = 'https://www.zillow.com/arlington-va-22201/apartments/1-bedrooms/3_p'
browser.visit(url)

In [135]:
html = browser.html
soup = bs(html,'html.parser')

In [136]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22201.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
104 N Bedford St #A, Arlington, VA 22201
<div class="list-card-price">$1,475/mo</div>
1 bd
612 sqft
-------------
1220 N Fillmore St UNIT 903, Arlington, VA 22201
<div class="list-card-price">$1,845/mo</div>
1 bd
693 sqft
-------------
1020 N Highland St UNIT 611, Arlington, VA 22201
<div class="list-card-price">$1,850/mo</div>
1 bd
792 sqft
-------------
1021 N Garfield St, Arlington, VA
None
$1,816+ 1 bd
None
-------------
3409 Wilson Blvd UNIT 603, Arlington, VA 22201
<div class="list-card-price">$1,850/mo</div>
1 bd
720 sqft
-------------
2220 Fairfax Dr, Arlington, VA
None
$1,775+ 1 bd
None
-------------
1800 Queens Ln #4197, Arlington, VA 22201
<div class="list-card-price">$1,450/mo</div>
1 bd
544 sqft
-------------
152 N Bedford St #A, Arlington, VA 22201
<div class="list-card-price">$1,700/mo</div>
1 bd
612 sqft

In [137]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22201): 
    if word in stopwords:
        words.remove(word)

In [138]:
apartments_22201

[{'address': 'Verde Pointe | 1947 N Uhle St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,730+ 1 bd',
  'sqft': None},
 {'address': 'Lyon Place at Clarendon Center | 1200 N Garfield St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,665+ 1 bd',
  'sqft': None},
 {'address': 'Latitude | 3601 Fairfax Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,882+ 1 bd',
  'sqft': None},
 {'address': 'The Prime at Arlington Courthouse | 1415 N Taft St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,649+ 1 bd',
  'sqft': None},
 {'address': 'Potomac Towers | 2001 N Adams St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,303+ 1 bd',
  'sqft': None},
 {'address': 'Courthouse Plaza | 2250 Clarendon Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,670+ 1 bd',
  'sqft': None},
 {'address': '2201 Wilson | 2201 Wilson Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,681+ 1 bd',
  'sqft': None},
 {'address': '1050 N Stuart St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': 'The Reserve at Clarendon Centre | 3000 N Washington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,694+ 1 bd',
  'sqft': None},
 {'address': 'AVA Ballston | 4650 N Washington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,304+ 1 bd',
  'sqft': None},
 {'address': 'Avalon Courthouse Place | 1320 N Veitch St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,259+ 1 bd',
  'sqft': None},
 {'address': 'The Clarendon | 1200 N Herndon St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,663+ 1 bd',
  'sqft': None},
 {'address': '2201 Pershing | 2209 N Pershing Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,582+ 1 bd',
  'sqft': None},
 {'address': 'Sheffield Court | 701 N Wayne St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,180+ 1 bd',
  'sqft': None},
 {'address': '2100 Lee Hwy, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '1020 N Stafford St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '1911 Key Blvd #11560, Arlington, VA 22201',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '581 sqft'},
 {'address': 'Courtland Towers | 1200 N Veitch St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': 'Zoso Flats | 1025 N Fillmore St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,910+ 1 bd',
  'sqft': None},
 {'address': 'Meridian at Courthouse Commons | 1401 N Taft St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,548+ 1 bd',
  'sqft': None},
 {'address': 'Bell at Courthouse | 2200 12th Ct N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,865+ 1 bd',
  'sqft': None},
 {'address': 'Fort Strong Properties | 1920 N Calvert St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '1047 N Edgewood St APT 5, Arlington, VA 22201',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '712 N Monroe St APT 2, Arlington, VA 22201',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': 'Garfield Park | 925 N Garfield St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,880+ 1 bd',
  'sqft': None},
 {'address': 'Virginia Square Towers | 3444 Fairfax Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,550+ 1 bd',
  'sqft': None},
 {'address': 'Tellus | 2009 14th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,850+ 1 bd',
  'sqft': None},
 {'address': 'Virginia Square Plaza | 801 N Monroe St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,495+ 1 bd',
  'sqft': None},
 {'address': 'Lyon Village | 3004 Lee Hwy, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '3100 9th Rd N APT 9, Arlington, VA 22201',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': 'Park Adams | 2000 N Adams St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,199+ 1 bd',
  'sqft': None},
 {'address': 'Vpoint | 1210 N Highland St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': 'Ten At Clarendon | 3110 10th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,636+ 1 bd',
  'sqft': None},
 {'address': '1021 N Garfield St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': 'Courtland Park | 2500 Clarendon Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': '3119 9th Rd N APT 206, Arlington, VA 22201',
  'price_monthly': '$3,250/mo',
  'also_price': '1 bd',
  'sqft': '877 sqft'},
 {'address': '2001 15th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,850+ 1 bd',
  'sqft': None},
 {'address': '1801 N Queens Ln, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,480+ 1 bd',
  'sqft': None},
 {'address': '1201 N Garfield St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': '3000 Spout Run Pkwy, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '1050 N Taylor St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': '1301 N Courthouse Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '1020 N Highland St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': '1800 Wilson Blvd, Arlington, VA 22201',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '695 sqft'},
 {'address': '1025 N Fillmore St #328, Arlington, VA 22201',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '748 sqft'},
 {'address': '1105 N Stuart St #1, Arlington, VA 22201',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '735 sqft'},
 {'address': '2713 Arlington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '1024 N Utah St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '2001 15th St N APT 804, Arlington, VA 22201',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '696 sqft'},
 {'address': '1000 N Randolph St APT 105, Arlington, VA 22201',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '663 sqft'},
 {'address': '911 N Fillmore St #4, Arlington, VA 22201',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '708 N Monroe St APT 4, Arlington, VA 22201',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '1778 N Troy St APT 711, Arlington, VA 22201',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1001 N Vermont St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': '2330 14th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': '1001 N Randolph St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '1210 N Taft St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': 'Avalon Clarendon | 2800 Clarendon Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,710+ 1 bd',
  'sqft': None},
 {'address': '3515 Washington Blvd APT 105, Arlington, VA 22201',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '850 sqft'},
 {'address': '1276 N Wayne St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '(undisclosed Address), Arlington, VA 22201',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '4020 Washington Blvd, Arlington, VA 22201',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '740 sqft'},
 {'address': '1001 N Randolph St APT 618, Arlington, VA 22201',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '634 sqft'},
 {'address': '2603 Arlington Blvd APT 201, Arlington, VA 22201',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '648 sqft'},
 {'address': '1025 N Stuart St #705, Arlington, VA 22201',
  'price_monthly': '$2,450/mo',
  'also_price': '1 bd',
  'sqft': '1,100 sqft'},
 {'address': '724 N Monroe St APT 1, Arlington, VA 22201',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '1817 N Rhodes St APT 256, Arlington, VA 22201',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '602 sqft'},
 {'address': '2416-2424 16th St N #4, Arlington, VA 22201',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2400 Clarendon Blvd APT 410, Arlington, VA 22201',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '44 N Bedford St APT 4, Arlington, VA 22201',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '(undisclosed Address), Arlington, VA 22201',
  'price_monthly': '$1,145/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '2009 N Daniel St #104, Arlington, VA 22201',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '725 sqft'},
 {'address': '1810 Key Blvd #9472, Arlington, VA 22201',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '630 sqft'},
 {'address': '4510 Washington Blvd #B1, Arlington, VA 22201',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '2,132 sqft'},
 {'address': '122 N Bedford St #A, Arlington, VA 22201',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '620 sqft'},
 {'address': '2007 Key Blvd APT 592, Arlington, VA 22201',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '630 sqft'},
 {'address': '1800 Wilson Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,850+ 1 bd',
  'sqft': None},
 {'address': '2523 Wilson Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '1020 N Highland St UNIT 1117, Arlington, VA 22201',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '721 sqft'},
 {'address': '2609 Arlington Blvd APT 102, Arlington, VA 22201',
  'price_monthly': '$1,370/mo',
  'also_price': '1 bd',
  'sqft': '642 sqft'},
 {'address': '104 N Bedford St #A, Arlington, VA 22201',
  'price_monthly': '$1,475/mo',
  'also_price': '1 bd',
  'sqft': '612 sqft'},
 {'address': '1220 N Fillmore St UNIT 903, Arlington, VA 22201',
  'price_monthly': '$1,845/mo',
  'also_price': '1 bd',
  'sqft': '693 sqft'},
 {'address': '1020 N Highland St UNIT 611, Arlington, VA 22201',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '792 sqft'},
 {'address': '1021 N Garfield St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,816+ 1 bd',
  'sqft': None},
 {'address': '3409 Wilson Blvd UNIT 603, Arlington, VA 22201',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '720 sqft'},
 {'address': '2220 Fairfax Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,775+ 1 bd',
  'sqft': None},
 {'address': '1800 Queens Ln #4197, Arlington, VA 22201',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '544 sqft'},
 {'address': '152 N Bedford St #A, Arlington, VA 22201',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '612 sqft'}]

In [139]:
zip_code ="22201"

apts_22201_df = pd.DataFrame(apartments_22201)
apts_22201_df['also_price'] = apts_22201_df['also_price'].str[:-4]
apts_22201_df["Zip Code"] = zip_code
apts_22201_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Verde Pointe | 1947 N Uhle St, Arlington, VA",None,"$1,730+",None,22201
1,Lyon Place at Clarendon Center | 1200 N Garfie...,None,"$1,665+",None,22201
2,"Latitude | 3601 Fairfax Dr, Arlington, VA",None,"$1,882+",None,22201
3,The Prime at Arlington Courthouse | 1415 N Taf...,None,"$1,649+",None,22201
4,"Potomac Towers | 2001 N Adams St, Arlington, VA",None,"$1,303+",None,22201
...,...,...,...,...,...
83,"1021 N Garfield St, Arlington, VA",None,"$1,816+",None,22201
84,"3409 Wilson Blvd UNIT 603, Arlington, VA 22201","$1,850/mo",,720 sqft,22201
85,"2220 Fairfax Dr, Arlington, VA",None,"$1,775+",None,22201
86,"1800 Queens Ln #4197, Arlington, VA 22201","$1,450/mo",,544 sqft,22201
87,"152 N Bedford St #A, Arlington, VA 22201","$1,700/mo",,612 sqft,22201

In [140]:
#20003
apartments_20003 = []

In [151]:
url = 'https://www.zillow.com/washington-dc-20003/apartments/1-bedrooms/3_p'
browser.visit(url)

In [152]:
html = browser.html
soup = bs(html,'html.parser')

In [153]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20003.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
754 7th St SE #1/2, Washington, DC 20003
<div class="list-card-price">$1,650/mo</div>
1 bd
460 sqft
-------------
1843 Burke St SE #2, Washington, DC 20003
<div class="list-card-price">$1,900/mo</div>
1 bd
563 sqft
-------------
1628 Independence Ave SE APT 2, Washington, DC 20003
<div class="list-card-price">$1,895/mo</div>
1 bd
850 sqft
-------------
1815 A St SE APT 203, Washington, DC 20003
<div class="list-card-price">$1,550/mo</div>
1 bd
550 sqft
-------------
1391 Pennsylvania Ave SE, Washington, DC
None
$1,975+ 1 bd
None
-------------
124 D St SE APT 1, Washington, DC 20003
<div class="list-card-price">$2,300/mo</div>
1 bd
703 sqft
-------------
1203 Walter St SE APT B, Washington, DC 20003
<div class="list-card-price">$1,450/mo</div>
1 bd
-- sqft
-------------
649 C St SE APT 202, Washington, DC 20003
<div class="list-card-price">$2,750/mo</div>
1 bd
732 sqft
-------------
801 Virginia Ave SE UNIT 206, Washington, DC 20003
<div class="list-card-price">$2,200/mo</div>
1 bd
800 sqft
-------------
309 4th St SE APT 1, Washington, DC 20003
<div class="list-card-price">$1,499/mo</div>
1 bd
499 sqft
-------------
(undisclosed Address), Washington, DC 20003
<div class="list-card-price">$2,300/mo</div>
1 bd
800 sqft
-------------
(undisclosed Address), Washington, DC 20003
<div class="list-card-price">$1,850/mo</div>
1 bd
650 sqft
-------------
223 6th St SE #3, Washington, DC 20003
<div class="list-card-price">$1,950/mo</div>
1 bd
750 sqft
-------------
910 E Capitol St NE #2, Washington, DC 20003
<div class="list-card-price">$1,750/mo</div>
1 bd
700 sqft
-------------
712 G St SE #201, Washington, DC 20003
<div class="list-card-price">$3,200/mo</div>
1 bd
410 sqft
-------------
742 7th St SE #A, Washington, DC 20003
<div class="list-card-price">$1,725/mo</div>
1 bd
-- sqft
-------------
513 Seward Sq SE #2, Washington, DC 20003
<div class="list-card-price">$2,695/mo</div>
1 bd
920 sqft
-------------
Saratoga Apartments | 653 E Capitol St SE, Washington, DC
None
$1,350+ 1 bd
None
-------------
900 11th St SE, Washington, DC 20003
<div class="list-card-price">$2,150/mo</div>
1 bd
700 sqft
-------------
607 A St SE APT B, Washington, DC 20003
<div class="list-card-price">$1,795/mo</div>
1 bd
450 sqft
-------------
Beckert's Park | 1350 E St SE, Washington, DC
None
$2,082+ 1 bd
None
-------------
724 7th St SE APT 3, Washington, DC 20003
<div class="list-card-price">$1,695/mo</div>
1 bd
600 sqft
-------------
1367 K St SE, Washington, DC 20003
<div class="list-card-price">$1,550/mo</div>
1 bd
492 sqft
-------------
119 D St SE APT 2, Washington, DC 20003
<div class="list-card-price">$1,700/mo</div>
1 bd
700 sqft
-------------
1314 K St SE #102, Washington, DC 20003
<div class="list-card-price">$1,130/mo</div>
1 bd
650 sqft
-------------
1300 4th St SE UNIT 413, Washington, DC 20003
<div class="list-card-price">$2,100/mo</div>
1 bd
625 sqft
-------------
621 I St SE #2, Washington, DC 20003
<div class="list-card-price">$2,200/mo</div>
1 bd
900 sqft
-------------
923 N Carolina Ave SE #1, Washington, DC 20003
<div class="list-card-price">$2,300/mo</div>
1 bd
825 sqft
-------------
914 E Capitol St NE #BASEMENT, Washington, DC 20003
<div class="list-card-price">$2,000/mo</div>
1 bd
1,000 sqft
-------------
1601 A St SE APT 4, Washington, DC 20003
<div class="list-card-price">$1,800/mo</div>
1 bd
867 sqft
-------------
414 Seward Sq SE APT 205, Washington, DC 20003
<div class="list-card-price">$1,835/mo</div>
1 bd
467 sqft
-------------
1311 Pennsylvania Ave SE UNIT B, Washington, DC 20003
<div class="list-card-price">$2,200/mo</div>
1 bd
575 sqft
-------------
1023 14th St SE #202, Washington, DC 20003
<div class="list-card-price">$1,500/mo</div>
1 bd
700 sqft
-------------
1500 Pennsylvania Ave SE UNIT 202, Washington, DC 20003
<div class="list-card-price">$1,895/mo</div>
1 bd
512 sqft
-------------
1631 E St SE #2, Washington, DC 20003
<div class="list-card-price">$1,150/mo</div>
1 bd
630 sqft
-------------
226 11th St SE #1/2, Washington, DC 20003
<div class="list-card-price">$1,595/mo</div>
1 bd
600 sqft
-------------
333 8th St SE APT 503, Washington, DC 20003
<div class="list-card-price">$4,825/mo</div>
1 bd
1,201 sqft
-------------
922 N Carolina Ave SE, Washington, DC 20003
<div class="list-card-price">$2,400/mo</div>
1 bd
800 sqft

In [154]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20003): 
    if word in stopwords:
        words.remove(word)

In [155]:
apartments_20003

[{'address': 'Agora | 800 New Jersey Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': 'Camden South Capitol | 1345 S Capitol St SW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,881+ 1 bd',
  'sqft': None},
 {'address': 'Capitol Yards | 100 Capital Yards, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,743+ 1 bd',
  'sqft': None},
 {'address': 'ORE 82 | 82 I St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,564+ 1 bd',
  'sqft': None},
 {'address': 'Parc Riverside | 1011 1st St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,687+ 1 bd',
  'sqft': None},
 {'address': 'One Hill South | 28 K St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,300+ 1 bd',
  'sqft': None},
 {'address': '110 D St SE #315, Washington, DC 20003',
  'price_monthly': '$2,149/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '614 E Capitol St NE APT 2, Washington, DC 20003',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '909 | 909 New Jersey Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,762+ 1 bd',
  'sqft': None},
 {'address': 'Meridian on First | 1000 1st St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,090+ 1 bd',
  'sqft': None},
 {'address': 'Park Chelsea | 880 New Jersey Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,050+ 1 bd',
  'sqft': None},
 {'address': '10K | 10 K St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,290+ 1 bd',
  'sqft': None},
 {'address': 'Maren | 71 Potomac Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,235+ 1 bd',
  'sqft': None},
 {'address': '7 15th St SE APT 1, Washington, DC 20003',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '3,120 sqft'},
 {'address': '618 E St NE #B, Washington, DC 20003',
  'price_monthly': '$1,575/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '401 11th St SE #2, Washington, DC 20003',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'Arris | 1331 4th St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,980+ 1 bd',
  'sqft': None},
 {'address': '603 E St SE, Washington, DC 20003',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '980 sqft'},
 {'address': 'f1rst residences | 1263 1st St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,490+ 1 bd',
  'sqft': None},
 {'address': '1000 New Jersey Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'Park Kennedy | 1901 C St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,745+ 1 bd',
  'sqft': None},
 {'address': 'Estate | 220 Water St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,274+ 1 bd',
  'sqft': None},
 {'address': 'Bell Capitol Hill | 1717 E Capitol St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,745+ 1 bd',
  'sqft': None},
 {'address': '456 New Jersey Ave SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,475/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '258 8th St SE, Washington, DC 20003',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': 'Blackbird | 1401 Pennsylvania Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,055+ 1 bd',
  'sqft': None},
 {'address': '1600 Pennsylvania Avenue SE | 1600 Pennsylvania Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,535+ 1 bd',
  'sqft': None},
 {'address': '330 5th St SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,808/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': 'The Lockwood | 1339 E St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,641+ 1 bd',
  'sqft': None},
 {'address': 'Crossing | 949 1st St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': 'The Residences at Eastern Market | 777 C St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,200+ 1 bd',
  'sqft': None},
 {'address': '231 15th St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '710 N Carolina Ave SE, Washington, DC 20003',
  'price_monthly': '$2,050/mo',
  'also_price': '1 bd',
  'sqft': '560 sqft'},
 {'address': '114 4th St SE APT 1, Washington, DC 20003',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '1,200 sqft'},
 {'address': 'Insignia on M | 1111 New Jersey Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,872+ 1 bd',
  'sqft': None},
 {'address': 'The Kelvin | 1250 Half St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,051+ 1 bd',
  'sqft': None},
 {'address': '1300 K St SE APT 4, Washington, DC 20003',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': 'Novel South Capitol West | 2 I St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,975+ 1 bd',
  'sqft': None},
 {'address': '917 E Capitol St SE APT 1, Washington, DC 20003',
  'price_monthly': '$2,245/mo',
  'also_price': '1 bd',
  'sqft': '915 sqft'},
 {'address': 'Guild | 1346 4th St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,769+ 1 bd',
  'sqft': None},
 {'address': '1324 E St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': 'The Garrett | 150 I St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,880+ 1 bd',
  'sqft': None},
 {'address': '909 E St SE APT 3, Washington, DC 20003',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '329 1/2 6th St SE #A, Washington, DC 20003',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '222 4th St SE, Washington, DC 20003',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '408 Seward Sq SE APT 7, Washington, DC 20003',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '644 sqft'},
 {'address': 'West Half | 1201 Half St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '1391 Pennsylvania Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': '1117 I St SE, Washington, DC 20003',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1248 C St SE #1, Washington, DC 20003',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '70 N St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': 'Dock 79 | 79 Potomac Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,892+ 1 bd',
  'sqft': None},
 {'address': '601 D St SE APT 3, Washington, DC 20003',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '416 A St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,895+ 1 bd',
  'sqft': None},
 {'address': '322 D St SE APT B, Washington, DC 20003',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '626 E St SE #201, Washington, DC 20003',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '575 sqft'},
 {'address': '732 5th St SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,575/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1830 Independence Ave SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '3,168 sqft'},
 {'address': '1302 Pennsylvania Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,850+ 1 bd',
  'sqft': None},
 {'address': '1010 3rd St SE APT 1, Washington, DC 20003',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': 'Onyx on First | 1100 1st St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '420 16th St SE APT 109, Washington, DC 20003',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '546 sqft'},
 {'address': '732 15th St SE APT 3, Washington, DC 20003',
  'price_monthly': '$2,395/mo',
  'also_price': '1 bd',
  'sqft': '714 sqft'},
 {'address': '306 2nd St SE #1, Washington, DC 20003',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '1020 Pennsylvania Ave SE APT 505, Washington, DC 20003',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '828 D St SE APT 3, Washington, DC 20003',
  'price_monthly': '$2,469/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1025 1st St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,500+ 1 bd',
  'sqft': None},
 {'address': '1345 K St SW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '1310 K St SE APT 302, Washington, DC 20003',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '675 sqft'},
 {'address': '1221 Van | 1221 Van St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,715+ 1 bd',
  'sqft': None},
 {'address': '124 6th St SE APT B, Washington, DC 20003',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '400 sqft'},
 {'address': '325 C St SE APT 3, Washington, DC 20003',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '575 sqft'},
 {'address': '635 G St SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1126 S Carolina Ave SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '1,056 sqft'},
 {'address': '730 7th St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,777+ 1 bd',
  'sqft': None},
 {'address': '747 10th St SE APT 1, Washington, DC 20003',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '765 sqft'},
 {'address': '733 6th St SE, Washington, DC 20003',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '470 sqft'},
 {'address': '264 15th St SE #BASEMENT, Washington, DC 20003',
  'price_monthly': '$1,790/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '536 13th St SE, Washington, DC 20003',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '608 sqft'},
 {'address': '1408 A St SE APT 203, Washington, DC 20003',
  'price_monthly': '$1,375/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '754 7th St SE #1/2, Washington, DC 20003',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '460 sqft'},
 {'address': '1843 Burke St SE #2, Washington, DC 20003',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '563 sqft'},
 {'address': '1628 Independence Ave SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '850 sqft'},
 {'address': '1815 A St SE APT 203, Washington, DC 20003',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '1391 Pennsylvania Ave SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,975+ 1 bd',
  'sqft': None},
 {'address': '124 D St SE APT 1, Washington, DC 20003',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '703 sqft'},
 {'address': '1203 Walter St SE APT B, Washington, DC 20003',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '649 C St SE APT 202, Washington, DC 20003',
  'price_monthly': '$2,750/mo',
  'also_price': '1 bd',
  'sqft': '732 sqft'},
 {'address': '801 Virginia Ave SE UNIT 206, Washington, DC 20003',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '309 4th St SE APT 1, Washington, DC 20003',
  'price_monthly': '$1,499/mo',
  'also_price': '1 bd',
  'sqft': '499 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20003',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20003',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '223 6th St SE #3, Washington, DC 20003',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '910 E Capitol St NE #2, Washington, DC 20003',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '712 G St SE #201, Washington, DC 20003',
  'price_monthly': '$3,200/mo',
  'also_price': '1 bd',
  'sqft': '410 sqft'},
 {'address': '742 7th St SE #A, Washington, DC 20003',
  'price_monthly': '$1,725/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '513 Seward Sq SE #2, Washington, DC 20003',
  'price_monthly': '$2,695/mo',
  'also_price': '1 bd',
  'sqft': '920 sqft'},
 {'address': 'Saratoga Apartments | 653 E Capitol St SE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '900 11th St SE, Washington, DC 20003',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '607 A St SE APT B, Washington, DC 20003',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': "Beckert's Park | 1350 E St SE, Washington, DC",
  'price_monthly': None,
  'also_price': '$2,082+ 1 bd',
  'sqft': None},
 {'address': '724 7th St SE APT 3, Washington, DC 20003',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1367 K St SE, Washington, DC 20003',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '492 sqft'},
 {'address': '119 D St SE APT 2, Washington, DC 20003',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1314 K St SE #102, Washington, DC 20003',
  'price_monthly': '$1,130/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1300 4th St SE UNIT 413, Washington, DC 20003',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '625 sqft'},
 {'address': '621 I St SE #2, Washington, DC 20003',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '923 N Carolina Ave SE #1, Washington, DC 20003',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '825 sqft'},
 {'address': '914 E Capitol St NE #BASEMENT, Washington, DC 20003',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '1601 A St SE APT 4, Washington, DC 20003',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '867 sqft'},
 {'address': '414 Seward Sq SE APT 205, Washington, DC 20003',
  'price_monthly': '$1,835/mo',
  'also_price': '1 bd',
  'sqft': '467 sqft'},
 {'address': '1311 Pennsylvania Ave SE UNIT B, Washington, DC 20003',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '575 sqft'},
 {'address': '1023 14th St SE #202, Washington, DC 20003',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1500 Pennsylvania Ave SE UNIT 202, Washington, DC 20003',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '512 sqft'},
 {'address': '1631 E St SE #2, Washington, DC 20003',
  'price_monthly': '$1,150/mo',
  'also_price': '1 bd',
  'sqft': '630 sqft'},
 {'address': '226 11th St SE #1/2, Washington, DC 20003',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '333 8th St SE APT 503, Washington, DC 20003',
  'price_monthly': '$4,825/mo',
  'also_price': '1 bd',
  'sqft': '1,201 sqft'},
 {'address': '922 N Carolina Ave SE, Washington, DC 20003',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'}]

In [156]:
zip_code ="20003"

apts_20003_df = pd.DataFrame(apartments_20003)
apts_20003_df['also_price'] = apts_20003_df['also_price'].str[:-4]
apts_20003_df["Zip Code"] = zip_code
apts_20003_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Agora | 800 New Jersey Ave SE, Washington, DC",None,"$1,900+",None,20003
1,"Camden South Capitol | 1345 S Capitol St SW, W...",None,"$1,881+",None,20003
2,"Capitol Yards | 100 Capital Yards, Washington, DC",None,"$1,743+",None,20003
3,"ORE 82 | 82 I St SE, Washington, DC",None,"$1,564+",None,20003
4,"Parc Riverside | 1011 1st St SE, Washington, DC",None,"$1,687+",None,20003
...,...,...,...,...,...
113,"1500 Pennsylvania Ave SE UNIT 202, Washington,...","$1,895/mo",,512 sqft,20003
114,"1631 E St SE #2, Washington, DC 20003","$1,150/mo",,630 sqft,20003
115,"226 11th St SE #1/2, Washington, DC 20003","$1,595/mo",,600 sqft,20003
116,"333 8th St SE APT 503, Washington, DC 20003","$4,825/mo",,"1,201 sqft",20003
117,"922 N Carolina Ave SE, Washington, DC 20003","$2,400/mo",,800 sqft,20003

In [182]:
#20007

apartments_20007 = []

In [168]:
url = 'https://www.zillow.com/washington-dc-20007/apartments/1-bedrooms/3_p'
browser.visit(url)

In [169]:
html = browser.html
soup = bs(html,'html.parser')

In [170]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20007.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
2336 Huidekoper Pl NW, Washington, DC 20007
<div class="list-card-price">$1,300/mo</div>
1 bd
500 sqft
-------------
3032 Q St NW #34C68FUMW, Washington, DC 20007
<div class="list-card-price">$2,600+/mo</div>
1 bd
-- sqft
-------------
3299 K St NW, Washington, DC
None
$2,150+ 1 bd
None
-------------
3237 N St NW APT 15, Washington, DC 20007
<div class="list-card-price">$1,775/mo</div>
1 bd
387 sqft
-------------
4582 Macarthur Blvd NW #203, Washington, DC 20007
<div class="list-card-price">$1,550/mo</div>
1 bd
650 sqft
-------------
2232 40th St NW, Washington, DC 20007
<div class="list-card-price">$1,500/mo</div>
1 bd
700 sqft
-------------
4474 Macarthur Blvd NW #6, Washington, DC 20007
<div class="list-card-price">$1,485/mo</div>
1 bd
740 sqft
-------------
3819 Davis Pl NW APT 1, Washington, DC 20007
<div class="list-card-price">$1,295/mo</div>
1 bd
533 sqft
-------------
2725 39th St NW APT 405, Washington, DC 20007
<div class="list-card-price">$2,100/mo</div>
1 bd
742 sqft
-------------
4545 Macarthur Blvd NW APT 206, Washington, DC 20007
<div class="list-card-price">$1,495/mo</div>
1 bd
719 sqft

In [171]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20007): 
    if word in stopwords:
        words.remove(word)

In [172]:
apartments_20007

[{'address': 'Park Crest | 2324 41st St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,411+ 1 bd',
  'sqft': None},
 {'address': '3850 Tunlaw Rd NW #VPX588N0V, Washington, DC 20007',
  'price_monthly': '$1,437+/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': 'Kew Gardens | 2700 Q St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,932+ 1 bd',
  'sqft': None},
 {'address': 'eaves Tunlaw Gardens | 3903 Davis Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,250+ 1 bd',
  'sqft': None},
 {'address': '2511 Q St NW #8, Washington, DC 20007',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '574 sqft'},
 {'address': 'The Wisconsin House | 2712 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,495+ 1 bd',
  'sqft': None},
 {'address': 'Highbridge | 2512 Q St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,260+ 1 bd',
  'sqft': None},
 {'address': 'Carillon House | 2500 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '3009 M St NW #1, Washington, DC 20007',
  'price_monthly': '$3,800/mo',
  'also_price': '1 bd',
  'sqft': '1,500 sqft'},
 {'address': '1202 30th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,900+ 1 bd',
  'sqft': None},
 {'address': '2255 Wisconsin | 2255 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,980+ 1 bd',
  'sqft': None},
 {'address': '1549 35th St NW, Washington, DC 20007',
  'price_monthly': '$1,425/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '2216 40th St NW APT 2, Washington, DC 20007',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '850 sqft'},
 {'address': '2626 Tunlaw Rd NW #2628-303, Washington, DC 20007',
  'price_monthly': '$1,425/mo',
  'also_price': '1 bd',
  'sqft': '560 sqft'},
 {'address': '2304 40th St NW, Washington, DC 20007',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '2,800 sqft'},
 {'address': '4021 Benton St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,475+ 1 bd',
  'sqft': None},
 {'address': '4031 Davis | 4031 Davis Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,575+ 1 bd',
  'sqft': None},
 {'address': '2655 41st St NW APT B1, Washington, DC 20007',
  'price_monthly': '$1,325/mo',
  'also_price': '1 bd',
  'sqft': '558 sqft'},
 {'address': '4840 Macarthur Blvd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '4491 Macarthur Blvd NW APT 103, Washington, DC 20007',
  'price_monthly': '$1,490/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1524 Wisconsin Ave NW APT 2, Washington, DC 20007',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '3333 N St NW, Washington, DC 20007',
  'price_monthly': '$3,400/mo',
  'also_price': '1 bd',
  'sqft': '890 sqft'},
 {'address': '4004 Beecher St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '2111 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': '3520 W Pl NW APT 104, Washington, DC 20007',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': 'Skyline Towers | 2730 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '1719 35th St NW APT 1, Washington, DC 20007',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1080 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,500+ 1 bd',
  'sqft': None},
 {'address': '1072 Thomas Jefferson St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,900+ 1 bd',
  'sqft': None},
 {'address': '1832 Wisconsin Ave NW #103, Washington, DC 20007',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '2201 40th Pl NW APT 1, Washington, DC 20007',
  'price_monthly': '$2,900/mo',
  'also_price': '1 bd',
  'sqft': '872 sqft'},
 {'address': '3925 Davis Pl NW APT 206, Washington, DC 20007',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '459 sqft'},
 {'address': 'Sherry Hall | 2702 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,560+ 1 bd',
  'sqft': None},
 {'address': '4555 Macarthur Blvd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,875+ 1 bd',
  'sqft': None},
 {'address': '2500 Q St NW APT 225, Washington, DC 20007',
  'price_monthly': '$2,375/mo',
  'also_price': '1 bd',
  'sqft': '703 sqft'},
 {'address': '4455 Macarthur Blvd NW APT T9, Washington, DC 20007',
  'price_monthly': '$1,690/mo',
  'also_price': '1 bd',
  'sqft': '625 sqft'},
 {'address': '2209 40th St NW APT 2, Washington, DC 20007',
  'price_monthly': '$1,475/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '1711 35th St NW APT 2, Washington, DC 20007',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '435 sqft'},
 {'address': '3101 P St NW APT 1, Washington, DC 20007',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '851 sqft'},
 {'address': '2120 Tunlaw Rd NW #B, Washington, DC 20007',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '530 sqft'},
 {'address': '3120 R St NW #TOWNHOUSE, Washington, DC 20007',
  'price_monthly': '$1,540/mo',
  'also_price': '1 bd',
  'sqft': '540 sqft'},
 {'address': '2224 40th St NW APT 2, Washington, DC 20007',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '3016 Dumbarton St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,000+ 1 bd',
  'sqft': None},
 {'address': '4527 Macarthur Blvd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '3032 Q St NW #5, Washington, DC 20007',
  'price_monthly': '$2,850/mo',
  'also_price': '1 bd',
  'sqft': '471 sqft'},
 {'address': '3900 Tunlaw Rd NW, Washington, DC 20007',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '870 sqft'},
 {'address': '2212 40th St NW APT 3, Washington, DC 20007',
  'price_monthly': '$1,375/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '4564 Macarthur Blvd NW APT 202, Washington, DC 20007',
  'price_monthly': '$1,800+/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '4593 Macarthur Blvd NW APT 5, Washington, DC 20007',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '540 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20007',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '3736 Benton St NW #1, Washington, DC 20007',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '4114 Davis Pl NW APT 110, Washington, DC 20007',
  'price_monthly': '$1,775/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '2700 Wisconsin Ave NW #610, Washington, DC 20007',
  'price_monthly': '$1,375/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2400 41st St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,475+ 1 bd',
  'sqft': None},
 {'address': '3520 W Pl NW, Washington, DC 20007',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '480 sqft'},
 {'address': '4593 Macarthur Blvd NW APT 6, Washington, DC 20007',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '520 sqft'},
 {'address': '3016 Dumbarton St NW #KAUFKKXKV, Washington, DC 20007',
  'price_monthly': '$3,000+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '4836 Macarthur Blvd NW #3, Washington, DC 20007',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '3001 P St NW APT 2, Washington, DC 20007',
  'price_monthly': '$2,995/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '4540 Macarthur Blvd NW #36XKD443W, Washington, DC 20007',
  'price_monthly': '$1,450+/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '2720 Wisconsin Ave NW APT 705, Washington, DC 20007',
  'price_monthly': '$1,875/mo',
  'also_price': '1 bd',
  'sqft': '725 sqft'},
 {'address': '3929 Fulton St NW #2, Washington, DC 20007',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '2,886 sqft'},
 {'address': '2725 39th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,099+ 1 bd',
  'sqft': None},
 {'address': '3516 W Pl NW APT 100, Washington, DC 20007',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '4471 Macarthur Blvd NW APT 301, Washington, DC 20007',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '536 sqft'},
 {'address': '1045 31st St NW APT 301, Washington, DC 20007',
  'price_monthly': '$2,875/mo',
  'also_price': '1 bd',
  'sqft': '866 sqft'},
 {'address': '1252 Wisconsin Ave NW #301, Washington, DC 20007',
  'price_monthly': '$2,700/mo',
  'also_price': '1 bd',
  'sqft': '756 sqft'},
 {'address': '4029 Benton St NW APT 202, Washington, DC 20007',
  'price_monthly': '$1,345/mo',
  'also_price': '1 bd',
  'sqft': '562 sqft'},
 {'address': '3900 Tunlaw Rd NW UNIT 318, Washington, DC 20007',
  'price_monthly': '$1,725/mo',
  'also_price': '1 bd',
  'sqft': '820 sqft'},
 {'address': '2813 38th St NW #B, Washington, DC 20007',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '720 sqft'},
 {'address': '1338 Wisconsin Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': '4000 Tunlaw Rd NW APT 430, Washington, DC 20007',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '679 sqft'},
 {'address': '1632 30th St NW APT 7, Washington, DC 20007',
  'price_monthly': '$2,950/mo',
  'also_price': '1 bd',
  'sqft': '840 sqft'},
 {'address': '3901 Tunlaw Rd NW APT 705, Washington, DC 20007',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1660 Avon Pl NW, Washington, DC 20007',
  'price_monthly': '$2,700/mo',
  'also_price': '1 bd',
  'sqft': '990 sqft'},
 {'address': '3050 N St NW #2, Washington, DC 20007',
  'price_monthly': '$4,500/mo',
  'also_price': '1 bd',
  'sqft': '3,554 sqft'},
 {'address': '3901 Fulton St NW APT 203, Washington, DC 20007',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '487 sqft'},
 {'address': '3012 Q St NW APT B, Washington, DC 20007',
  'price_monthly': '$3,000/mo',
  'also_price': '1 bd',
  'sqft': '483 sqft'},
 {'address': '3012 Q St NW APT A, Washington, DC 20007',
  'price_monthly': '$3,500/mo',
  'also_price': '1 bd',
  'sqft': '643 sqft'},
 {'address': '4450 Macarthur Blvd NW APT 9A, Washington, DC 20007',
  'price_monthly': '$1,859/mo',
  'also_price': '1 bd',
  'sqft': '635 sqft'},
 {'address': '2336 Huidekoper Pl NW, Washington, DC 20007',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '3032 Q St NW #34C68FUMW, Washington, DC 20007',
  'price_monthly': '$2,600+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '3299 K St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,150+ 1 bd',
  'sqft': None},
 {'address': '3237 N St NW APT 15, Washington, DC 20007',
  'price_monthly': '$1,775/mo',
  'also_price': '1 bd',
  'sqft': '387 sqft'},
 {'address': '4582 Macarthur Blvd NW #203, Washington, DC 20007',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '2232 40th St NW, Washington, DC 20007',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '4474 Macarthur Blvd NW #6, Washington, DC 20007',
  'price_monthly': '$1,485/mo',
  'also_price': '1 bd',
  'sqft': '740 sqft'},
 {'address': '3819 Davis Pl NW APT 1, Washington, DC 20007',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '533 sqft'},
 {'address': '2725 39th St NW APT 405, Washington, DC 20007',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '742 sqft'},
 {'address': '4545 Macarthur Blvd NW APT 206, Washington, DC 20007',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '719 sqft'}]

In [173]:
zip_code ="20007"

apts_20007_df = pd.DataFrame(apartments_20007)
apts_20007_df['also_price'] = apts_20007_df['also_price'].str[:-4]
apts_20007_df["Zip Code"] = zip_code
apts_20007_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Park Crest | 2324 41st St NW, Washington, DC",None,"$1,411+",None,20007
1,"3850 Tunlaw Rd NW #VPX588N0V, Washington, DC 2...","$1,437+/mo",,750 sqft,20007
2,"Kew Gardens | 2700 Q St NW, Washington, DC",None,"$1,932+",None,20007
3,"eaves Tunlaw Gardens | 3903 Davis Pl NW, Washi...",None,"$1,250+",None,20007
4,"2511 Q St NW #8, Washington, DC 20007","$1,500/mo",,574 sqft,20007
...,...,...,...,...,...
85,"2232 40th St NW, Washington, DC 20007","$1,500/mo",,700 sqft,20007
86,"4474 Macarthur Blvd NW #6, Washington, DC 20007","$1,485/mo",,740 sqft,20007
87,"3819 Davis Pl NW APT 1, Washington, DC 20007","$1,295/mo",,533 sqft,20007
88,"2725 39th St NW APT 405, Washington, DC 20007","$2,100/mo",,742 sqft,20007
89,"4545 Macarthur Blvd NW APT 206, Washington, DC...","$1,495/mo",,719 sqft,20007

In [174]:
#22209

apartments_22209 = []

In [180]:
url = 'https://www.zillow.com/arlington-va-22209/apartments/1-bedrooms/2_p'
browser.visit(url)

In [181]:
html = browser.html
soup = bs(html,'html.parser')

In [177]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22209.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Union on Queen | 1515 N Queen St, Arlington, VA
None
$1,831+ 1 bd
None
-------------
1565 N Colonial Ter #303, Arlington, VA 22209
<div class="list-card-price">$1,775/mo</div>
1 bd
607 sqft
-------------
Central Place | 1800 N Lynn St, Arlington, VA
None
$1,895+ 1 bd
None
-------------
Gables Pointe 14 | 1351 N Rolfe St, Arlington, VA
None
$1,699+ 1 bd
None
-------------
1215 N. Scott Street | 1215 N Scott St, Arlington, VA
None
$1,600+ 1 bd
None
-------------
Gables 12 Twenty One | 1221 N Pierce St, Arlington, VA
None
$1,410+ 1 bd
None
-------------
1800 Oak | 1800 N Oak St, Arlington, VA
None
$1,576+ 1 bd
None
-------------
1336 N Ode St, Arlington, VA
None
$1,350+ 1 bd
None
-------------
1820 N Quinn St #1820-307, Arlington, VA 22209
<div class="list-card-price">$1,462/mo</div>
1 bd
760 sqft
-------------
Avery Row | 1200 N Rolfe St, Arlington, VA
None
$2,082+ 1 bd
None
-------------
1121 Arlington Blvd, Arlington, VA
None
$1,350+ 1 bd
None
-------------
1530 Key Blvd, Arlington, VA
None
$1,750+ 1 bd
None
-------------
1550 Clarendon Blvd #52WP8MPPW, Arlington, VA 22209
<div class="list-card-price">$2,000+/mo</div>
1 bd
800 sqft
-------------
Bennett Park | 1601 Clarendon Blvd, Arlington, VA
None
$1,865+ 1 bd
None
-------------
1881 N Nash St, Arlington, VA
None
$4,095+ 1 bd
None
-------------
1021 Arlington Blvd, Arlington, VA
None
$1,250+ 1 bd
None
-------------
Whispering Oaks | 1310 N Oak St, Arlington, VA
None
$1,517+ 1 bd
None
-------------
Sedona;Slate | 1510 Clarendon Blvd, Arlington, VA
None
$1,644+ 1 bd
None
-------------
Swansen Apartments | 1800 16th St N, Arlington, VA
None
$1,450+ 1 bd
None
-------------
1111 Arlington Blvd, Arlington, VA
None
$1,295+ 1 bd
None
-------------
1111 19th St N, Arlington, VA
None
$2,100+ 1 bd
None
-------------
1415 N Oak St APT 404, Arlington, VA 22209
<div class="list-card-price">$1,650/mo</div>
1 bd
750 sqft
-------------
1600 N Oak St, Arlington, VA
None
$2,000+ 1 bd
None
-------------
Park Georgetown | 2100 N Pierce St, Arlington, VA
None
$1,341+ 1 bd
None
-------------
1011 Arlington Blvd, Arlington, VA
None
$1,650+ 1 bd
None
-------------
1700 Clarendon Blvd #112, Arlington, VA 22209
<div class="list-card-price">$4,000/mo</div>
1 bd
1,207 sqft
-------------
1401 N Rhodes St APT 203, Arlington, VA 22209
<div class="list-card-price">$1,895/mo</div>
1 bd
754 sqft
-------------
1200 N Nash St, Arlington, VA 22209
<div class="list-card-price">$1,950/mo</div>
1 bd
1,000 sqft
-------------
1575 N Colonial Ter APT 403, Arlington, VA 22209
<div class="list-card-price">$1,799/mo</div>
1 bd
650 sqft
-------------
1601 N Rhodes St, Arlington, VA 22209
<div class="list-card-price">$1,350/mo</div>
1 bd
750 sqft
-------------
2103 N Scott St, Arlington, VA
None
$1,590+ 1 bd
None
-------------
Rosslyn Heights | 1800 N Quinn St, Arlington, VA
None
$1,596+ 1 bd
None
-------------
1720 N Quinn St #B1, Arlington, VA 22209
<div class="list-card-price">$1,440/mo</div>
1 bd
1,520 sqft
-------------
1724 N Quinn St UNIT 305, Arlington, VA 22209
<div class="list-card-price">$1,490/mo</div>
1 bd
805 sqft
-------------
1724 N Quinn St APT 106, Arlington, VA 22209
<div class="list-card-price">$1,458/mo</div>
1 bd
641 sqft
-------------
1573 N Colonial Ter APT 402Y, Arlington, VA 22209
<div class="list-card-price">$1,800/mo</div>
1 bd
617 sqft
-------------
1230 N Quinn St #332, Arlington, VA 22209
<div class="list-card-price">$1,275/mo</div>
1 bd
-- sqft
-------------
1600 N Oak St APT 1701, Arlington, VA 22209
<div class="list-card-price">$2,150/mo</div>
1 bd
945 sqft
-------------
1510 12th St N APT 402, Arlington, VA 22209
<div class="list-card-price">$1,675/mo</div>
1 bd
895 sqft
-------------
1423 N Nash St APT 7, Arlington, VA 22209
<div class="list-card-price">$1,695/mo</div>
1 bd
715 sqft

In [178]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22209): 
    if word in stopwords:
        words.remove(word)

In [184]:
apartments_22209

[{'address': 'Union on Queen | 1515 N Queen St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,831+ 1 bd',
  'sqft': None},
 {'address': '1565 N Colonial Ter #303, Arlington, VA 22209',
  'price_monthly': '$1,775/mo',
  'also_price': '1 bd',
  'sqft': '607 sqft'},
 {'address': 'Central Place | 1800 N Lynn St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'Gables Pointe 14 | 1351 N Rolfe St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,699+ 1 bd',
  'sqft': None},
 {'address': '1215 N. Scott Street | 1215 N Scott St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'Gables 12 Twenty One | 1221 N Pierce St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,410+ 1 bd',
  'sqft': None},
 {'address': '1800 Oak | 1800 N Oak St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,576+ 1 bd',
  'sqft': None},
 {'address': '1336 N Ode St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '1820 N Quinn St #1820-307, Arlington, VA 22209',
  'price_monthly': '$1,462/mo',
  'also_price': '1 bd',
  'sqft': '760 sqft'},
 {'address': 'Avery Row | 1200 N Rolfe St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,082+ 1 bd',
  'sqft': None},
 {'address': '1121 Arlington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '1530 Key Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': '1550 Clarendon Blvd #52WP8MPPW, Arlington, VA 22209',
  'price_monthly': '$2,000+/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': 'Bennett Park | 1601 Clarendon Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,865+ 1 bd',
  'sqft': None},
 {'address': '1881 N Nash St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$4,095+ 1 bd',
  'sqft': None},
 {'address': '1021 Arlington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,250+ 1 bd',
  'sqft': None},
 {'address': 'Whispering Oaks | 1310 N Oak St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,517+ 1 bd',
  'sqft': None},
 {'address': 'Sedona;Slate | 1510 Clarendon Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,644+ 1 bd',
  'sqft': None},
 {'address': 'Swansen Apartments | 1800 16th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,450+ 1 bd',
  'sqft': None},
 {'address': '1111 Arlington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,295+ 1 bd',
  'sqft': None},
 {'address': '1111 19th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '1415 N Oak St APT 404, Arlington, VA 22209',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1600 N Oak St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': 'Park Georgetown | 2100 N Pierce St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,341+ 1 bd',
  'sqft': None},
 {'address': '1011 Arlington Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '1700 Clarendon Blvd #112, Arlington, VA 22209',
  'price_monthly': '$4,000/mo',
  'also_price': '1 bd',
  'sqft': '1,207 sqft'},
 {'address': '1401 N Rhodes St APT 203, Arlington, VA 22209',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '754 sqft'},
 {'address': '1200 N Nash St, Arlington, VA 22209',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '1575 N Colonial Ter APT 403, Arlington, VA 22209',
  'price_monthly': '$1,799/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1601 N Rhodes St, Arlington, VA 22209',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '2103 N Scott St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,590+ 1 bd',
  'sqft': None},
 {'address': 'Rosslyn Heights | 1800 N Quinn St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,596+ 1 bd',
  'sqft': None},
 {'address': '1720 N Quinn St #B1, Arlington, VA 22209',
  'price_monthly': '$1,440/mo',
  'also_price': '1 bd',
  'sqft': '1,520 sqft'},
 {'address': '1724 N Quinn St UNIT 305, Arlington, VA 22209',
  'price_monthly': '$1,490/mo',
  'also_price': '1 bd',
  'sqft': '805 sqft'},
 {'address': '1724 N Quinn St APT 106, Arlington, VA 22209',
  'price_monthly': '$1,458/mo',
  'also_price': '1 bd',
  'sqft': '641 sqft'},
 {'address': '1573 N Colonial Ter APT 402Y, Arlington, VA 22209',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '617 sqft'},
 {'address': '1230 N Quinn St #332, Arlington, VA 22209',
  'price_monthly': '$1,275/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1600 N Oak St APT 1701, Arlington, VA 22209',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '945 sqft'},
 {'address': '1510 12th St N APT 402, Arlington, VA 22209',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '895 sqft'},
 {'address': '1423 N Nash St APT 7, Arlington, VA 22209',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '715 sqft'}]

In [187]:
zip_code ="22209"

apts_22209_df = pd.DataFrame(apartments_22209)
apts_22209_df['also_price'] = apts_22209_df['also_price'].str[:-4]
apts_22209_df["Zip Code"] = zip_code
apts_22209_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Union on Queen | 1515 N Queen St, Arlington, VA",None,"$1,831+",None,22209
1,"1565 N Colonial Ter #303, Arlington, VA 22209","$1,775/mo",,607 sqft,22209
2,"Central Place | 1800 N Lynn St, Arlington, VA",None,"$1,895+",None,22209
3,"Gables Pointe 14 | 1351 N Rolfe St, Arlington, VA",None,"$1,699+",None,22209
4,"1215 N. Scott Street | 1215 N Scott St, Arling...",None,"$1,600+",None,22209
5,"Gables 12 Twenty One | 1221 N Pierce St, Arlin...",None,"$1,410+",None,22209
6,"1800 Oak | 1800 N Oak St, Arlington, VA",None,"$1,576+",None,22209
7,"1336 N Ode St, Arlington, VA",None,"$1,350+",None,22209
8,"1820 N Quinn St #1820-307, Arlington, VA 22209","$1,462/mo",,760 sqft,22209
9,"Avery Row | 1200 N Rolfe St, Arlington, VA",None,"$2,082+",None,22209
10,"1121 Arlington Blvd, Arlington, VA",None,"$1,350+",None,22209
11,"1530 Key Blvd, Arlington, VA",None,"$1,750+",None,22209
12,"1550 Clarendon Blvd #52WP8MPPW, Arlington, VA ...","$2,000+/mo",,800 sqft,22209
13,"Bennett Park | 1601 Clarendon Blvd, Arlington, VA",None,"$1,865+",None,22209
14,"1881 N Nash St, Arlington, VA",None,"$4,095+",None,22209
15,"1021 Arlington Blvd, Arlington, VA",None,"$1,250+",None,22209
16,"Whispering Oaks | 1310 N Oak St, Arlington, VA",None,"$1,517+",None,22209
17,"Sedona;Slate | 1510 Clarendon Blvd, Arlington, VA",None,"$1,644+",None,22209
18,"Swansen Apartments | 1800 16th St N, Arlington...",None,"$1,450+",None,22209
19,"1111 Arlington Blvd, Arlington, VA",None,"$1,295+",None,22209
20,"1111 19th St N, Arlington, VA",None,"$2,100+",None,22209
21,"1415 N Oak St APT 404, Arlington, VA 22209","$1,650/mo",,750 sqft,22209
22,"1600 N Oak St, Arlington, VA",None,"$2,000+",None,22209
23,"Park Georgetown | 2100 N Pierce St, Arlington, VA",None,"$1,341+",None,22209
24,"1011 Arlington Blvd, Arlington, VA",None,"$1,650+",None,22209
25,"1700 Clarendon Blvd #112, Arlington, VA 22209","$4,000/mo",,"1,207 sqft",22209
26,"1401 N Rhodes St APT 203, Arlington, VA 22209","$1,895/mo",,754 sqft,22209
27,"1200 N Nash St, Arlington, VA 22209","$1,950/mo",,"1,000 sqft",22209
28,"1575 N Colonial Ter APT 403, Arlington, VA 22209","$1,799/mo",,650 sqft,22209
29,"1601 N Rhodes St, Arlington, VA 22209","$1,350/mo",,750 sqft,22209
30,"2103 N Scott St, Arlington, VA",None,"$1,590+",None,22209
31,"Rosslyn Heights | 1800 N Quinn St, Arlington, VA",None,"$1,596+",None,22209
32,"1720 N Quinn St #B1, Arlington, VA 22209","$1,440/mo",,"1,520 sqft",22209
33,"1724 N Quinn St UNIT 305, Arlington, VA 22209","$1,490/mo",,805 sqft,22209
34,"1724 N Quinn St APT 106, Arlington, VA 22209","$1,458/mo",,641 sqft,22209
35,"1573 N Colonial Ter APT 402Y, Arlington, VA 22209","$1,800/mo",,617 sqft,22209
36,"1230 N Quinn St #332, Arlington, VA 22209","$1,275/mo",,-- sqft,22209
37,"1600 N Oak St APT 1701, Arlington, VA 22209","$2,150/mo",,945 sqft,22209
38,"1510 12th St N APT 402, Arlington, VA 22209","$1,675/mo",,895 sqft,22209
39,"1423 N Nash St APT 7, Arlington, VA 22209","$1,695/mo",,715 sqft,22209

In [188]:
#20037

apartments_20037 = []

In [194]:
url = 'https://www.zillow.com/washington-dc-20037/apartments/1-bedrooms/2_p'
browser.visit(url)

In [195]:
html = browser.html
soup = bs(html,'html.parser')

In [196]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20037.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1140 23rd St NW, Washington, DC
None
$2,300+ 1 bd
None
-------------
1111 25th St NW, Washington, DC
None
$2,250+ 1 bd
None
-------------
1121 24th St NW APT 308, Washington, DC 20037
<div class="list-card-price">$2,200/mo</div>
1 bd
577 sqft
-------------
2401 H St NW, Washington, DC
None
$1,795+ 1 bd
None
-------------
3 Washington Cir NW, Washington, DC
None
$2,300+ 1 bd
None
-------------
1001 26th St NW, Washington, DC
None
$1,800+ 1 bd
None
-------------
950 25th St NW, Washington, DC 20037
<div class="list-card-price">$2,000/mo</div>
1 bd
550 sqft
-------------
2401 Penn Avenue LLC | 2401 Pennsylvania Ave NW, Washington, DC
None
$3,985+ 1 bd
None
-------------
2311 M St NW, Washington, DC
None
$2,000+ 1 bd
None
-------------
The Savoy | 1101 New Hampshire Ave NW, Washington, DC
None
$2,100+ 1 bd
None
-------------
2405 I St NW SUITE 2B, Washington, DC 20037
<div class="list-card-price">$2,150/mo</div>
1 bd
703 sqft
-------------
2475 Virginia Ave NW, Washington, DC
None
$1,775+ 1 bd
None
-------------
2119 N St NW APT 2, Washington, DC 20037
<div class="list-card-price">$1,799/mo</div>
1 bd
500 sqft
-------------
1006 E Saint Expy NW #B, Washington, DC 20037
<div class="list-card-price">$1,550/mo</div>
1 bd
2,294 sqft
-------------
1099 22nd St NW APT 309, Washington, DC 20037
<div class="list-card-price">$2,750/mo</div>
1 bd
963 sqft
-------------
2501 K St NW APT 6B, Washington, DC 20037
<div class="list-card-price">$2,250/mo</div>
1 bd
728 sqft
-------------
730 24th St NW APT 621, Washington, DC 20037
<div class="list-card-price">$2,131/mo</div>
1 bd
750 sqft
-------------
2555 Pennsylvania Ave NW APT 707, Washington, DC 20037
<div class="list-card-price">$3,000/mo</div>
1 bd
862 sqft
-------------
939 26th St NW, Washington, DC 20037
<div class="list-card-price">$1,695/mo</div>
1 bd
700 sqft

In [197]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20037): 
    if word in stopwords:
        words.remove(word)

In [198]:
apartments_20037

[{'address': '2400 M | 2400 M St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,481+ 1 bd',
  'sqft': None},
 {'address': 'Westbrooke Place | 2201 N St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,091+ 1 bd',
  'sqft': None},
 {'address': '601 24th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,350+ 1 bd',
  'sqft': None},
 {'address': 'Winston House | 2140 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '950 25th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': '1124 25th St NW APT 202, Washington, DC 20037',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '450 sqft'},
 {'address': '2416 K St NW APT 304, Washington, DC 20037',
  'price_monthly': '$2,290/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '607 24th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': 'Residences on The Avenue | 2221 I St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,990+ 1 bd',
  'sqft': None},
 {'address': 'Columbia Plaza Apartments | 2400 Virginia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': 'Westpark | 2130 P St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,299+ 1 bd',
  'sqft': None},
 {'address': '2424 Penn | 2424 Pennsylvania Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': '2130 N St NW APT 509, Washington, DC 20037',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '510 sqft'},
 {'address': '2514 K St NW, Washington, DC 20037',
  'price_monthly': '$1,890/mo',
  'also_price': '1 bd',
  'sqft': '760 sqft'},
 {'address': '2700 Virginia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,950+ 1 bd',
  'sqft': None},
 {'address': 'WestEnd25 | 1255 25th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,880+ 1 bd',
  'sqft': None},
 {'address': '2515 K St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'Boathouse | 2601 Virginia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,195+ 1 bd',
  'sqft': None},
 {'address': 'West End Residences | 1221 24th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,130+ 1 bd',
  'sqft': None},
 {'address': '940 25th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,850+ 1 bd',
  'sqft': None},
 {'address': '2209 Washington Cir NW APT 2, Washington, DC 20037',
  'price_monthly': '$2,095/mo',
  'also_price': '1 bd',
  'sqft': '521 sqft'},
 {'address': '2301 N St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,350+ 1 bd',
  'sqft': None},
 {'address': '2114 N St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '2555 Pennsylvania Ave NW APT 1019, Washington, DC 20037',
  'price_monthly': '$2,995/mo',
  'also_price': '1 bd',
  'sqft': '950 sqft'},
 {'address': '1230 23rd St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,170+ 1 bd',
  'sqft': None},
 {'address': '955 26th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': '2141 P St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,400+ 1 bd',
  'sqft': None},
 {'address': '1010 25th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': 'Legacy West End | 1255 22nd St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,495+ 1 bd',
  'sqft': None},
 {'address': '2504-M NW Street Expy, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,580+ 1 bd',
  'sqft': None},
 {'address': '2201 K St NW APT 1, Washington, DC 20037',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '2106 O St NW #1, Washington, DC 20037',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '2425 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,900+ 1 bd',
  'sqft': None},
 {'address': '2119 N St NW, Washington, DC 20037',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '2141 I St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,550+ 1 bd',
  'sqft': None},
 {'address': '2201 L St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': 'August | 2147 O St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,974+ 1 bd',
  'sqft': None},
 {'address': '2400 Pennsylvania Avenue Apartments | 2400 Pennsylvania Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,830+ 1 bd',
  'sqft': None},
 {'address': 'The 925 Apartments | 925 25th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,827+ 1 bd',
  'sqft': None},
 {'address': '1201 24th St NW, Washington, DC 20037',
  'price_monthly': '$16,000/mo',
  'also_price': '1 bd',
  'sqft': '1,022 sqft'},
 {'address': '1140 23rd St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,300+ 1 bd',
  'sqft': None},
 {'address': '1111 25th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,250+ 1 bd',
  'sqft': None},
 {'address': '1121 24th St NW APT 308, Washington, DC 20037',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '577 sqft'},
 {'address': '2401 H St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': '3 Washington Cir NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,300+ 1 bd',
  'sqft': None},
 {'address': '1001 26th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '950 25th St NW, Washington, DC 20037',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '2401 Penn Avenue LLC | 2401 Pennsylvania Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,985+ 1 bd',
  'sqft': None},
 {'address': '2311 M St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': 'The Savoy | 1101 New Hampshire Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '2405 I St NW SUITE 2B, Washington, DC 20037',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '703 sqft'},
 {'address': '2475 Virginia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,775+ 1 bd',
  'sqft': None},
 {'address': '2119 N St NW APT 2, Washington, DC 20037',
  'price_monthly': '$1,799/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '1006 E Saint Expy NW #B, Washington, DC 20037',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '2,294 sqft'},
 {'address': '1099 22nd St NW APT 309, Washington, DC 20037',
  'price_monthly': '$2,750/mo',
  'also_price': '1 bd',
  'sqft': '963 sqft'},
 {'address': '2501 K St NW APT 6B, Washington, DC 20037',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '728 sqft'},
 {'address': '730 24th St NW APT 621, Washington, DC 20037',
  'price_monthly': '$2,131/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '2555 Pennsylvania Ave NW APT 707, Washington, DC 20037',
  'price_monthly': '$3,000/mo',
  'also_price': '1 bd',
  'sqft': '862 sqft'},
 {'address': '939 26th St NW, Washington, DC 20037',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'}]

In [199]:
zip_code ="20037"

apts_20037_df = pd.DataFrame(apartments_20037)
apts_20037_df['also_price'] = apts_20037_df['also_price'].str[:-4]
apts_20037_df["Zip Code"] = zip_code
apts_20037_df

,address,price_monthly,also_price,sqft,Zip Code
0,"2400 M | 2400 M St NW, Washington, DC",None,"$2,481+",None,20037
1,"Westbrooke Place | 2201 N St NW, Washington, DC",None,"$2,091+",None,20037
2,"601 24th St NW, Washington, DC",None,"$2,350+",None,20037
3,"Winston House | 2140 L St NW, Washington, DC",None,"$2,100+",None,20037
4,"950 25th St NW, Washington, DC",None,"$1,950+",None,20037
5,"1124 25th St NW APT 202, Washington, DC 20037","$1,895/mo",,450 sqft,20037
6,"2416 K St NW APT 304, Washington, DC 20037","$2,290/mo",,500 sqft,20037
7,"607 24th St NW, Washington, DC",None,"$1,400+",None,20037
8,"Residences on The Avenue | 2221 I St NW, Washi...",None,"$1,990+",None,20037
9,Columbia Plaza Apartments | 2400 Virginia Ave ...,None,"$1,995+",None,20037
10,"Westpark | 2130 P St NW, Washington, DC",None,"$2,299+",None,20037
11,"2424 Penn | 2424 Pennsylvania Ave NW, Washingt...",None,"$1,950+",None,20037
12,"2130 N St NW APT 509, Washington, DC 20037","$1,900/mo",,510 sqft,20037
13,"2514 K St NW, Washington, DC 20037","$1,890/mo",,760 sqft,20037
14,"2700 Virginia Ave NW, Washington, DC",None,"$2,950+",None,20037
15,"WestEnd25 | 1255 25th St NW, Washington, DC",None,"$1,880+",None,20037
16,"2515 K St NW, Washington, DC",None,"$1,600+",None,20037
17,"Boathouse | 2601 Virginia Ave NW, Washington, DC",None,"$3,195+",None,20037
18,"West End Residences | 1221 24th St NW, Washing...",None,"$2,130+",None,20037
19,"940 25th St NW, Washington, DC",None,"$1,850+",None,20037
20,"2209 Washington Cir NW APT 2, Washington, DC 2...","$2,095/mo",,521 sqft,20037
21,"2301 N St NW, Washington, DC",None,"$2,350+",None,20037
22,"2114 N St NW, Washington, DC",None,"$1,700+",None,20037
23,"2555 Pennsylvania Ave NW APT 1019, Washington,...","$2,995/mo",,950 sqft,20037
24,"1230 23rd St NW, Washington, DC",None,"$2,170+",None,20037
25,"955 26th St NW, Washington, DC",None,"$1,950+",None,20037
26,"2141 P St NW, Washington, DC",None,"$2,400+",None,20037
27,"1010 25th St NW, Washington, DC",None,"$1,750+",None,20037
28,"Legacy West End | 1255 22nd St NW, Washington, DC",None,"$2,495+",None,20037
29,"2504-M NW Street Expy, Washington, DC",None,"$1,580+",None,20037
30,"2201 K St NW APT 1, Washington, DC 20037","$2,100/mo",,500 sqft,20037
31,"2106 O St NW #1, Washington, DC 20037","$2,200/mo",,800 sqft,20037
32,"2425 L St NW, Washington, DC",None,"$2,900+",None,20037
33,"2119 N St NW, Washington, DC 20037","$2,300/mo",,600 sqft,20037
34,"2141 I St NW, Washington, DC",None,"$1,550+",None,20037
35,"2201 L St NW, Washington, DC",None,"$1,750+",None,20037
36,"August | 2147 O St NW, Washington, DC",None,"$1,974+",None,20037
37,2400 Pennsylvania Avenue Apartments | 2400 Pen...,None,"$1,830+",None,20037
38,"The 925 Apartments | 925 25th St NW, Washingto...",None,"$1,827+",None,20037
39,"1201 24th St NW, Washington, DC 20037","$16,000/mo",,"1,022 sqft",20037
40,"1140 23rd St NW, Washington, DC",None,"$2,300+",None,20037
41,"1111 25th St NW, Washington, DC",None,"$2,250+",None,20037
42,"1121 24th St NW APT 308, Washington, DC 20037","$2,200/mo",,577 sqft,20037
43,"2401 H St NW, Washington, DC",None,"$1,795+",None,20037
44,"3 Washington Cir NW, Washington, DC",None,"$2,300+",None,20037
45,"1001 26th St NW, Washington, DC",None,"$1,800+",None,20037
46,"950 25th St NW, Washington, DC 20037","$2,000/mo",,550 sqft,20037
47,2401 Penn Avenue LLC | 2401 Pennsylvania Ave N...,None,"$3,985+",None,20037
48,"2311 M St NW, Washington, DC",None,"$2,000+",None,20037
49,"The Savoy | 1101 New Hampshire Ave NW, Washing...",None,"$2,100+",None,20037
50,"2405 I St NW SUITE 2B, Washington, DC 20037","$2,150/mo",,703 sqft,20037
51,"2475 Virginia Ave NW, Washington, DC",None,"$1,775+",None,20037
52,"2119 N St NW APT 2, Washington, DC 20037","$1,799/mo",,500 sqft,20037
53,"1006 E Saint Expy NW #B, Washington, DC 20037","$1,550/mo",,"2,294 sqft",20037
54,"1099 22nd St NW APT 309, Washington, DC 20037","$2,750/mo",,963 sqft,20037
55,"2501 K St NW APT 6B, Washington, DC 20037","$2,250/mo",,728 sqft,20037
56,"730 24th St NW APT 621, Washington, DC 20037","$2,131/mo",,750 sqft,20037
57,"2555 Pennsylvania Ave NW APT 707, Washington, ...","$3,000/mo",,862 sqft,20037
58,"939 26th St NW, Washington, DC 20037","$1,695/mo",,700 sqft,20037

In [200]:
#20005

apartments_20005 = []

In [206]:
url = 'https://www.zillow.com/washington-dc-20005/apartments/1-bedrooms/2_p'
browser.visit(url)

In [207]:
html = browser.html
soup = bs(html,'html.parser')

In [208]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20005.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1312 Massachusetts Ave NW, Washington, DC
None
$2,200+ 1 bd
None
-------------
1113 M St NW #2, Washington, DC 20005
<div class="list-card-price">$1,850/mo</div>
1 bd
750 sqft
-------------
1205 N St NW, Washington, DC 20005
<div class="list-card-price">$2,150/mo</div>
1 bd
700 sqft
-------------
1311 Rhode Island Ave NW APT 2, Washington, DC 20005
<div class="list-card-price">$2,000/mo</div>
1 bd
550 sqft
-------------
1521 Kingman Pl NW, Washington, DC
None
$1,725+ 1 bd
None
-------------
1133 13th St NW, Washington, DC
None
$1,760+ 1 bd
None
-------------
1449 P St NW #409, Washington, DC 20005
<div class="list-card-price">$2,880/mo</div>
1 bd
679 sqft
-------------
1125 12th St NW, Washington, DC
None
$1,750+ 1 bd
None
-------------
1301 Vermont Ave NW APT 707, Washington, DC 20005
<div class="list-card-price">$1,845/mo</div>
1 bd
597 sqft
-------------
1334 13th St NW APT B, Washington, DC 20005
<div class="list-card-price">$1,650/mo</div>
1 bd
600 sqft
-------------
1313 Vermont Ave NW #9, Washington, DC 20005
<div class="list-card-price">$2,500/mo</div>
1 bd
700 sqft
-------------
1530 14th St NW FLOOR 3, Washington, DC 20005
<div class="list-card-price">$4,000/mo</div>
1 bd
900 sqft
-------------
1322 15th St NW APT 21, Washington, DC 20005
<div class="list-card-price">$1,550/mo</div>
1 bd
600 sqft
-------------
1215 N St NW APT 4, Washington, DC 20005
<div class="list-card-price">$2,200/mo</div>
1 bd
628 sqft
-------------
1306 12th St NW APT C, Washington, DC 20005
<div class="list-card-price">$2,500/mo</div>
1 bd
900 sqft
-------------
1239 Vermont Ave NW, Washington, DC
None
$1,400+ 1 bd
None
-------------
1318 14th St NW, Washington, DC
None
$1,675+ 1 bd
None
-------------
1245 13th St NW APT 314, Washington, DC 20005
<div class="list-card-price">$1,950/mo</div>
1 bd
700 sqft
-------------
1501 Vermont Ave NW #A, Washington, DC 20005
<div class="list-card-price">$3,130/mo</div>
1 bd
820 sqft
-------------
1306 O St NW APT 203, Washington, DC 20005
<div class="list-card-price">$2,200/mo</div>
1 bd
643 sqft
-------------
1115 12th St NW APT 105, Washington, DC 20005
<div class="list-card-price">$1,850/mo</div>
1 bd
700 sqft
-------------
1420 N St NW, Washington, DC
None
$1,741+ 1 bd
None
-------------
1508 13th St NW APT 2, Washington, DC 20005
<div class="list-card-price">$2,295/mo</div>
1 bd
911 sqft

In [209]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20005): 
    if word in stopwords:
        words.remove(word)

In [210]:
apartments_20005

[{'address': 'The Bentley | 1328 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,799+ 1 bd',
  'sqft': None},
 {'address': '1150 K St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': 'The Woodward Building Apartments | 733 15th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': 'Latrobe Apartment Homes | 1325 15th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,849+ 1 bd',
  'sqft': None},
 {'address': 'Camden Grand Parc | 910 15th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,819+ 1 bd',
  'sqft': None},
 {'address': '1210 Mass | 1210 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,057+ 1 bd',
  'sqft': None},
 {'address': 'The Cambridge | 1221 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,070+ 1 bd',
  'sqft': None},
 {'address': '1500 Mass | 1500 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,657+ 1 bd',
  'sqft': None},
 {'address': 'Windsor House | 1444 Rhode Island Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,825+ 1 bd',
  'sqft': None},
 {'address': '1300 N St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': 'Post Massachusetts Avenue | 1499 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,040+ 1 bd',
  'sqft': None},
 {'address': '1445 P St NW #A209, Washington, DC 20005',
  'price_monthly': '$2,470/mo',
  'also_price': '1 bd',
  'sqft': '679 sqft'},
 {'address': '1301 Thomas Circle | 1301 M St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,024+ 1 bd',
  'sqft': None},
 {'address': '1200 N St NW #RG1U1J3PP, Washington, DC 20005',
  'price_monthly': '$1,899+/mo',
  'also_price': '1 bd',
  'sqft': '695 sqft'},
 {'address': 'The Hudson Apartments | 1425 P St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,245+ 1 bd',
  'sqft': None},
 {'address': '1417 P St NW #203, Washington, DC 20005',
  'price_monthly': '$2,740/mo',
  'also_price': '1 bd',
  'sqft': '676 sqft'},
 {'address': '1303 P St NW #405, Washington, DC 20005',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '698 sqft'},
 {'address': '1223 O St NW #1/2, Washington, DC 20005',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '888 sqft'},
 {'address': 'Belvedere | 1301 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,811+ 1 bd',
  'sqft': None},
 {'address': 'Andover House | 1200 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,929+ 1 bd',
  'sqft': None},
 {'address': '1111 M St NW APT 3, Washington, DC 20005',
  'price_monthly': '$2,475/mo',
  'also_price': '1 bd',
  'sqft': '756 sqft'},
 {'address': '1314 14th St NW APT 302, Washington, DC 20005',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '405 sqft'},
 {'address': '1314 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '733 15th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$3,260+ 1 bd',
  'sqft': None},
 {'address': '1110 Rhode Island Ave NW #BASEMENT, Washington, DC 20005',
  'price_monthly': '$2,400/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '1332 15th St NW APT B4, Washington, DC 20005',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '420 sqft'},
 {'address': '1445 P St NW #409, Washington, DC 20005',
  'price_monthly': '$3,140/mo',
  'also_price': '1 bd',
  'sqft': '679 sqft'},
 {'address': '1401 Church St NW APT 515, Washington, DC 20005',
  'price_monthly': '$3,500/mo',
  'also_price': '1 bd',
  'sqft': '975 sqft'},
 {'address': '1120 Rhode Island Ave NW APT 3, Washington, DC 20005',
  'price_monthly': '$2,299/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': 'Newport West | 1415 Rhode Island Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': '1112 Rhode Island Ave NW FLOOR 2, Washington, DC 20005',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '1,017 sqft'},
 {'address': '1325 13th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': 'The Seville | 1401 N St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '1211 13th St NW APT 307, Washington, DC 20005',
  'price_monthly': '$2,600/mo',
  'also_price': '1 bd',
  'sqft': '950 sqft'},
 {'address': '1133 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,200+ 1 bd',
  'sqft': None},
 {'address': '1202 14th St NW #206, Washington, DC 20005',
  'price_monthly': '$2,990/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1225 13th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,000+ 1 bd',
  'sqft': None},
 {'address': '1441 Rhode Island Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,300+ 1 bd',
  'sqft': None},
 {'address': '1201 Rhode Island Ave NW #B, Washington, DC 20005',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '735 15th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,720+ 1 bd',
  'sqft': None},
 {'address': '1312 Massachusetts Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,200+ 1 bd',
  'sqft': None},
 {'address': '1113 M St NW #2, Washington, DC 20005',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1205 N St NW, Washington, DC 20005',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1311 Rhode Island Ave NW APT 2, Washington, DC 20005',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '1521 Kingman Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,725+ 1 bd',
  'sqft': None},
 {'address': '1133 13th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,760+ 1 bd',
  'sqft': None},
 {'address': '1449 P St NW #409, Washington, DC 20005',
  'price_monthly': '$2,880/mo',
  'also_price': '1 bd',
  'sqft': '679 sqft'},
 {'address': '1125 12th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': '1301 Vermont Ave NW APT 707, Washington, DC 20005',
  'price_monthly': '$1,845/mo',
  'also_price': '1 bd',
  'sqft': '597 sqft'},
 {'address': '1334 13th St NW APT B, Washington, DC 20005',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1313 Vermont Ave NW #9, Washington, DC 20005',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1530 14th St NW FLOOR 3, Washington, DC 20005',
  'price_monthly': '$4,000/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '1322 15th St NW APT 21, Washington, DC 20005',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1215 N St NW APT 4, Washington, DC 20005',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '628 sqft'},
 {'address': '1306 12th St NW APT C, Washington, DC 20005',
  'price_monthly': '$2,500/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '1239 Vermont Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '1318 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,675+ 1 bd',
  'sqft': None},
 {'address': '1245 13th St NW APT 314, Washington, DC 20005',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1501 Vermont Ave NW #A, Washington, DC 20005',
  'price_monthly': '$3,130/mo',
  'also_price': '1 bd',
  'sqft': '820 sqft'},
 {'address': '1306 O St NW APT 203, Washington, DC 20005',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '643 sqft'},
 {'address': '1115 12th St NW APT 105, Washington, DC 20005',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1420 N St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,741+ 1 bd',
  'sqft': None},
 {'address': '1508 13th St NW APT 2, Washington, DC 20005',
  'price_monthly': '$2,295/mo',
  'also_price': '1 bd',
  'sqft': '911 sqft'}]

In [211]:
zip_code ="20005"

apts_20005_df = pd.DataFrame(apartments_20005)
apts_20005_df['also_price'] = apts_20005_df['also_price'].str[:-4]
apts_20005_df["Zip Code"] = zip_code
apts_20005_df

,address,price_monthly,also_price,sqft,Zip Code
0,"The Bentley | 1328 14th St NW, Washington, DC",None,"$1,799+",None,20005
1,"1150 K St NW, Washington, DC",None,"$1,800+",None,20005
2,The Woodward Building Apartments | 733 15th St...,None,"$1,950+",None,20005
3,"Latrobe Apartment Homes | 1325 15th St NW, Was...",None,"$1,849+",None,20005
4,"Camden Grand Parc | 910 15th St NW, Washington...",None,"$1,819+",None,20005
...,...,...,...,...,...
58,"1501 Vermont Ave NW #A, Washington, DC 20005","$3,130/mo",,820 sqft,20005
59,"1306 O St NW APT 203, Washington, DC 20005","$2,200/mo",,643 sqft,20005
60,"1115 12th St NW APT 105, Washington, DC 20005","$1,850/mo",,700 sqft,20005
61,"1420 N St NW, Washington, DC",None,"$1,741+",None,20005
62,"1508 13th St NW APT 2, Washington, DC 20005","$2,295/mo",,911 sqft,20005

In [212]:
#20010

apartments_20010 = []

In [218]:
url = 'https://www.zillow.com/washington-dc-20010/apartments/1-bedrooms/2_p'
browser.visit(url)

In [219]:
html = browser.html
soup = bs(html,'html.parser')

In [220]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20010.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1511 Park Rd NW, Washington, DC
None
$1,895+ 1 bd
None
-------------
1476 Newton St NW #2, Washington, DC 20010
<div class="list-card-price">$1,195/mo</div>
1 bd
-- sqft
-------------
1630 Park | 1630 Park Rd NW, Washington, DC
None
$1,897+ 1 bd
None
-------------
3740 9th St NW UNIT B, Washington, DC 20010
<div class="list-card-price">$1,550/mo</div>
1 bd
630 sqft
-------------
1810 Ingleside Ter NW UNIT 4, Washington, DC 20010
<div class="list-card-price">$2,295/mo</div>
1 bd
839 sqft
-------------
1483 Newton St NW #1483-102, Washington, DC 20010
<div class="list-card-price">$1,599/mo</div>
1 bd
502 sqft
-------------
1030 Kenyon St NW APT B, Washington, DC 20010
<div class="list-card-price">$1,600/mo</div>
1 bd
908 sqft
-------------
1507 Park Rd NW #4, Washington, DC 20010
<div class="list-card-price">$1,600/mo</div>
1 bd
-- sqft
-------------
Park Marconi | 3150 16th St NW, Washington, DC
None
$1,809+ 1 bd
None
-------------
1901 Ingleside Ter NW APT 101, Washington, DC 20010
<div class="list-card-price">$2,000/mo</div>
1 bd
650 sqft
-------------
1700 Irving St NW #302, Washington, DC 20010
<div class="list-card-price">$1,399/mo</div>
1 bd
-- sqft
-------------
Park Pleasant Apartments | 3339 Mount Pleasant St NW, Washington, DC
None
$1,237+ 1 bd
None
-------------
3420 16th St NW APT 404, Washington, DC 20010
<div class="list-card-price">$1,700/mo</div>
1 bd
585 sqft
-------------
1457 Park Rd NW APT 404, Washington, DC 20010
<div class="list-card-price">$1,600/mo</div>
1 bd
500 sqft
-------------
3200 18th St NW #2, Washington, DC 20010
<div class="list-card-price">$2,095/mo</div>
1 bd
1,100 sqft
-------------
3721 Georgia Ave NW #2, Washington, DC 20010
<div class="list-card-price">$2,000/mo</div>
1 bd
950 sqft
-------------
1315 Park Rd NW, Washington, DC
None
$1,350+ 1 bd
None
-------------
3537 10th St NW #1, Washington, DC 20010
<div class="list-card-price">$1,395/mo</div>
1 bd
-- sqft
-------------
3427 13th St NW #104, Washington, DC 20010
<div class="list-card-price">$1,790/mo</div>
1 bd
780 sqft
-------------
1445 Oak St NW #1, Washington, DC 20010
<div class="list-card-price">$1,650/mo</div>
1 bd
-- sqft
-------------
1436 Spring Rd NW #B, Washington, DC 20010
<div class="list-card-price">$2,100/mo</div>
1 bd
2,295 sqft
-------------
3606 13th St NW APT 2, Washington, DC 20010
<div class="list-card-price">$1,350/mo</div>
1 bd
650 sqft
-------------
3360 18th St NW, Washington, DC 20010
<div class="list-card-price">$1,750/mo</div>
1 bd
850 sqft
-------------
3654 New Hampshire Ave NW, Washington, DC
None
$1,399+ 1 bd
None
-------------
1445 Park Rd NW #208, Washington, DC 20010
<div class="list-card-price">$1,397/mo</div>
1 bd
525 sqft
-------------
3413 Brown St NW #1, Washington, DC 20010
<div class="list-card-price">$1,750/mo</div>
1 bd
1,058 sqft
-------------
3422 Georgia Ave NW, Washington, DC
None
$1,625+ 1 bd
None
-------------
3433 Mount Pleasant St NW APT 103, Washington, DC 20010
<div class="list-card-price">$1,162/mo</div>
1 bd
-- sqft
-------------
1341 Monroe St NW, Washington, DC 20010
<div class="list-card-price">$1,395/mo</div>
1 bd
3,027 sqft
-------------
3534 10th St NW APT 150, Washington, DC 20010
<div class="list-card-price">$1,450/mo</div>
1 bd
424 sqft
-------------
(undisclosed Address), Washington, DC 20010
<div class="list-card-price">$1,999/mo</div>
1 bd
1,000 sqft

In [221]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20010): 
    if word in stopwords:
        words.remove(word)

In [222]:
apartments_20010

[{'address': '3427 13th St NW APT 1, Washington, DC 20010',
  'price_monthly': '$1,590/mo',
  'also_price': '1 bd',
  'sqft': '760 sqft'},
 {'address': 'Allegro | 3460 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,611+ 1 bd',
  'sqft': None},
 {'address': 'Kenyon House Apartments | 1349 Kenyon St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,725+ 1 bd',
  'sqft': None},
 {'address': '1515 Ogden St NW APT 622, Washington, DC 20010',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1615 Kenyon St NW APT 52, Washington, DC 20010',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '620 sqft'},
 {'address': 'Holmead Apartments | 3435 Holmead Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,399+ 1 bd',
  'sqft': None},
 {'address': '608 Kenyon St NW #B, Washington, DC 20010',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '2,520 sqft'},
 {'address': 'The Vintage on 16th | 3146 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,885+ 1 bd',
  'sqft': None},
 {'address': '1356 Irving St NW #2, Washington, DC 20010',
  'price_monthly': '$2,700/mo',
  'also_price': '1 bd',
  'sqft': '892 sqft'},
 {'address': 'Woodner | 3636 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,499+ 1 bd',
  'sqft': None},
 {'address': '1674 Irving St NW APT 2, Washington, DC 20010',
  'price_monthly': '$2,050/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '3308-3312 Sherman Ave NW #S5PCYCQ6M, Washington, DC 20010',
  'price_monthly': '$1,625+/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1404 Irving St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,620+ 1 bd',
  'sqft': None},
 {'address': 'Newton Towers | 1435 Newton St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': 'Highland Park at Columbia Heights Metro | 1400 Irving St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '(undisclosed Address), Washington, DC 20010',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '510 sqft'},
 {'address': '3223 Hiatt Pl NW APT B, Washington, DC 20010',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': '1661 Park Rd NW APT B2, Washington, DC 20010',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '498 sqft'},
 {'address': 'Sarbin Towers | 3132 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,675+ 1 bd',
  'sqft': None},
 {'address': '3205 Georgia Ave NW UNIT 302, Washington, DC 20010',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '1527 Park Rd NW APT 302, Washington, DC 20010',
  'price_monthly': '$1,995/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1451 Park Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,599+ 1 bd',
  'sqft': None},
 {'address': '1850 Ingleside Ter NW APT 1, Washington, DC 20010',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '930 sqft'},
 {'address': '3501 13th St NW #205, Washington, DC 20010',
  'price_monthly': '$1,599/mo',
  'also_price': '1 bd',
  'sqft': '460 sqft'},
 {'address': '3426 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,395+ 1 bd',
  'sqft': None},
 {'address': '3115 Mt. Pleasant Street NW | 3115 Mount Pleasant St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,599+ 1 bd',
  'sqft': None},
 {'address': '809 Otis Pl NW APT 105, Washington, DC 20010',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '675 sqft'},
 {'address': '3318 Georgia Ave NW APT B3, Washington, DC 20010',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '518 sqft'},
 {'address': '3701 16th St NW #958829, Washington, DC 20010',
  'price_monthly': '$1,650+/mo',
  'also_price': '1 bd',
  'sqft': '674 sqft'},
 {'address': '1717 Kilbourne Pl NW #B, Washington, DC 20010',
  'price_monthly': '$1,575/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '1361 Parkwood Pl NW #B, Washington, DC 20010',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '780 sqft'},
 {'address': 'Alpha House | 3520 Center St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,375+ 1 bd',
  'sqft': None},
 {'address': '1354 Kenyon St NW APT 2, Washington, DC 20010',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '719 sqft'},
 {'address': '3513 13th St NW, Washington, DC 20010',
  'price_monthly': '$1,530/mo',
  'also_price': '1 bd',
  'sqft': '525 sqft'},
 {'address': '3620 16th St NW #604, Washington, DC 20010',
  'price_monthly': '$1,613/mo',
  'also_price': '1 bd',
  'sqft': '735 sqft'},
 {'address': '430 Irving St NW APT 206, Washington, DC 20010',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '531 sqft'},
 {'address': '1495 Newton St NW APT B101, Washington, DC 20010',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '678 sqft'},
 {'address': '1514 Newton St NW APT 103, Washington, DC 20010',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '530 sqft'},
 {'address': 'New Hampshire House | 3728 New Hampshire Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,399+ 1 bd',
  'sqft': None},
 {'address': '619 Quebec Pl NW #B, Washington, DC 20010',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '830 sqft'},
 {'address': '1511 Park Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': '1476 Newton St NW #2, Washington, DC 20010',
  'price_monthly': '$1,195/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1630 Park | 1630 Park Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,897+ 1 bd',
  'sqft': None},
 {'address': '3740 9th St NW UNIT B, Washington, DC 20010',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '630 sqft'},
 {'address': '1810 Ingleside Ter NW UNIT 4, Washington, DC 20010',
  'price_monthly': '$2,295/mo',
  'also_price': '1 bd',
  'sqft': '839 sqft'},
 {'address': '1483 Newton St NW #1483-102, Washington, DC 20010',
  'price_monthly': '$1,599/mo',
  'also_price': '1 bd',
  'sqft': '502 sqft'},
 {'address': '1030 Kenyon St NW APT B, Washington, DC 20010',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '908 sqft'},
 {'address': '1507 Park Rd NW #4, Washington, DC 20010',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'Park Marconi | 3150 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,809+ 1 bd',
  'sqft': None},
 {'address': '1901 Ingleside Ter NW APT 101, Washington, DC 20010',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1700 Irving St NW #302, Washington, DC 20010',
  'price_monthly': '$1,399/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'Park Pleasant Apartments | 3339 Mount Pleasant St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,237+ 1 bd',
  'sqft': None},
 {'address': '3420 16th St NW APT 404, Washington, DC 20010',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '585 sqft'},
 {'address': '1457 Park Rd NW APT 404, Washington, DC 20010',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '3200 18th St NW #2, Washington, DC 20010',
  'price_monthly': '$2,095/mo',
  'also_price': '1 bd',
  'sqft': '1,100 sqft'},
 {'address': '3721 Georgia Ave NW #2, Washington, DC 20010',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '950 sqft'},
 {'address': '1315 Park Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,350+ 1 bd',
  'sqft': None},
 {'address': '3537 10th St NW #1, Washington, DC 20010',
  'price_monthly': '$1,395/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '3427 13th St NW #104, Washington, DC 20010',
  'price_monthly': '$1,790/mo',
  'also_price': '1 bd',
  'sqft': '780 sqft'},
 {'address': '1445 Oak St NW #1, Washington, DC 20010',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1436 Spring Rd NW #B, Washington, DC 20010',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '2,295 sqft'},
 {'address': '3606 13th St NW APT 2, Washington, DC 20010',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '3360 18th St NW, Washington, DC 20010',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '850 sqft'},
 {'address': '3654 New Hampshire Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,399+ 1 bd',
  'sqft': None},
 {'address': '1445 Park Rd NW #208, Washington, DC 20010',
  'price_monthly': '$1,397/mo',
  'also_price': '1 bd',
  'sqft': '525 sqft'},
 {'address': '3413 Brown St NW #1, Washington, DC 20010',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '1,058 sqft'},
 {'address': '3422 Georgia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,625+ 1 bd',
  'sqft': None},
 {'address': '3433 Mount Pleasant St NW APT 103, Washington, DC 20010',
  'price_monthly': '$1,162/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '1341 Monroe St NW, Washington, DC 20010',
  'price_monthly': '$1,395/mo',
  'also_price': '1 bd',
  'sqft': '3,027 sqft'},
 {'address': '3534 10th St NW APT 150, Washington, DC 20010',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '424 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20010',
  'price_monthly': '$1,999/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'}]

In [223]:
zip_code ="20010"

apts_20010_df = pd.DataFrame(apartments_20010)
apts_20010_df['also_price'] = apts_20010_df['also_price'].str[:-4]
apts_20010_df["Zip Code"] = zip_code
apts_20010_df

,address,price_monthly,also_price,sqft,Zip Code
0,"3427 13th St NW APT 1, Washington, DC 20010","$1,590/mo",,760 sqft,20010
1,"Allegro | 3460 14th St NW, Washington, DC",None,"$1,611+",None,20010
2,"Kenyon House Apartments | 1349 Kenyon St NW, W...",None,"$1,725+",None,20010
3,"1515 Ogden St NW APT 622, Washington, DC 20010","$1,495/mo",,650 sqft,20010
4,"1615 Kenyon St NW APT 52, Washington, DC 20010","$1,600/mo",,620 sqft,20010
...,...,...,...,...,...
66,"3422 Georgia Ave NW, Washington, DC",None,"$1,625+",None,20010
67,"3433 Mount Pleasant St NW APT 103, Washington,...","$1,162/mo",,-- sqft,20010
68,"1341 Monroe St NW, Washington, DC 20010","$1,395/mo",,"3,027 sqft",20010
69,"3534 10th St NW APT 150, Washington, DC 20010","$1,450/mo",,424 sqft,20010
70,"(undisclosed Address), Washington, DC 20010","$1,999/mo",,"1,000 sqft",20010

In [224]:
#20011

apartments_20011 = []

In [230]:
url = 'https://www.zillow.com/washington-dc-20011/apartments/1-bedrooms/2_p'
browser.visit(url)

In [231]:
html = browser.html
soup = bs(html,'html.parser')

In [232]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20011.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
5403-5407 9th St NW #103, Washington, DC 20011
<div class="list-card-price">$1,675/mo</div>
1 bd
600 sqft
-------------
812 Decatur St NW, Washington, DC 20011
<div class="list-card-price">$1,495/mo</div>
1 bd
650 sqft
-------------
812 1/2 Decatur St NW, Washington, DC 20011
<div class="list-card-price">$1,495/mo</div>
1 bd
650 sqft
-------------
1372 Randolph St NW APT 204, Washington, DC 20011
<div class="list-card-price">$1,695/mo</div>
1 bd
510 sqft
-------------
5224 4th St NW #102, Washington, DC 20011
<div class="list-card-price">$1,650/mo</div>
1 bd
560 sqft
-------------
215 Rock Creek Church Rd NW, Washington, DC 20011
<div class="list-card-price">$1,350/mo</div>
1 bd
680 sqft
-------------
5611 5th St NW, Washington, DC
None
$1,500+ 1 bd
None
-------------
31 Kennedy St NW APT 103, Washington, DC 20011
<div class="list-card-price">$1,400/mo</div>
1 bd
739 sqft
-------------
4326 Georgia Ave NW #302, Washington, DC 20011
<div class="list-card-price">$1,747/mo</div>
1 bd
551 sqft
-------------
723 Longfellow St NW APT 2, Washington, DC 20011
<div class="list-card-price">$1,450/mo</div>
1 bd
504 sqft
-------------
3900 14th St NW APT 611, Washington, DC 20011
<div class="list-card-price">$1,800/mo</div>
1 bd
637 sqft
-------------
5826 Colorado Ave NW #4, Washington, DC 20011
<div class="list-card-price">$1,600+/mo</div>
1 bd
700 sqft
-------------
1380 Fort Stevens Dr NW APT 204, Washington, DC 20011
<div class="list-card-price">$1,550/mo</div>
1 bd
925 sqft
-------------
738 N Longfellow St NW #312, Washington, DC 20011
<div class="list-card-price">$1,400/mo</div>
1 bd
437 sqft
-------------
(undisclosed Address), Washington, DC 20011
<div class="list-card-price">$1,600/mo</div>
1 bd
2,155 sqft
-------------
5419 Kansas Ave NW, Washington, DC 20011
<div class="list-card-price">$1,800/mo</div>
1 bd
1,476 sqft
-------------
1301 Longfellow St NW APT 207, Washington, DC 20011
<div class="list-card-price">$1,595/mo</div>
1 bd
578 sqft
-------------
965 Randolph St NW UNIT B, Washington, DC 20011
<div class="list-card-price">$1,675/mo</div>
1 bd
3,242 sqft
-------------
5408 1st Pl NW, Washington, DC
None
$1,750+ 1 bd
None
-------------
4010 Kansas Ave NW APT 4, Washington, DC 20011
<div class="list-card-price">$1,950/mo</div>
1 bd
677 sqft
-------------
5011 7th St NW #A, Washington, DC 20011
<div class="list-card-price">$1,500/mo</div>
1 bd
800 sqft
-------------
618 Allison St NW #B, Washington, DC 20011
<div class="list-card-price">$1,300/mo</div>
1 bd
740 sqft
-------------
6024 8th St NW APT A4, Washington, DC 20011
<div class="list-card-price">$1,550/mo</div>
1 bd
600 sqft
-------------
5400 7th St NW #ZBBBKGYKT, Washington, DC 20011
<div class="list-card-price">$1,140+/mo</div>
1 bd
590 sqft
-------------
Simply Amazing Location | 5912 14th St NW, Washington, DC
None
$1,375+ 1 bd
None
-------------
830 Kennedy St NW APT 36, Washington, DC 20011
<div class="list-card-price">$1,355/mo</div>
1 bd
-- sqft

In [233]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20011): 
    if word in stopwords:
        words.remove(word)

In [234]:
apartments_20011

[{'address': 'Fort Totten Square | 5661 3rd St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': 'Park Place at Petworth Metro | 850 Quincy St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,506+ 1 bd',
  'sqft': None},
 {'address': '5403 9th St NW, Washington, DC 20011',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Twin Oaks | 3800 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': '811 Quincy St NW #1422220, Washington, DC 20011',
  'price_monthly': '$1,700+/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '5178-86 Eastern Ave NE #1BR1, Washington, DC 20011',
  'price_monthly': '$1,542+/mo',
  'also_price': '1 bd',
  'sqft': '585 sqft'},
 {'address': 'Hawaiian Gardens | 4520 Fort Totten Dr NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': 'Rolling Terrace | 1360 Peabody St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': 'Aventine Fort Totten | 5210 3rd St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,369+ 1 bd',
  'sqft': None},
 {'address': 'Griffin Apartments | 3801 Georgia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '430 Missouri Ave NW #TRAUPDZK6, Washington, DC 20011',
  'price_monthly': '$1,400+/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': 'The Modern at Art Place | 400 Galloway St NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,342+ 1 bd',
  'sqft': None},
 {'address': 'The Swift at Petworth Metro | 3828 Georgia Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,615+ 1 bd',
  'sqft': None},
 {'address': 'The Rittenhouse | 6101 16th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,616+ 1 bd',
  'sqft': None},
 {'address': '1320 Nicholson St NW #Y59J4F7EJ, Washington, DC 20011',
  'price_monthly': '$1,450+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '310 Hamilton St NW #Z2GE6HZTB, Washington, DC 20011',
  'price_monthly': '$1,430+/mo',
  'also_price': '1 bd',
  'sqft': '730 sqft'},
 {'address': 'Petworth Station | 940 Randolph St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,417+ 1 bd',
  'sqft': None},
 {'address': '5740 13th St NW #1, Washington, DC 20011',
  'price_monthly': '$1,395/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '507 Kennedy St NW #3, Washington, DC 20011',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '720 sqft'},
 {'address': '519 Kennedy St NW FLOOR 2, Washington, DC 20011',
  'price_monthly': '$1,290/mo',
  'also_price': '1 bd',
  'sqft': '588 sqft'},
 {'address': 'Paramount | 829 Quincy St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,698+ 1 bd',
  'sqft': None},
 {'address': '1413 Shepherd St NW, Washington, DC 20011',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '318 Farragut St NW #BASEMENT, Washington, DC 20011',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '541 Quincy St NW #B, Washington, DC 20011',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '1235 Randolph St NW APT 304, Washington, DC 20011',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '525 sqft'},
 {'address': '4419 2nd St NE APT 1, Washington, DC 20011',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '5438 4th St NW APT 4, Washington, DC 20011',
  'price_monthly': '$1,305/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '434 Shepherd St NW #1, Washington, DC 20011',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '4840 New Hampshire Ave NW APT 4, Washington, DC 20011',
  'price_monthly': '$1,376/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '5515 2nd St NW #2, Washington, DC 20011',
  'price_monthly': '$1,875/mo',
  'also_price': '1 bd',
  'sqft': '827 sqft'},
 {'address': '1401 Sheridan | 1401 Sheridan St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,450+ 1 bd',
  'sqft': None},
 {'address': '1211 Farragut St NW #B, Washington, DC 20011',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '1215 Farragut St NW #2, Washington, DC 20011',
  'price_monthly': '$1,295/mo',
  'also_price': '1 bd',
  'sqft': '950 sqft'},
 {'address': '4408 15th St NW, Washington, DC 20011',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '938 sqft'},
 {'address': '4418 5th St NW #BASEMENT, Washington, DC 20011',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '4120 14th St NW APT 39, Washington, DC 20011',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '675 sqft'},
 {'address': '33 Kennedy St NW APT 202, Washington, DC 20011',
  'price_monthly': '$1,575/mo',
  'also_price': '1 bd',
  'sqft': '670 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20011',
  'price_monthly': '$1,499/mo',
  'also_price': '1 bd',
  'sqft': '677 sqft'},
 {'address': '3901 Georgia Ave NW STE 3, Washington, DC 20011',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': 'Northwood Gardens | 4900-20 Fort Totten Dr NE, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,385+ 1 bd',
  'sqft': None},
 {'address': '5403-5407 9th St NW #103, Washington, DC 20011',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '812 Decatur St NW, Washington, DC 20011',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '812 1/2 Decatur St NW, Washington, DC 20011',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '1372 Randolph St NW APT 204, Washington, DC 20011',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '510 sqft'},
 {'address': '5224 4th St NW #102, Washington, DC 20011',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '560 sqft'},
 {'address': '215 Rock Creek Church Rd NW, Washington, DC 20011',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '680 sqft'},
 {'address': '5611 5th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '31 Kennedy St NW APT 103, Washington, DC 20011',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '739 sqft'},
 {'address': '4326 Georgia Ave NW #302, Washington, DC 20011',
  'price_monthly': '$1,747/mo',
  'also_price': '1 bd',
  'sqft': '551 sqft'},
 {'address': '723 Longfellow St NW APT 2, Washington, DC 20011',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '504 sqft'},
 {'address': '3900 14th St NW APT 611, Washington, DC 20011',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '637 sqft'},
 {'address': '5826 Colorado Ave NW #4, Washington, DC 20011',
  'price_monthly': '$1,600+/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1380 Fort Stevens Dr NW APT 204, Washington, DC 20011',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '925 sqft'},
 {'address': '738 N Longfellow St NW #312, Washington, DC 20011',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '437 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20011',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '2,155 sqft'},
 {'address': '5419 Kansas Ave NW, Washington, DC 20011',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '1,476 sqft'},
 {'address': '1301 Longfellow St NW APT 207, Washington, DC 20011',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '578 sqft'},
 {'address': '965 Randolph St NW UNIT B, Washington, DC 20011',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '3,242 sqft'},
 {'address': '5408 1st Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,750+ 1 bd',
  'sqft': None},
 {'address': '4010 Kansas Ave NW APT 4, Washington, DC 20011',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '677 sqft'},
 {'address': '5011 7th St NW #A, Washington, DC 20011',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '618 Allison St NW #B, Washington, DC 20011',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '740 sqft'},
 {'address': '6024 8th St NW APT A4, Washington, DC 20011',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '5400 7th St NW #ZBBBKGYKT, Washington, DC 20011',
  'price_monthly': '$1,140+/mo',
  'also_price': '1 bd',
  'sqft': '590 sqft'},
 {'address': 'Simply Amazing Location | 5912 14th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,375+ 1 bd',
  'sqft': None},
 {'address': '830 Kennedy St NW APT 36, Washington, DC 20011',
  'price_monthly': '$1,355/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'}]

In [235]:
zip_code ="20011"

apts_20011_df = pd.DataFrame(apartments_20011)
apts_20011_df['also_price'] = apts_20011_df['also_price'].str[:-4]
apts_20011_df["Zip Code"] = zip_code
apts_20011_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Fort Totten Square | 5661 3rd St NE, Washingto...",None,"$1,400+",None,20011
1,Park Place at Petworth Metro | 850 Quincy St N...,None,"$1,506+",None,20011
2,"5403 9th St NW, Washington, DC 20011","$1,750/mo",,600 sqft,20011
3,"Twin Oaks | 3800 14th St NW, Washington, DC",None,"$1,595+",None,20011
4,"811 Quincy St NW #1422220, Washington, DC 20011","$1,700+/mo",,700 sqft,20011
...,...,...,...,...,...
61,"618 Allison St NW #B, Washington, DC 20011","$1,300/mo",,740 sqft,20011
62,"6024 8th St NW APT A4, Washington, DC 20011","$1,550/mo",,600 sqft,20011
63,"5400 7th St NW #ZBBBKGYKT, Washington, DC 20011","$1,140+/mo",,590 sqft,20011
64,"Simply Amazing Location | 5912 14th St NW, Was...",None,"$1,375+",None,20011
65,"830 Kennedy St NW APT 36, Washington, DC 20011","$1,355/mo",,-- sqft,20011

In [236]:
#20008

apartments_20008 = []

In [244]:
url = 'https://www.zillow.com/washington-dc-20008/apartments/1-bedrooms/2_p'
browser.visit(url)

In [245]:
html = browser.html
soup = bs(html,'html.parser')

In [246]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20008.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
2800 Woodley Rd | 2800 Woodley Rd NW, Washington, DC
None
$1,615+ 1 bd
None
-------------
2111 S St NW APT 201, Washington, DC 20008
<div class="list-card-price">$2,250/mo</div>
1 bd
802 sqft
-------------
4600 Connecticut Ave NW, Washington, DC
None
$1,349+ 1 bd
None
-------------
2829 28th St NW, Washington, DC 20008
<div class="list-card-price">$1,675/mo</div>
1 bd
-- sqft
-------------
2818 Connecticut Ave NW APT 14, Washington, DC 20008
<div class="list-card-price">$2,350/mo</div>
1 bd
614 sqft
-------------
2939 Van Ness St NW, Washington, DC
None
$1,550+ 1 bd
None
-------------
925 Garfield St N #211, Washington, DC 20008
<div class="list-card-price">$2,160/mo</div>
1 bd
672 sqft
-------------
Cathedral Mansions | 3000 Connecticut Ave NW, Washington, DC
None
$1,838+ 1 bd
None
-------------
2608 Cathedral Ave NW, Washington, DC
None
$1,795+ 1 bd
None
-------------
2100 Connecticut | 2100 Connecticut Ave NW, Washington, DC
None
$1,710+ 1 bd
None
-------------
2852 Connecticut Ave NW, Washington, DC
None
$1,900+ 1 bd
None
-------------
The Frontenac | 4550 Connecticut Ave NW, Washington, DC
None
$1,780+ 1 bd
None
-------------
3883 Connecticut Ave NW APT 102, Washington, DC 20008
<div class="list-card-price">$1,850/mo</div>
1 bd
730 sqft
-------------
The Chesapeake | 4607 Connecticut Ave NW, Washington, DC
None
$1,560+ 1 bd
None
-------------
2801 Cortland Pl NW, Washington, DC
None
$1,895+ 1 bd
None
-------------
The Klingle | 2755 Macomb St NW, Washington, DC
None
$1,740+ 1 bd
None
-------------
4707 Connecticut Ave NW APT 107, Washington, DC 20008
<div class="list-card-price">$2,399/mo</div>
1 bd
929 sqft
-------------
2755 Ordway St NW, Washington, DC
None
$1,600+ 1 bd
None
-------------
The Saratoga Apartments | 4601 Connecticut Ave NW, Washington, DC
None
$1,775+ 1 bd
None
-------------
2760 Devonshire Pl NW APT 34, Washington, DC 20008
<div class="list-card-price">$1,580/mo</div>
1 bd
840 sqft
-------------
4530 Connecticut Ave NW #510, Washington, DC 20008
<div class="list-card-price">$1,698/mo</div>
1 bd
734 sqft
-------------
2710 Macomb St NW, Washington, DC
None
$1,550+ 1 bd
None
-------------
3310 27th St NW APT 6, Washington, DC 20008
<div class="list-card-price">$2,100/mo</div>
1 bd
644 sqft
-------------
(undisclosed Address), Washington, DC 20008
<div class="list-card-price">$1,690/mo</div>
1 bd
804 sqft
-------------
2726 Connecticut Ave NW APT 401, Washington, DC 20008
<div class="list-card-price">$1,750/mo</div>
1 bd
-- sqft
-------------
2647 Connecticut Ave NW, Washington, DC
None
$2,450+ 1 bd
None
-------------
2820 Devonshire Pl NW #1, Washington, DC 20008
<div class="list-card-price">$1,409/mo</div>
1 bd
-- sqft
-------------
2715 Cortland Pl NW APT 22, Washington, DC 20008
<div class="list-card-price">$1,590/mo</div>
1 bd
500 sqft
-------------
2802 Devonshire Pl NW APT 107, Washington, DC 20008
<div class="list-card-price">$1,700/mo</div>
1 bd
700 sqft
-------------
2501 Calvert St NW APT 311, Washington, DC 20008
<div class="list-card-price">$1,950/mo</div>
1 bd
566 sqft
-------------
2634 Woodley Pl NW APT 2, Washington, DC 20008
<div class="list-card-price">$1,950/mo</div>
1 bd
800 sqft
-------------
2113 Bancroft Pl NW UNIT B, Washington, DC 20008
<div class="list-card-price">$2,300/mo</div>
1 bd
1,000 sqft
-------------
3025 Porter St NW APT 12, Washington, DC 20008
<div class="list-card-price">$1,875/mo</div>
1 bd
600 sqft
-------------
2138 California St NW APT 407, Washington, DC 20008
<div class="list-card-price">$1,900/mo</div>
1 bd
750 sqft
-------------
2126 Connecticut Ave NW #57, Washington, DC 20008
<div class="list-card-price">$2,450/mo</div>
1 bd
874 sqft
-------------
2827 28th St NW APT 31, Washington, DC 20008
<div class="list-card-price">$1,675/mo</div>
1 bd
-- sqft
-------------
2801 Connecticut Ave NW APT 5, Washington, DC 20008
<div class="list-card-price">$2,800/mo</div>
1 bd
828 sqft
-------------
3024 Porter St NW APT 101, Washington, DC 20008
<div class="list-card-price">$1,750/mo</div>
1 bd
700 sqft
-------------
4601 Connecticut Ave NW APT 112, Washington, DC 20008
<div class="list-card-price">$1,840/mo</div>
1 bd
632 sqft

In [247]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20008): 
    if word in stopwords:
        words.remove(word)

In [248]:
apartments_20008

[{'address': 'Quebec House | 2800 Quebec St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,775+ 1 bd',
  'sqft': None},
 {'address': 'Ordway | 2745-49 Ordway St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '2724-40 Porter St NW #4, Washington, DC 20008',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '900 sqft'},
 {'address': 'South Cathedral Mansions | 2900 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': 'Brandywine | 4545 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,699+ 1 bd',
  'sqft': None},
 {'address': '2501 Porter | 2501 Porter St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'Ora | 2144 California St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,074+ 1 bd',
  'sqft': None},
 {'address': 'Cleveland House | 2727 29th St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': 'Connecticut Park Apartments | 2828 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,579+ 1 bd',
  'sqft': None},
 {'address': 'Kennedy-Warren | 3133 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,355+ 1 bd',
  'sqft': None},
 {'address': 'Park Connecticut | 4411 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,668+ 1 bd',
  'sqft': None},
 {'address': 'AVA Van Ness | 2950 Van Ness St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,341+ 1 bd',
  'sqft': None},
 {'address': 'Arcadia | 3614 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,599+ 1 bd',
  'sqft': None},
 {'address': '3003 Van Ness | 3003 Van Ness St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,306+ 1 bd',
  'sqft': None},
 {'address': 'Connecticut Heights | 4850 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,340+ 1 bd',
  'sqft': None},
 {'address': 'Avalon The Albemarle | 4501 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,466+ 1 bd',
  'sqft': None},
 {'address': 'Rodman | 3032 Rodman St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,549+ 1 bd',
  'sqft': None},
 {'address': '3001 Porter St NW APT 204, Washington, DC 20008',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '2756 Macomb St NW #3167772, Washington, DC 20008',
  'price_monthly': '$1,599+/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': 'Sulgrave Manor | 5130 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': 'Sedgwick Gardens | 3726 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': 'The Parkwest | 2929 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,789+ 1 bd',
  'sqft': None},
 {'address': '3221 Connecticut Avenue | 3221 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '5100 Connecticut Avenue Apartments | 5100 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '3217 Connecticut Ave NW | 3217 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,399+ 1 bd',
  'sqft': None},
 {'address': '3100 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,480+ 1 bd',
  'sqft': None},
 {'address': 'Calvert House Apartments | 2401 Calvert St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,722+ 1 bd',
  'sqft': None},
 {'address': 'Connecticut Plaza Apartments | 2901 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '4007 Connecticut Ave NW, Washington, DC 20008',
  'price_monthly': '$2,050/mo',
  'also_price': '1 bd',
  'sqft': '775 sqft'},
 {'address': 'Parkway Apartments | 3220 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,876+ 1 bd',
  'sqft': None},
 {'address': 'Park Van Ness | 4455 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,880+ 1 bd',
  'sqft': None},
 {'address': 'The Rodman | 3002 Rodman St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,824+ 1 bd',
  'sqft': None},
 {'address': '2701 Connecticut Ave | 2701 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '2725 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,100+ 1 bd',
  'sqft': None},
 {'address': '2736 Ordway St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '3701 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,875+ 1 bd',
  'sqft': None},
 {'address': '2911 Newark St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,412+ 1 bd',
  'sqft': None},
 {'address': '2902 Porter St NW, Washington, DC 20008',
  'price_monthly': '$1,796/mo',
  'also_price': '1 bd',
  'sqft': '714 sqft'},
 {'address': 'The Woodley | 2700 Woodley Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,960+ 1 bd',
  'sqft': None},
 {'address': 'Tilden Hall Apartments | 3945 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,375+ 1 bd',
  'sqft': None},
 {'address': '2800 Woodley Rd | 2800 Woodley Rd NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,615+ 1 bd',
  'sqft': None},
 {'address': '2111 S St NW APT 201, Washington, DC 20008',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '802 sqft'},
 {'address': '4600 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,349+ 1 bd',
  'sqft': None},
 {'address': '2829 28th St NW, Washington, DC 20008',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2818 Connecticut Ave NW APT 14, Washington, DC 20008',
  'price_monthly': '$2,350/mo',
  'also_price': '1 bd',
  'sqft': '614 sqft'},
 {'address': '2939 Van Ness St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,550+ 1 bd',
  'sqft': None},
 {'address': '925 Garfield St N #211, Washington, DC 20008',
  'price_monthly': '$2,160/mo',
  'also_price': '1 bd',
  'sqft': '672 sqft'},
 {'address': 'Cathedral Mansions | 3000 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,838+ 1 bd',
  'sqft': None},
 {'address': '2608 Cathedral Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': '2100 Connecticut | 2100 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,710+ 1 bd',
  'sqft': None},
 {'address': '2852 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': 'The Frontenac | 4550 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,780+ 1 bd',
  'sqft': None},
 {'address': '3883 Connecticut Ave NW APT 102, Washington, DC 20008',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '730 sqft'},
 {'address': 'The Chesapeake | 4607 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,560+ 1 bd',
  'sqft': None},
 {'address': '2801 Cortland Pl NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'The Klingle | 2755 Macomb St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,740+ 1 bd',
  'sqft': None},
 {'address': '4707 Connecticut Ave NW APT 107, Washington, DC 20008',
  'price_monthly': '$2,399/mo',
  'also_price': '1 bd',
  'sqft': '929 sqft'},
 {'address': '2755 Ordway St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'The Saratoga Apartments | 4601 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,775+ 1 bd',
  'sqft': None},
 {'address': '2760 Devonshire Pl NW APT 34, Washington, DC 20008',
  'price_monthly': '$1,580/mo',
  'also_price': '1 bd',
  'sqft': '840 sqft'},
 {'address': '4530 Connecticut Ave NW #510, Washington, DC 20008',
  'price_monthly': '$1,698/mo',
  'also_price': '1 bd',
  'sqft': '734 sqft'},
 {'address': '2710 Macomb St NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$1,550+ 1 bd',
  'sqft': None},
 {'address': '3310 27th St NW APT 6, Washington, DC 20008',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '644 sqft'},
 {'address': '(undisclosed Address), Washington, DC 20008',
  'price_monthly': '$1,690/mo',
  'also_price': '1 bd',
  'sqft': '804 sqft'},
 {'address': '2726 Connecticut Ave NW APT 401, Washington, DC 20008',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2647 Connecticut Ave NW, Washington, DC',
  'price_monthly': None,
  'also_price': '$2,450+ 1 bd',
  'sqft': None},
 {'address': '2820 Devonshire Pl NW #1, Washington, DC 20008',
  'price_monthly': '$1,409/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2715 Cortland Pl NW APT 22, Washington, DC 20008',
  'price_monthly': '$1,590/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '2802 Devonshire Pl NW APT 107, Washington, DC 20008',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '2501 Calvert St NW APT 311, Washington, DC 20008',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '566 sqft'},
 {'address': '2634 Woodley Pl NW APT 2, Washington, DC 20008',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '2113 Bancroft Pl NW UNIT B, Washington, DC 20008',
  'price_monthly': '$2,300/mo',
  'also_price': '1 bd',
  'sqft': '1,000 sqft'},
 {'address': '3025 Porter St NW APT 12, Washington, DC 20008',
  'price_monthly': '$1,875/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '2138 California St NW APT 407, Washington, DC 20008',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '2126 Connecticut Ave NW #57, Washington, DC 20008',
  'price_monthly': '$2,450/mo',
  'also_price': '1 bd',
  'sqft': '874 sqft'},
 {'address': '2827 28th St NW APT 31, Washington, DC 20008',
  'price_monthly': '$1,675/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '2801 Connecticut Ave NW APT 5, Washington, DC 20008',
  'price_monthly': '$2,800/mo',
  'also_price': '1 bd',
  'sqft': '828 sqft'},
 {'address': '3024 Porter St NW APT 101, Washington, DC 20008',
  'price_monthly': '$1,750/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '4601 Connecticut Ave NW APT 112, Washington, DC 20008',
  'price_monthly': '$1,840/mo',
  'also_price': '1 bd',
  'sqft': '632 sqft'}]

In [249]:
zip_code ="20008"

apts_20008_df = pd.DataFrame(apartments_20008)
apts_20008_df['also_price'] = apts_20008_df['also_price'].str[:-4]
apts_20008_df["Zip Code"] = zip_code
apts_20008_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Quebec House | 2800 Quebec St NW, Washington, DC",None,"$1,775+",None,20008
1,"Ordway | 2745-49 Ordway St NW, Washington, DC",None,"$1,700+",None,20008
2,"2724-40 Porter St NW #4, Washington, DC 20008","$1,900/mo",,900 sqft,20008
3,South Cathedral Mansions | 2900 Connecticut Av...,None,"$1,950+",None,20008
4,"Brandywine | 4545 Connecticut Ave NW, Washingt...",None,"$1,699+",None,20008
...,...,...,...,...,...
74,"2126 Connecticut Ave NW #57, Washington, DC 20008","$2,450/mo",,874 sqft,20008
75,"2827 28th St NW APT 31, Washington, DC 20008","$1,675/mo",,-- sqft,20008
76,"2801 Connecticut Ave NW APT 5, Washington, DC ...","$2,800/mo",,828 sqft,20008
77,"3024 Porter St NW APT 101, Washington, DC 20008","$1,750/mo",,700 sqft,20008
78,"4601 Connecticut Ave NW APT 112, Washington, D...","$1,840/mo",,632 sqft,20008

In [250]:
#22314

apartments_22314 = []

In [256]:
url = 'https://www.zillow.com/alexandria-va-22314/apartments/1-bedrooms/2_p'
browser.visit(url)

In [257]:
html = browser.html
soup = bs(html,'html.parser')

In [258]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22314.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
400 Madison St, Alexandria, VA
None
$1,995+ 1 bd
None
-------------
602 Bashford Ln UNIT 2212, Alexandria, VA 22314
<div class="list-card-price">$1,500/mo</div>
1 bd
549 sqft
-------------
1100 Quaker Hill Dr APT 219, Alexandria, VA 22314
<div class="list-card-price">$1,700/mo</div>
1 bd
996 sqft
-------------
1636 W Abingdon Dr APT 102, Alexandria, VA 22314
<div class="list-card-price">$1,349/mo</div>
1 bd
683 sqft
-------------
501 Slaters Ln, Alexandria, VA
None
$1,800+ 1 bd
None
-------------
219 S Saint Asaph St APT 3, Alexandria, VA 22314
<div class="list-card-price">$2,250/mo</div>
1 bd
750 sqft
-------------
1606 W Abingdon Dr, Alexandria, VA
None
$1,495+ 1 bd
None
-------------
102 S Henry St #1, Alexandria, VA 22314
<div class="list-card-price">$1,495/mo</div>
1 bd
-- sqft
-------------
718 S Washington St APT 201, Alexandria, VA 22314
<div class="list-card-price">$1,600/mo</div>
1 bd
555 sqft
-------------
719 S Saint Asaph St, Alexandria, VA
None
$1,345+ 1 bd
None
-------------
919 Green St #3, Alexandria, VA 22314
<div class="list-card-price">$1,550+/mo</div>
1 bd
500 sqft
-------------
133 N Payne St, Alexandria, VA 22314
<div class="list-card-price">$1,550/mo</div>
1 bd
504 sqft
-------------
125 N Lee St APT 307, Alexandria, VA 22314
<div class="list-card-price">$2,350/mo</div>
1 bd
820 sqft
-------------
906 S Washington St APT 308, Alexandria, VA 22314
<div class="list-card-price">$1,375/mo</div>
1 bd
631 sqft
-------------
1806 W Abingdon Dr APT 101, Alexandria, VA 22314
<div class="list-card-price">$1,545/mo</div>
1 bd
612 sqft
-------------
1200 Braddock Pl, Alexandria, VA
None
$1,500+ 1 bd
None
-------------
200 S Fairfax St APT 8, Alexandria, VA 22314
<div class="list-card-price">$2,650/mo</div>
1 bd
605 sqft
-------------
706 North Washington Street | 706 N Washington St, Alexandria, VA
None
$2,295+ 1 bd
None
-------------
2121 Jamieson Ave UNIT 910, Alexandria, VA 22314
<div class="list-card-price">$1,775/mo</div>
1 bd
750 sqft
-------------
115 N Lee St #BH403, Alexandria, VA 22314
<div class="list-card-price">$2,000/mo</div>
1 bd
686 sqft
-------------
815 King St, Alexandria, VA
None
$1,860+ 1 bd
None

In [259]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22314): 
    if word in stopwords:
        words.remove(word)

In [260]:
apartments_22314

[{'address': 'The Heritage at Old Town | 431 S Columbus St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,295+ 1 bd',
  'sqft': None},
 {'address': 'The Asher | 620 N Fayette St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,651+ 1 bd',
  'sqft': None},
 {'address': 'Lincoln Old Town | 401 Holland Ln, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,505+ 1 bd',
  'sqft': None},
 {'address': '1111 Belle Pre | 1111 Belle Pre Way, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,475+ 1 bd',
  'sqft': None},
 {'address': 'Gables Old Town North | 525 Montgomery St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$2,073+ 1 bd',
  'sqft': None},
 {'address': 'The Dalton | 1225 First St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,475+ 1 bd',
  'sqft': None},
 {'address': '1203 N Pitt St APT 1B, Alexandria, VA 22314',
  'price_monthly': '$1,895/mo',
  'also_price': '1 bd',
  'sqft': '624 sqft'},
 {'address': 'Carlyle Mill | 2201 Mill Rd, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'The Bradley Braddock Road Station Apartments | 1260 Braddock Pl, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,645+ 1 bd',
  'sqft': None},
 {'address': 'The Foundry | 2470 Mandeville Ln, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,785+ 1 bd',
  'sqft': None},
 {'address': '820 S Columbus St UNIT 119, Alexandria, VA 22314',
  'price_monthly': '$1,952/mo',
  'also_price': '1 bd',
  'sqft': '656 sqft'},
 {'address': 'Post Carlyle Square | 501 Holland Ln, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,429+ 1 bd',
  'sqft': None},
 {'address': 'Bridgeyard Old Town | 1204 S Washington St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,430+ 1 bd',
  'sqft': None},
 {'address': 'Mason Gardens | 2327 Duke St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,460+ 1 bd',
  'sqft': None},
 {'address': '1111 Oronoco St UNIT 132, Alexandria, VA 22314',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '840 sqft'},
 {'address': 'Cameron Court | 2700 Williamsburg St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,571+ 1 bd',
  'sqft': None},
 {'address': 'Monticello-Lee | 620 Jefferson St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,549+ 1 bd',
  'sqft': None},
 {'address': 'The Kingsley | 500 Madison St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,718+ 1 bd',
  'sqft': None},
 {'address': '1014 King St APT 1, Alexandria, VA 22314',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '585 sqft'},
 {'address': '502 Bashford Ln UNIT 3221, Alexandria, VA 22314',
  'price_monthly': '$1,795/mo',
  'also_price': '1 bd',
  'sqft': '543 sqft'},
 {'address': '800 Carlyle | 800 John Carlyle St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,664+ 1 bd',
  'sqft': None},
 {'address': 'The Thornton | 750 Thornton Way, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,412+ 1 bd',
  'sqft': None},
 {'address': '(undisclosed Address), Alexandria, VA 22314',
  'price_monthly': '$2,150/mo',
  'also_price': '1 bd',
  'sqft': '860 sqft'},
 {'address': '520 John Carlyle St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '715 S Washington St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '409 Cameron St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,250+ 1 bd',
  'sqft': None},
 {'address': '309 Holland Ln UNIT 107, Alexandria, VA 22314',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '651 sqft'},
 {'address': '801 N Pitt St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,449+ 1 bd',
  'sqft': None},
 {'address': '800 S Saint Asaph St APT 309, Alexandria, VA 22314',
  'price_monthly': '$2,100/mo',
  'also_price': '1 bd',
  'sqft': '797 sqft'},
 {'address': '412 N Fayette St UNIT 1, Alexandria, VA 22314',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '1600 Prince St APT 306, Alexandria, VA 22314',
  'price_monthly': '$1,695/mo',
  'also_price': '1 bd',
  'sqft': '739 sqft'},
 {'address': 'Mason Hall | 1420 W Abingdon Dr, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,359+ 1 bd',
  'sqft': None},
 {'address': '1109 N Pitt St APT 3A, Alexandria, VA 22314',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '612 sqft'},
 {'address': '922 Queen St APT A, Alexandria, VA 22314',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '620 sqft'},
 {'address': '1704 W Abingdon Dr APT 201, Alexandria, VA 22314',
  'price_monthly': '$2,295/mo',
  'also_price': '1 bd',
  'sqft': '612 sqft'},
 {'address': '217 S Patrick St, Alexandria, VA 22314',
  'price_monthly': '$2,295/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '610 N West St APT 507, Alexandria, VA 22314',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '754 sqft'},
 {'address': '2151 Jamieson Ave, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,975+ 1 bd',
  'sqft': None},
 {'address': '800 S Washington St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,549+ 1 bd',
  'sqft': None},
 {'address': '400 Madison St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': '400 Madison St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,995+ 1 bd',
  'sqft': None},
 {'address': '602 Bashford Ln UNIT 2212, Alexandria, VA 22314',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '549 sqft'},
 {'address': '1100 Quaker Hill Dr APT 219, Alexandria, VA 22314',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '996 sqft'},
 {'address': '1636 W Abingdon Dr APT 102, Alexandria, VA 22314',
  'price_monthly': '$1,349/mo',
  'also_price': '1 bd',
  'sqft': '683 sqft'},
 {'address': '501 Slaters Ln, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '219 S Saint Asaph St APT 3, Alexandria, VA 22314',
  'price_monthly': '$2,250/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1606 W Abingdon Dr, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,495+ 1 bd',
  'sqft': None},
 {'address': '102 S Henry St #1, Alexandria, VA 22314',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': '718 S Washington St APT 201, Alexandria, VA 22314',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '555 sqft'},
 {'address': '719 S Saint Asaph St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,345+ 1 bd',
  'sqft': None},
 {'address': '919 Green St #3, Alexandria, VA 22314',
  'price_monthly': '$1,550+/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'},
 {'address': '133 N Payne St, Alexandria, VA 22314',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '504 sqft'},
 {'address': '125 N Lee St APT 307, Alexandria, VA 22314',
  'price_monthly': '$2,350/mo',
  'also_price': '1 bd',
  'sqft': '820 sqft'},
 {'address': '906 S Washington St APT 308, Alexandria, VA 22314',
  'price_monthly': '$1,375/mo',
  'also_price': '1 bd',
  'sqft': '631 sqft'},
 {'address': '1806 W Abingdon Dr APT 101, Alexandria, VA 22314',
  'price_monthly': '$1,545/mo',
  'also_price': '1 bd',
  'sqft': '612 sqft'},
 {'address': '1200 Braddock Pl, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '200 S Fairfax St APT 8, Alexandria, VA 22314',
  'price_monthly': '$2,650/mo',
  'also_price': '1 bd',
  'sqft': '605 sqft'},
 {'address': '706 North Washington Street | 706 N Washington St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$2,295+ 1 bd',
  'sqft': None},
 {'address': '2121 Jamieson Ave UNIT 910, Alexandria, VA 22314',
  'price_monthly': '$1,775/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '115 N Lee St #BH403, Alexandria, VA 22314',
  'price_monthly': '$2,000/mo',
  'also_price': '1 bd',
  'sqft': '686 sqft'},
 {'address': '815 King St, Alexandria, VA',
  'price_monthly': None,
  'also_price': '$1,860+ 1 bd',
  'sqft': None}]

In [261]:
zip_code ="22314"

apts_22314_df = pd.DataFrame(apartments_22314)
apts_22314_df['also_price'] = apts_22314_df['also_price'].str[:-4]
apts_22314_df["Zip Code"] = zip_code
apts_22314_df

,address,price_monthly,also_price,sqft,Zip Code
0,"The Heritage at Old Town | 431 S Columbus St, ...",None,"$1,295+",None,22314
1,"The Asher | 620 N Fayette St, Alexandria, VA",None,"$1,651+",None,22314
2,"Lincoln Old Town | 401 Holland Ln, Alexandria, VA",None,"$1,505+",None,22314
3,"1111 Belle Pre | 1111 Belle Pre Way, Alexandri...",None,"$1,475+",None,22314
4,"Gables Old Town North | 525 Montgomery St, Ale...",None,"$2,073+",None,22314
...,...,...,...,...,...
56,"200 S Fairfax St APT 8, Alexandria, VA 22314","$2,650/mo",,605 sqft,22314
57,706 North Washington Street | 706 N Washington...,None,"$2,295+",None,22314
58,"2121 Jamieson Ave UNIT 910, Alexandria, VA 22314","$1,775/mo",,750 sqft,22314
59,"115 N Lee St #BH403, Alexandria, VA 22314","$2,000/mo",,686 sqft,22314
60,"815 King St, Alexandria, VA",None,"$1,860+",None,22314

In [262]:
#22204

apartments_22204 = []

In [268]:
url = 'https://www.zillow.com/arlington-va-22204/apartments/1-bedrooms/2_p'
browser.visit(url)

In [269]:
html = browser.html
soup = bs(html,'html.parser')

In [270]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22204.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1401 S Barton St UNIT 218, Arlington, VA 22204
<div class="list-card-price">$1,600/mo</div>
1 bd
738 sqft
-------------
401 S Courthouse Rd #7, Arlington, VA 22204
<div class="list-card-price">$1,350/mo</div>
1 bd
620 sqft
-------------
2010 4th St S APT 2, Arlington, VA 22204
<div class="list-card-price">$1,350/mo</div>
1 bd
751 sqft
-------------
3801 7th St S, Arlington, VA 22204
<div class="list-card-price">$1,550/mo</div>
1 bd
700 sqft
-------------
5353 Columbia Pike APT 403, Arlington, VA 22204
<div class="list-card-price">$1,495/mo</div>
1 bd
726 sqft
-------------
1511 S George Mason Dr APT 3, Arlington, VA 22204
<div class="list-card-price">$1,650/mo</div>
1 bd
687 sqft
-------------
131 S Courthouse Rd APT 6, Arlington, VA 22204
<div class="list-card-price">$1,350/mo</div>
1 bd
751 sqft
-------------
989 S Buchanan St UNIT 411, Arlington, VA 22204
<div class="list-card-price">$1,699/mo</div>
1 bd
727 sqft
-------------
2005 4th Street South, Arlington, VA | 2005 4th St S, Arlington, VA
None
$1,300+ 1 bd
None

In [271]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22204): 
    if word in stopwords:
        words.remove(word)

In [272]:
apartments_22204

[{'address': 'Pike3400 | 3400 Columbia Pike, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,583+ 1 bd',
  'sqft': None},
 {'address': '500-510 S Walter Reed Dr #22, Arlington, VA 22204',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'Columbia Crossing | 1957 Columbia Pike, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,465+ 1 bd',
  'sqft': None},
 {'address': '55 Hundred | 5500 Columbia Pike, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,425+ 1 bd',
  'sqft': None},
 {'address': '500 S. Wayne Street | 500 S Wayne St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': 'Avalon Columbia Pike | 1028 S Walter Reed Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,487+ 1 bd',
  'sqft': None},
 {'address': 'Wildwood Towers | 1075 S Jefferson St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': '4600 S Four Mile Run Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': 'Dominion Plaza | 1200 S Courthouse Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,355+ 1 bd',
  'sqft': None},
 {'address': 'Dominion Towers | 1201 S Courthouse Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,174+ 1 bd',
  'sqft': None},
 {'address': 'Myerton | 108 S Courthouse Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,218+ 1 bd',
  'sqft': None},
 {'address': 'The Whitmore | 4301 Columbia Pike, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,657+ 1 bd',
  'sqft': None},
 {'address': 'Dominion | 333 S Glebe Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,465+ 1 bd',
  'sqft': None},
 {'address': 'Infinity Apartments | 955 S Columbus St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,283+ 1 bd',
  'sqft': None},
 {'address': 'Columbia Park | 942 S Wakefield St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,445+ 1 bd',
  'sqft': None},
 {'address': 'The Wellington | 1850 Columbia Pike, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,279+ 1 bd',
  'sqft': None},
 {'address': 'Fillmore Garden | 805 S Walter Reed Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,159+ 1 bd',
  'sqft': None},
 {'address': 'Wildwood Park | 5550 Columbia Pike, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,495+ 1 bd',
  'sqft': None},
 {'address': '4500 S Four Mile Run Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': 'Centro Arlington | 950 S George Mason Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,454+ 1 bd',
  'sqft': None},
 {'address': '2910 13th Rd S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '840 S Frederick St APT 102, Arlington, VA 22204',
  'price_monthly': '$1,312/mo',
  'also_price': '1 bd',
  'sqft': '695 sqft'},
 {'address': '4151 S Four Mile Run Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,950+ 1 bd',
  'sqft': None},
 {'address': '1830 Columbia Pike, Arlington, VA 22204',
  'price_monthly': '$1,599/mo',
  'also_price': '1 bd',
  'sqft': '770 sqft'},
 {'address': '2019 5th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,370+ 1 bd',
  'sqft': None},
 {'address': '2814 13th St S, Arlington, VA 22204',
  'price_monthly': '$1,200/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '5300 Columbia Pike APT 814, Arlington, VA 22204',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '927 sqft'},
 {'address': '989 S Buchanan St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '4077 S Four Mile Run Dr UNIT 304, Arlington, VA 22204',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '851 sqft'},
 {'address': '302 S Wayne St, Arlington, VA 22204',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '416 S Veitch St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': '4089 S Four Mile Run Dr UNIT 304, Arlington, VA 22204',
  'price_monthly': '$1,950/mo',
  'also_price': '1 bd',
  'sqft': '851 sqft'},
 {'address': '2902 13th Rd S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,200+ 1 bd',
  'sqft': None},
 {'address': '2701 16th St S APT 639, Arlington, VA 22204',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': '706 S Arlington Mill Dr APT 304, Arlington, VA 22204',
  'price_monthly': '$1,525/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '700 S Arlington Mill Dr APT 302, Arlington, VA 22204',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '592 sqft'},
 {'address': '4241 Columbia Pike APT 204, Arlington, VA 22204',
  'price_monthly': '$1,300/mo',
  'also_price': '1 bd',
  'sqft': '551 sqft'},
 {'address': 'Haven Columbia Pike | 805 S Florida St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,370+ 1 bd',
  'sqft': None},
 {'address': '200 S Veitch St APT 2, Arlington, VA 22204',
  'price_monthly': '$1,100/mo',
  'also_price': '1 bd',
  'sqft': '475 sqft'},
 {'address': '2011 6th St S APT 3, Arlington, VA 22204',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '1401 S Barton St UNIT 218, Arlington, VA 22204',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '738 sqft'},
 {'address': '401 S Courthouse Rd #7, Arlington, VA 22204',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '620 sqft'},
 {'address': '2010 4th St S APT 2, Arlington, VA 22204',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '751 sqft'},
 {'address': '3801 7th St S, Arlington, VA 22204',
  'price_monthly': '$1,550/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '5353 Columbia Pike APT 403, Arlington, VA 22204',
  'price_monthly': '$1,495/mo',
  'also_price': '1 bd',
  'sqft': '726 sqft'},
 {'address': '1511 S George Mason Dr APT 3, Arlington, VA 22204',
  'price_monthly': '$1,650/mo',
  'also_price': '1 bd',
  'sqft': '687 sqft'},
 {'address': '131 S Courthouse Rd APT 6, Arlington, VA 22204',
  'price_monthly': '$1,350/mo',
  'also_price': '1 bd',
  'sqft': '751 sqft'},
 {'address': '989 S Buchanan St UNIT 411, Arlington, VA 22204',
  'price_monthly': '$1,699/mo',
  'also_price': '1 bd',
  'sqft': '727 sqft'},
 {'address': '2005 4th Street South, Arlington, VA | 2005 4th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,300+ 1 bd',
  'sqft': None}]

In [273]:
zip_code ="22204"

apts_22204_df = pd.DataFrame(apartments_22204)
apts_22204_df['also_price'] = apts_22204_df['also_price'].str[:-4]
apts_22204_df["Zip Code"] = zip_code
apts_22204_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Pike3400 | 3400 Columbia Pike, Arlington, VA",None,"$1,583+",None,22204
1,"500-510 S Walter Reed Dr #22, Arlington, VA 22204","$1,450/mo",,-- sqft,22204
2,"Columbia Crossing | 1957 Columbia Pike, Arling...",None,"$1,465+",None,22204
3,"55 Hundred | 5500 Columbia Pike, Arlington, VA",None,"$1,425+",None,22204
4,"500 S. Wayne Street | 500 S Wayne St, Arlingto...",None,"$1,400+",None,22204
5,"Avalon Columbia Pike | 1028 S Walter Reed Dr, ...",None,"$1,487+",None,22204
6,"Wildwood Towers | 1075 S Jefferson St, Arlingt...",None,"$1,595+",None,22204
7,"4600 S Four Mile Run Dr, Arlington, VA",None,"$1,500+",None,22204
8,"Dominion Plaza | 1200 S Courthouse Rd, Arlingt...",None,"$1,355+",None,22204
9,"Dominion Towers | 1201 S Courthouse Rd, Arling...",None,"$1,174+",None,22204
10,"Myerton | 108 S Courthouse Rd, Arlington, VA",None,"$1,218+",None,22204
11,"The Whitmore | 4301 Columbia Pike, Arlington, VA",None,"$1,657+",None,22204
12,"Dominion | 333 S Glebe Rd, Arlington, VA",None,"$1,465+",None,22204
13,"Infinity Apartments | 955 S Columbus St, Arlin...",None,"$1,283+",None,22204
14,"Columbia Park | 942 S Wakefield St, Arlington, VA",None,"$1,445+",None,22204
15,"The Wellington | 1850 Columbia Pike, Arlington...",None,"$1,279+",None,22204
16,"Fillmore Garden | 805 S Walter Reed Dr, Arling...",None,"$1,159+",None,22204
17,"Wildwood Park | 5550 Columbia Pike, Arlington, VA",None,"$1,495+",None,22204
18,"4500 S Four Mile Run Dr, Arlington, VA",None,"$1,500+",None,22204
19,"Centro Arlington | 950 S George Mason Dr, Arli...",None,"$1,454+",None,22204
20,"2910 13th Rd S, Arlington, VA",None,"$1,500+",None,22204
21,"840 S Frederick St APT 102, Arlington, VA 22204","$1,312/mo",,695 sqft,22204
22,"4151 S Four Mile Run Dr, Arlington, VA",None,"$1,950+",None,22204
23,"1830 Columbia Pike, Arlington, VA 22204","$1,599/mo",,770 sqft,22204
24,"2019 5th St S, Arlington, VA",None,"$1,370+",None,22204
25,"2814 13th St S, Arlington, VA 22204","$1,200/mo",,700 sqft,22204
26,"5300 Columbia Pike APT 814, Arlington, VA 22204","$1,700/mo",,927 sqft,22204
27,"989 S Buchanan St, Arlington, VA",None,"$1,400+",None,22204
28,"4077 S Four Mile Run Dr UNIT 304, Arlington, V...","$1,900/mo",,851 sqft,22204
29,"302 S Wayne St, Arlington, VA 22204","$1,700/mo",,650 sqft,22204
30,"416 S Veitch St, Arlington, VA",None,"$1,650+",None,22204
31,"4089 S Four Mile Run Dr UNIT 304, Arlington, V...","$1,950/mo",,851 sqft,22204
32,"2902 13th Rd S, Arlington, VA",None,"$1,200+",None,22204
33,"2701 16th St S APT 639, Arlington, VA 22204","$1,800/mo",,800 sqft,22204
34,"706 S Arlington Mill Dr APT 304, Arlington, VA...","$1,525/mo",,600 sqft,22204
35,"700 S Arlington Mill Dr APT 302, Arlington, VA...","$1,400/mo",,592 sqft,22204
36,"4241 Columbia Pike APT 204, Arlington, VA 22204","$1,300/mo",,551 sqft,22204
37,"Haven Columbia Pike | 805 S Florida St, Arling...",None,"$1,370+",None,22204
38,"200 S Veitch St APT 2, Arlington, VA 22204","$1,100/mo",,475 sqft,22204
39,"2011 6th St S APT 3, Arlington, VA 22204","$1,350/mo",,600 sqft,22204
40,"1401 S Barton St UNIT 218, Arlington, VA 22204","$1,600/mo",,738 sqft,22204
41,"401 S Courthouse Rd #7, Arlington, VA 22204","$1,350/mo",,620 sqft,22204
42,"2010 4th St S APT 2, Arlington, VA 22204","$1,350/mo",,751 sqft,22204
43,"3801 7th St S, Arlington, VA 22204","$1,550/mo",,700 sqft,22204
44,"5353 Columbia Pike APT 403, Arlington, VA 22204","$1,495/mo",,726 sqft,22204
45,"1511 S George Mason Dr APT 3, Arlington, VA 22204","$1,650/mo",,687 sqft,22204
46,"131 S Courthouse Rd APT 6, Arlington, VA 22204","$1,350/mo",,751 sqft,22204
47,"989 S Buchanan St UNIT 411, Arlington, VA 22204","$1,699/mo",,727 sqft,22204
48,"2005 4th Street South, Arlington, VA | 2005 4t...",None,"$1,300+",None,22204

In [274]:
#22203

apartments_22203 = []

In [280]:
url = 'https://www.zillow.com/arlington-va-22203/apartments/1-bedrooms/2_p'
browser.visit(url)

In [281]:
html = browser.html
soup = bs(html,'html.parser')

In [282]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22203.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
4310 N Pershing Dr #43101, Arlington, VA 22203
<div class="list-card-price">$1,425/mo</div>
1 bd
699 sqft
-------------
728 N Wakefield St, Arlington, VA 22203
<div class="list-card-price">$1,475/mo</div>
1 bd
550 sqft
-------------
880 N Pollard St APT 226, Arlington, VA 22203
<div class="list-card-price">$1,600/mo</div>
1 bd
650 sqft

In [283]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22203): 
    if word in stopwords:
        words.remove(word)

In [284]:
apartments_22203

[{'address': 'The Waycroft | 750 N Glebe Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,860+ 1 bd',
  'sqft': None},
 {'address': 'Birchwood | 545 N Pollard St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'Virginia Square | 901 N Nelson St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,585+ 1 bd',
  'sqft': None},
 {'address': 'AVA Ballston Square | 850 N Randolph St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,440+ 1 bd',
  'sqft': None},
 {'address': '672 Flats | 672 N Glebe Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'Ballston Place | 901 N Pollard St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': 'Liberty Tower | 818 N Quincy St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,640+ 1 bd',
  'sqft': None},
 {'address': '4322 2nd Rd N #43224, Arlington, VA 22203',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '666 sqft'},
 {'address': '851 N Glebe Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': 'The Amelia | 816 N Oakland St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': 'Randolph Towers | 4001 9th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,895+ 1 bd',
  'sqft': None},
 {'address': 'The View at Liberty Center | 4000 Wilson Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,625+ 1 bd',
  'sqft': None},
 {'address': 'J SOL | 4000 Fairfax Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,905+ 1 bd',
  'sqft': None},
 {'address': '724 N Oakland St #724, Arlington, VA 22203',
  'price_monthly': '$1,975/mo',
  'also_price': '1 bd',
  'sqft': '800 sqft'},
 {'address': 'Quincy Plaza | 3900 Fairfax Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,595+ 1 bd',
  'sqft': None},
 {'address': 'Origin | 700 N Randolph St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,790+ 1 bd',
  'sqft': None},
 {'address': 'Thomas Court | 470 N Thomas St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,925+ 1 bd',
  'sqft': None},
 {'address': 'Richmond Square | 900 N Randolph St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '4301 N Henderson Rd #656783, Arlington, VA 22203',
  'price_monthly': '$1,995+/mo',
  'also_price': '1 bd',
  'sqft': '680 sqft'},
 {'address': '4040 Wilson | 4040 Wilson Blvd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,041+ 1 bd',
  'sqft': None},
 {'address': 'The Maxwell | 4200 N Carlin Springs Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '900 N Stafford St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,450+ 1 bd',
  'sqft': None},
 {'address': '3714 7th St N APT 5, Arlington, VA 22203',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '4350 N Pershing Dr APT 4, Arlington, VA 22203',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '660 sqft'},
 {'address': '4800 9th St N APT 4, Arlington, VA 22203',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '230 N George Mason Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,395+ 1 bd',
  'sqft': None},
 {'address': '3835 9th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,775+ 1 bd',
  'sqft': None},
 {'address': '206 N George Mason Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,300+ 1 bd',
  'sqft': None},
 {'address': '4141 N Henderson Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,695+ 1 bd',
  'sqft': None},
 {'address': '3835 9th St N APT 706E, Arlington, VA 22203',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '834 sqft'},
 {'address': '206 N Trenton St APT 1, Arlington, VA 22203',
  'price_monthly': '$1,395/mo',
  'also_price': '1 bd',
  'sqft': '699 sqft'},
 {'address': '888 N Quincy St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '851 N Glebe Rd, Arlington, VA 22203',
  'price_monthly': '$1,899/mo',
  'also_price': '1 bd',
  'sqft': '752 sqft'},
 {'address': '4314 N Carlin Springs Rd APT 11, Arlington, VA 22203',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '3714 7th St N APT 4, Arlington, VA 22203',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'},
 {'address': '900 N Taylor St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$4,133+ 1 bd',
  'sqft': None},
 {'address': '3830 9th St N, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,795+ 1 bd',
  'sqft': None},
 {'address': '820 N Pollard St APT 507, Arlington, VA 22203',
  'price_monthly': '$1,900/mo',
  'also_price': '1 bd',
  'sqft': '729 sqft'},
 {'address': '4141 Henderson Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '3830 9th St N APT 407E, Arlington, VA 22203',
  'price_monthly': '$1,700/mo',
  'also_price': '1 bd',
  'sqft': '620 sqft'},
 {'address': '4310 N Pershing Dr #43101, Arlington, VA 22203',
  'price_monthly': '$1,425/mo',
  'also_price': '1 bd',
  'sqft': '699 sqft'},
 {'address': '728 N Wakefield St, Arlington, VA 22203',
  'price_monthly': '$1,475/mo',
  'also_price': '1 bd',
  'sqft': '550 sqft'},
 {'address': '880 N Pollard St APT 226, Arlington, VA 22203',
  'price_monthly': '$1,600/mo',
  'also_price': '1 bd',
  'sqft': '650 sqft'}]

In [285]:
zip_code ="22203"

apts_22203_df = pd.DataFrame(apartments_22203)
apts_22203_df['also_price'] = apts_22203_df['also_price'].str[:-4]
apts_22203_df["Zip Code"] = zip_code
apts_22203_df

,address,price_monthly,also_price,sqft,Zip Code
0,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22203
1,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22203
2,"Virginia Square | 901 N Nelson St, Arlington, VA",None,"$1,585+",None,22203
3,"AVA Ballston Square | 850 N Randolph St, Arlin...",None,"$1,440+",None,22203
4,"672 Flats | 672 N Glebe Rd, Arlington, VA",None,"$1,895+",None,22203
5,"Ballston Place | 901 N Pollard St, Arlington, VA",None,"$1,800+",None,22203
6,"Liberty Tower | 818 N Quincy St, Arlington, VA",None,"$1,640+",None,22203
7,"4322 2nd Rd N #43224, Arlington, VA 22203","$1,450/mo",,666 sqft,22203
8,"851 N Glebe Rd, Arlington, VA",None,"$1,795+",None,22203
9,"The Amelia | 816 N Oakland St, Arlington, VA",None,"$1,695+",None,22203
10,"Randolph Towers | 4001 9th St N, Arlington, VA",None,"$1,895+",None,22203
11,"The View at Liberty Center | 4000 Wilson Blvd,...",None,"$1,625+",None,22203
12,"J SOL | 4000 Fairfax Dr, Arlington, VA",None,"$1,905+",None,22203
13,"724 N Oakland St #724, Arlington, VA 22203","$1,975/mo",,800 sqft,22203
14,"Quincy Plaza | 3900 Fairfax Dr, Arlington, VA",None,"$1,595+",None,22203
15,"Origin | 700 N Randolph St, Arlington, VA",None,"$1,790+",None,22203
16,"Thomas Court | 470 N Thomas St, Arlington, VA",None,"$1,925+",None,22203
17,"Richmond Square | 900 N Randolph St, Arlington...",None,"$1,695+",None,22203
18,"4301 N Henderson Rd #656783, Arlington, VA 22203","$1,995+/mo",,680 sqft,22203
19,"4040 Wilson | 4040 Wilson Blvd, Arlington, VA",None,"$2,041+",None,22203
20,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22203
21,"900 N Stafford St, Arlington, VA",None,"$1,450+",None,22203
22,"3714 7th St N APT 5, Arlington, VA 22203","$1,500/mo",,550 sqft,22203
23,"4350 N Pershing Dr APT 4, Arlington, VA 22203","$1,600/mo",,660 sqft,22203
24,"4800 9th St N APT 4, Arlington, VA 22203","$1,700/mo",,750 sqft,22203
25,"230 N George Mason Dr, Arlington, VA",None,"$1,395+",None,22203
26,"3835 9th St N, Arlington, VA",None,"$1,775+",None,22203
27,"206 N George Mason Dr, Arlington, VA",None,"$1,300+",None,22203
28,"4141 N Henderson Rd, Arlington, VA",None,"$1,695+",None,22203
29,"3835 9th St N APT 706E, Arlington, VA 22203","$1,900/mo",,834 sqft,22203
30,"206 N Trenton St APT 1, Arlington, VA 22203","$1,395/mo",,699 sqft,22203
31,"888 N Quincy St, Arlington, VA",None,"$1,600+",None,22203
32,"851 N Glebe Rd, Arlington, VA 22203","$1,899/mo",,752 sqft,22203
33,"4314 N Carlin Springs Rd APT 11, Arlington, VA...","$1,450/mo",,750 sqft,22203
34,"3714 7th St N APT 4, Arlington, VA 22203","$1,400/mo",,650 sqft,22203
35,"900 N Taylor St, Arlington, VA",None,"$4,133+",None,22203
36,"3830 9th St N, Arlington, VA",None,"$1,795+",None,22203
37,"820 N Pollard St APT 507, Arlington, VA 22203","$1,900/mo",,729 sqft,22203
38,"4141 Henderson Rd, Arlington, VA",None,"$1,600+",None,22203
39,"3830 9th St N APT 407E, Arlington, VA 22203","$1,700/mo",,620 sqft,22203
40,"4310 N Pershing Dr #43101, Arlington, VA 22203","$1,425/mo",,699 sqft,22203
41,"728 N Wakefield St, Arlington, VA 22203","$1,475/mo",,550 sqft,22203
42,"880 N Pollard St APT 226, Arlington, VA 22203","$1,600/mo",,650 sqft,22203

In [286]:
#22202

apartments_22202 = []

In [292]:
url = 'https://www.zillow.com/arlington-va-22202/apartments/1-bedrooms/2_p'
browser.visit(url)

In [293]:
html = browser.html
soup = bs(html,'html.parser')

In [294]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22202.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1512 S Arlington Ridge Rd, Arlington, VA
None
$1,600+ 1 bd
None
-------------
The Gramercy | 550 14th Rd S, Arlington, VA
None
$1,464+ 1 bd
None
-------------
Crystal City Lofts | 305 10th St S, Arlington, VA
None
$1,737+ 1 bd
None
-------------
1805 Crystal Dr, Arlington, VA
None
$1,600+ 1 bd
None
-------------
618 19th St S, Arlington, VA 22202
<div class="list-card-price">$1,450/mo</div>
1 bd
500 sqft

In [295]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22202): 
    if word in stopwords:
        words.remove(word)

In [296]:
apartments_22202

[{'address': 'Crystal House | 1900 S Eads St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,395+ 1 bd',
  'sqft': None},
 {'address': 'Lofts 590 | 590 15th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,650+ 1 bd',
  'sqft': None},
 {'address': 'Water Park Towers | 1501 Crystal Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,596+ 1 bd',
  'sqft': None},
 {'address': 'Camden Potomac Yard | 3535 S Ball St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,449+ 1 bd',
  'sqft': None},
 {'address': 'Parc View Apartments | 815 18th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,333+ 1 bd',
  'sqft': None},
 {'address': 'Post Pentagon Row | 1201 S Joyce St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,516+ 1 bd',
  'sqft': None},
 {'address': 'RiverHouse | 1400 S Joyce St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,314+ 1 bd',
  'sqft': None},
 {'address': 'Landing: Flexible Leases, Designer Furnished, $0 Deposit in DC | 601 12th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,811+ 1 bd',
  'sqft': None},
 {'address': '1401 Joyce on Pentagon Row | 1401 S Joyce St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,751+ 1 bd',
  'sqft': None},
 {'address': 'Crystal Place | 1801 Crystal Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,489+ 1 bd',
  'sqft': None},
 {'address': 'Concord Crystal City | 2600 Crystal Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,637+ 1 bd',
  'sqft': None},
 {'address': 'Crystal Square Apartments | 1515 Richmond Hwy, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,699+ 1 bd',
  'sqft': None},
 {'address': 'The Point at Pentagon City | 1201 S Eads St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,617+ 1 bd',
  'sqft': None},
 {'address': '3600 S Glebe Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'Crystal Plaza | 2111 Richmond Hwy, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,450+ 1 bd',
  'sqft': None},
 {'address': 'The Sur | 3400 Potomac Ave, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,167+ 1 bd',
  'sqft': None},
 {'address': 'Aura Pentagon City | 1221-1331 S Eads St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,465+ 1 bd',
  'sqft': None},
 {'address': 'The Paramount | 1425 S Eads St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,566+ 1 bd',
  'sqft': None},
 {'address': 'The Acadia at Metropolitan Park | 575 12th Rd S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,530+ 1 bd',
  'sqft': None},
 {'address': 'The Millennium at Metropolitan Park | 1330 S Fair St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,610+ 1 bd',
  'sqft': None},
 {'address': '2221 S Clark St #6KGE40ZPW, Arlington, VA 22202',
  'price_monthly': '$1,582+/mo',
  'also_price': '1 bd',
  'sqft': '-- sqft'},
 {'address': 'The Witmer Pentagon City | 710 12th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,868+ 1 bd',
  'sqft': None},
 {'address': '220 Twentieth Street | 220 20th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,705+ 1 bd',
  'sqft': None},
 {'address': 'The Bartlett | 520 12th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,641+ 1 bd',
  'sqft': None},
 {'address': 'The Clark | 3400 S Clark St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,621+ 1 bd',
  'sqft': None},
 {'address': 'Altaire North | 402 Army Navy Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,925+ 1 bd',
  'sqft': None},
 {'address': '1101 S Arlington Ridge Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$2,195+ 1 bd',
  'sqft': None},
 {'address': 'Lenox Club | 401 12th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,440+ 1 bd',
  'sqft': None},
 {'address': '1121 S Eads St #503, Arlington, VA 22202',
  'price_monthly': '$2,200/mo',
  'also_price': '1 bd',
  'sqft': '837 sqft'},
 {'address': '3650 S Glebe Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,800+ 1 bd',
  'sqft': None},
 {'address': '822 20th St S #B, Arlington, VA 22202',
  'price_monthly': '$1,400/mo',
  'also_price': '1 bd',
  'sqft': '600 sqft'},
 {'address': '520 24th St S, Arlington, VA 22202',
  'price_monthly': '$4,470/mo',
  'also_price': '1 bd',
  'sqft': '629 sqft'},
 {'address': '1211 S Eads St, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,900+ 1 bd',
  'sqft': None},
 {'address': '1300 Army Navy Dr APT 720, Arlington, VA 22202',
  'price_monthly': '$1,595/mo',
  'also_price': '1 bd',
  'sqft': '660 sqft'},
 {'address': 'Altaire | 400 Army Navy Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,700+ 1 bd',
  'sqft': None},
 {'address': '1300 Army Navy Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,400+ 1 bd',
  'sqft': None},
 {'address': '1200 S Arlington Ridge Rd APT 405, Arlington, VA 22202',
  'price_monthly': '$1,500/mo',
  'also_price': '1 bd',
  'sqft': '700 sqft'},
 {'address': '1805 Crystal Dr APT 203, Arlington, VA 22202',
  'price_monthly': '$1,800/mo',
  'also_price': '1 bd',
  'sqft': '676 sqft'},
 {'address': '610 21st St S #B, Arlington, VA 22202',
  'price_monthly': '$1,850/mo',
  'also_price': '1 bd',
  'sqft': '750 sqft'},
 {'address': '1300 S Arlington Ridge Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,500+ 1 bd',
  'sqft': None},
 {'address': '1512 S Arlington Ridge Rd, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': 'The Gramercy | 550 14th Rd S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,464+ 1 bd',
  'sqft': None},
 {'address': 'Crystal City Lofts | 305 10th St S, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,737+ 1 bd',
  'sqft': None},
 {'address': '1805 Crystal Dr, Arlington, VA',
  'price_monthly': None,
  'also_price': '$1,600+ 1 bd',
  'sqft': None},
 {'address': '618 19th St S, Arlington, VA 22202',
  'price_monthly': '$1,450/mo',
  'also_price': '1 bd',
  'sqft': '500 sqft'}]

In [297]:
zip_code ="22202"

apts_22202_df = pd.DataFrame(apartments_22202)
apts_22202_df['also_price'] = apts_22202_df['also_price'].str[:-4]
apts_22202_df["Zip Code"] = zip_code
apts_22202_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Crystal House | 1900 S Eads St, Arlington, VA",None,"$1,395+",None,22202
1,"Lofts 590 | 590 15th St S, Arlington, VA",None,"$1,650+",None,22202
2,"Water Park Towers | 1501 Crystal Dr, Arlington...",None,"$1,596+",None,22202
3,"Camden Potomac Yard | 3535 S Ball St, Arlingto...",None,"$1,449+",None,22202
4,"Parc View Apartments | 815 18th St S, Arlingto...",None,"$1,333+",None,22202
5,"Post Pentagon Row | 1201 S Joyce St, Arlington...",None,"$1,516+",None,22202
6,"RiverHouse | 1400 S Joyce St, Arlington, VA",None,"$1,314+",None,22202
7,"Landing: Flexible Leases, Designer Furnished, ...",None,"$1,811+",None,22202
8,"1401 Joyce on Pentagon Row | 1401 S Joyce St, ...",None,"$1,751+",None,22202
9,"Crystal Place | 1801 Crystal Dr, Arlington, VA",None,"$1,489+",None,22202
10,"Concord Crystal City | 2600 Crystal Dr, Arling...",None,"$1,637+",None,22202
11,"Crystal Square Apartments | 1515 Richmond Hwy,...",None,"$1,699+",None,22202
12,"The Point at Pentagon City | 1201 S Eads St, A...",None,"$1,617+",None,22202
13,"3600 S Glebe Rd, Arlington, VA",None,"$1,600+",None,22202
14,"Crystal Plaza | 2111 Richmond Hwy, Arlington, VA",None,"$1,450+",None,22202
15,"The Sur | 3400 Potomac Ave, Arlington, VA",None,"$2,167+",None,22202
16,"Aura Pentagon City | 1221-1331 S Eads St, Arli...",None,"$1,465+",None,22202
17,"The Paramount | 1425 S Eads St, Arlington, VA",None,"$1,566+",None,22202
18,The Acadia at Metropolitan Park | 575 12th Rd ...,None,"$1,530+",None,22202
19,The Millennium at Metropolitan Park | 1330 S F...,None,"$1,610+",None,22202
20,"2221 S Clark St #6KGE40ZPW, Arlington, VA 22202","$1,582+/mo",,-- sqft,22202
21,"The Witmer Pentagon City | 710 12th St S, Arli...",None,"$1,868+",None,22202
22,"220 Twentieth Street | 220 20th St S, Arlingto...",None,"$1,705+",None,22202
23,"The Bartlett | 520 12th St S, Arlington, VA",None,"$1,641+",None,22202
24,"The Clark | 3400 S Clark St, Arlington, VA",None,"$1,621+",None,22202
25,"Altaire North | 402 Army Navy Dr, Arlington, VA",None,"$1,925+",None,22202
26,"1101 S Arlington Ridge Rd, Arlington, VA",None,"$2,195+",None,22202
27,"Lenox Club | 401 12th St S, Arlington, VA",None,"$1,440+",None,22202
28,"1121 S Eads St #503, Arlington, VA 22202","$2,200/mo",,837 sqft,22202
29,"3650 S Glebe Rd, Arlington, VA",None,"$1,800+",None,22202
30,"822 20th St S #B, Arlington, VA 22202","$1,400/mo",,600 sqft,22202
31,"520 24th St S, Arlington, VA 22202","$4,470/mo",,629 sqft,22202
32,"1211 S Eads St, Arlington, VA",None,"$1,900+",None,22202
33,"1300 Army Navy Dr APT 720, Arlington, VA 22202","$1,595/mo",,660 sqft,22202
34,"Altaire | 400 Army Navy Dr, Arlington, VA",None,"$1,700+",None,22202
35,"1300 Army Navy Dr, Arlington, VA",None,"$1,400+",None,22202
36,"1200 S Arlington Ridge Rd APT 405, Arlington, ...","$1,500/mo",,700 sqft,22202
37,"1805 Crystal Dr APT 203, Arlington, VA 22202","$1,800/mo",,676 sqft,22202
38,"610 21st St S #B, Arlington, VA 22202","$1,850/mo",,750 sqft,22202
39,"1300 S Arlington Ridge Rd, Arlington, VA",None,"$1,500+",None,22202
40,"1512 S Arlington Ridge Rd, Arlington, VA",None,"$1,600+",None,22202
41,"The Gramercy | 550 14th Rd S, Arlington, VA",None,"$1,464+",None,22202
42,"Crystal City Lofts | 305 10th St S, Arlington, VA",None,"$1,737+",None,22202
43,"1805 Crystal Dr, Arlington, VA",None,"$1,600+",None,22202
44,"618 19th St S, Arlington, VA 22202","$1,450/mo",,500 sqft,22202

In [298]:
#22207

apartments_22207 = []

In [299]:
url = 'https://www.zillow.com/arlington-va-22207/apartments/1-bedrooms/'
browser.visit(url)

In [300]:
html = browser.html
soup = bs(html,'html.parser')

In [301]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22207.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Avalon Arlington North | 2105 N Glebe Rd, Arlington, VA
None
$1,845+ 1 bd
None
-------------
2055 Vermont Street | 2055 N Vermont St, Arlington, VA
None
$1,450+ 1 bd
None
-------------
Cherry Hill Apartments | 2120 N Monroe St, Arlington, VA
None
$1,795+ 1 bd
None
-------------
Oakcrest | 4385 Lee Hwy, Arlington, VA
None
$1,250+ 1 bd
None
-------------
1931 N Cameron St, Arlington, VA 22207
<div class="list-card-price">$1,450+/mo</div>
1 bd
720 sqft
-------------
2055 N Woodstock St APT 301, Arlington, VA 22207
<div class="list-card-price">$1,400/mo</div>
1 bd
660 sqft
-------------
2101 N Monroe St APT 117, Arlington, VA 22207
<div class="list-card-price">$1,645/mo</div>
1 bd
605 sqft
-------------
4201 Lee Hwy APT 208, Arlington, VA 22207
<div class="list-card-price">$1,675/mo</div>
1 bd
809 sqft
-------------
2055-204 N Woodstock St, Arlington, VA 22207
<div class="list-card-price">$1,250/mo</div>
1 bd
583 sqft
-------------
3800 Lee Hwy UNIT 204, Arlington, VA 22207
<div class="list-card-price">$2,300/mo</div>
1 bd
825 sqft

In [302]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22207): 
    if word in stopwords:
        words.remove(word)

In [303]:
zip_code ="22207"

apts_22207_df = pd.DataFrame(apartments_22207)
apts_22207_df['also_price'] = apts_22207_df['also_price'].str[:-4]
apts_22207_df["Zip Code"] = zip_code
apts_22207_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Avalon Arlington North | 2105 N Glebe Rd, Arli...",None,"$1,845+",None,22207
1,"2055 Vermont Street | 2055 N Vermont St, Arlin...",None,"$1,450+",None,22207
2,"Cherry Hill Apartments | 2120 N Monroe St, Arl...",None,"$1,795+",None,22207
3,"Oakcrest | 4385 Lee Hwy, Arlington, VA",None,"$1,250+",None,22207
4,"1931 N Cameron St, Arlington, VA 22207","$1,450+/mo",,720 sqft,22207
5,"2055 N Woodstock St APT 301, Arlington, VA 22207","$1,400/mo",,660 sqft,22207
6,"2101 N Monroe St APT 117, Arlington, VA 22207","$1,645/mo",,605 sqft,22207
7,"4201 Lee Hwy APT 208, Arlington, VA 22207","$1,675/mo",,809 sqft,22207
8,"2055-204 N Woodstock St, Arlington, VA 22207","$1,250/mo",,583 sqft,22207
9,"3800 Lee Hwy UNIT 204, Arlington, VA 22207","$2,300/mo",,825 sqft,22207

In [304]:
#20006

apartments_20006 = []

In [305]:
url = 'https://www.zillow.com/washington-dc-20006/apartments/1-bedrooms/'
browser.visit(url)

In [306]:
html = browser.html
soup = bs(html,'html.parser')

In [307]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20006.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
The Statesman | 2020 F St NW, Washington, DC
None
$1,693+ 1 bd
None
-------------
City Market at O Street | 800 P St NW, Washington, DC
None
$1,702+ 1 bd
None
-------------
The Apartments at CityCenter | 825 10th St NW, Washington, DC
None
$2,760+ 1 bd
None
-------------
1331 | 1331 Maryland Ave SW, Washington, DC
None
$2,495+ 1 bd
None
-------------
555 | 555 E St SW, Washington, DC
None
$2,074+ 1 bd
None
-------------
Yale West | 443 New York Ave NW, Washington, DC
None
$1,838+ 1 bd
None
-------------
Residences on The Avenue | 2221 I St NW, Washington, DC
None
$1,990+ 1 bd
None
-------------
450K | 450 K St NW, Washington, DC
None
$1,984+ 1 bd
None
-------------
District | 1401 S St NW, Washington, DC
None
$1,998+ 1 bd
None

In [ ]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20006): 
    if word in stopwords:
        words.remove(word)

In [ ]:
zip_code ="20006"

apts_20006_df = pd.DataFrame(apartments_20006)
apts_20006_df['also_price'] = apts_20006_df['also_price'].str[:-4]
apts_20006_df["Zip Code"] = zip_code
apts_20006_df

In [308]:
#20036

apartments_20036 = []

In [309]:
url = 'https://www.zillow.com/washington-dc-20036/apartments/1-bedrooms/'
browser.visit(url)

In [310]:
html = browser.html
soup = bs(html,'html.parser')

In [311]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20036.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1718 P St NW, Washington, DC
None
$1,750+ 1 bd
None
-------------
1280 21st St NW, Washington, DC
None
$2,500+ 1 bd
None
-------------
The Flats at Dupont Circle | 2000 N St NW, Washington, DC
None
$1,956+ 1 bd
None
-------------
Gables Dupont Circle | 1750 P St NW, Washington, DC
None
$1,960+ 1 bd
None
-------------
Bristol House | 1400 20th St NW, Washington, DC
None
$2,099+ 1 bd
None
-------------
The Bond | 1230 New Hampshire Ave NW, Washington, DC
None
$2,125+ 1 bd
None
-------------
Blueground Furnished Apartments DC | 1025 Connecticut Ave NW, Washington, DC
None
$2,130+ 1 bd
None
-------------
Hightowers | 1530 16th St NW, Washington, DC
None
$1,800+ 1 bd
None
-------------
1316 New Hampshire Ave NW, Washington, DC
None
$1,975+ 1 bd
None
-------------
1757 Church St NW, Washington, DC
None
$2,395+ 1 bd
None
-------------
1545 18th St NW, Washington, DC
None
$1,950+ 1 bd
None
-------------
1426 21st St NW APT 403, Washington, DC 20036
<div class="list-card-price">$3,100/mo</div>
1 bd
700 sqft
-------------
1301 20th St NW, Washington, DC
None
$1,995+ 1 bd
None
-------------
1260 21st St NW, Washington, DC
None
$1,950+ 1 bd
None
-------------
Brunswick House | 1414 17th St NW, Washington, DC
None
$1,750+ 1 bd
None
-------------
101-1429 21st St NW #101, Washington, DC 20036
<div class="list-card-price">$2,100/mo</div>
1 bd
-- sqft
-------------
1320 21st St NW, Washington, DC
None
$2,100+ 1 bd
None
-------------
1330 New Hampshire Ave NW, Washington, DC
None
$1,875+ 1 bd
None
-------------
1737 P St NW APT 102, Washington, DC 20036
<div class="list-card-price">$1,800/mo</div>
1 bd
513 sqft
-------------
1401 17th St NW, Washington, DC
None
$2,150+ 1 bd
None
-------------
1521 17th St NW #301, Washington, DC 20036
<div class="list-card-price">$2,300/mo</div>
1 bd
-- sqft
-------------
1711 Massachusetts Ave NW, Washington, DC
None
$1,545+ 1 bd
None
-------------
2007 O St NW, Washington, DC
None
$2,070+ 1 bd
None
-------------
1325 18th St NW, Washington, DC
None
$1,650+ 1 bd
None
-------------
1420 Hopkins St NW #1, Washington, DC 20036
<div class="list-card-price">$1,450/mo</div>
1 bd
600 sqft
-------------
1715 P St NW APT 402, Washington, DC 20036
<div class="list-card-price">$1,599/mo</div>
1 bd
-- sqft
-------------
1727 Massachusetts Ave NW #219, Washington, DC 20036
<div class="list-card-price">$1,995/mo</div>
1 bd
633 sqft
-------------
1718 P St NW, Washington, DC 20036
<div class="list-card-price">$2,350/mo</div>
1 bd
710 sqft
-------------
(undisclosed Address), Washington, DC 20036
<div class="list-card-price">$2,775/mo</div>
1 bd
711 sqft
-------------
1408 21st St NW, Washington, DC 20036
<div class="list-card-price">$2,450/mo</div>
1 bd
700 sqft
-------------
1425 21st St NW, Washington, DC
None
$2,100+ 1 bd
None
-------------
1718 P St NW APT 702, Washington, DC 20036
<div class="list-card-price">$2,300/mo</div>
1 bd
755 sqft
-------------
1415 Hopkins St NW APT 3, Washington, DC 20036
<div class="list-card-price">$1,999/mo</div>
1 bd
750 sqft
-------------
2032 O St NW #70MEXFDH9, Washington, DC 20036
<div class="list-card-price">$1,849+/mo</div>
1 bd
-- sqft
-------------
2012 O St NW, Washington, DC
None
$2,000+ 1 bd
None
-------------
1705 P St NW APT 2, Washington, DC 20036
<div class="list-card-price">$1,950/mo</div>
1 bd
488 sqft
-------------
1403 21st St NW APT 4, Washington, DC 20036
<div class="list-card-price">$3,100/mo</div>
1 bd
1,050 sqft
-------------
1415 17th St NW, Washington, DC
None
$2,090+ 1 bd
None

In [312]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20036): 
    if word in stopwords:
        words.remove(word)

In [313]:
zip_code ="20036"

apts_20036_df = pd.DataFrame(apartments_20036)
apts_20036_df['also_price'] = apts_20036_df['also_price'].str[:-4]
apts_20036_df["Zip Code"] = zip_code
apts_20036_df

,address,price_monthly,also_price,sqft,Zip Code
0,"1718 P St NW, Washington, DC",None,"$1,750+",None,20036
1,"1280 21st St NW, Washington, DC",None,"$2,500+",None,20036
2,"The Flats at Dupont Circle | 2000 N St NW, Was...",None,"$1,956+",None,20036
3,"Gables Dupont Circle | 1750 P St NW, Washingto...",None,"$1,960+",None,20036
4,"Bristol House | 1400 20th St NW, Washington, DC",None,"$2,099+",None,20036
5,"The Bond | 1230 New Hampshire Ave NW, Washingt...",None,"$2,125+",None,20036
6,Blueground Furnished Apartments DC | 1025 Conn...,None,"$2,130+",None,20036
7,"Hightowers | 1530 16th St NW, Washington, DC",None,"$1,800+",None,20036
8,"1316 New Hampshire Ave NW, Washington, DC",None,"$1,975+",None,20036
9,"1757 Church St NW, Washington, DC",None,"$2,395+",None,20036
10,"1545 18th St NW, Washington, DC",None,"$1,950+",None,20036
11,"1426 21st St NW APT 403, Washington, DC 20036","$3,100/mo",,700 sqft,20036
12,"1301 20th St NW, Washington, DC",None,"$1,995+",None,20036
13,"1260 21st St NW, Washington, DC",None,"$1,950+",None,20036
14,"Brunswick House | 1414 17th St NW, Washington, DC",None,"$1,750+",None,20036
15,"101-1429 21st St NW #101, Washington, DC 20036","$2,100/mo",,-- sqft,20036
16,"1320 21st St NW, Washington, DC",None,"$2,100+",None,20036
17,"1330 New Hampshire Ave NW, Washington, DC",None,"$1,875+",None,20036
18,"1737 P St NW APT 102, Washington, DC 20036","$1,800/mo",,513 sqft,20036
19,"1401 17th St NW, Washington, DC",None,"$2,150+",None,20036
20,"1521 17th St NW #301, Washington, DC 20036","$2,300/mo",,-- sqft,20036
21,"1711 Massachusetts Ave NW, Washington, DC",None,"$1,545+",None,20036
22,"2007 O St NW, Washington, DC",None,"$2,070+",None,20036
23,"1325 18th St NW, Washington, DC",None,"$1,650+",None,20036
24,"1420 Hopkins St NW #1, Washington, DC 20036","$1,450/mo",,600 sqft,20036
25,"1715 P St NW APT 402, Washington, DC 20036","$1,599/mo",,-- sqft,20036
26,"1727 Massachusetts Ave NW #219, Washington, DC...","$1,995/mo",,633 sqft,20036
27,"1718 P St NW, Washington, DC 20036","$2,350/mo",,710 sqft,20036
28,"(undisclosed Address), Washington, DC 20036","$2,775/mo",,711 sqft,20036
29,"1408 21st St NW, Washington, DC 20036","$2,450/mo",,700 sqft,20036
30,"1425 21st St NW, Washington, DC",None,"$2,100+",None,20036
31,"1718 P St NW APT 702, Washington, DC 20036","$2,300/mo",,755 sqft,20036
32,"1415 Hopkins St NW APT 3, Washington, DC 20036","$1,999/mo",,750 sqft,20036
33,"2032 O St NW #70MEXFDH9, Washington, DC 20036","$1,849+/mo",,-- sqft,20036
34,"2012 O St NW, Washington, DC",None,"$2,000+",None,20036
35,"1705 P St NW APT 2, Washington, DC 20036","$1,950/mo",,488 sqft,20036
36,"1403 21st St NW APT 4, Washington, DC 20036","$3,100/mo",,"1,050 sqft",20036
37,"1415 17th St NW, Washington, DC",None,"$2,090+",None,20036

In [314]:
#20004

apartments_20004 = []

In [315]:
url = 'https://www.zillow.com/washington-dc-20004/apartments/1-bedrooms/'
browser.visit(url)

In [316]:
html = browser.html
soup = bs(html,'html.parser')

In [317]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20004.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
The Lexington at Market Square | 400 8th St NW, Washington, DC
None
$2,323+ 1 bd
None
-------------
Historic Row | 515 9th St NW, Washington, DC
None
$2,450+ 1 bd
None
-------------
425 8th St NW #1678532, Washington, DC 20004
<div class="list-card-price">$2,100+/mo</div>
1 bd
680 sqft
-------------
801 Pennsylvania Ave NW, Washington, DC
None
$1,900+ 1 bd
None
-------------
915 E St NW, Washington, DC
None
$2,300+ 1 bd
None
-------------
915 E St NW, Washington, DC
None
$1,545+ 1 bd
None
-------------
912 F St NW, Washington, DC 20004
<div class="list-card-price">$2,195/mo</div>
1 bd
760 sqft
-------------
631 D St NW, Washington, DC
None
$1,975+ 1 bd
None
-------------
(undisclosed Address), Washington, DC 20004
<div class="list-card-price">$3,060/mo</div>
1 bd
680 sqft
-------------
616 E St NW, Washington, DC
None
$2,350+ 1 bd
None
-------------
701 Pennsylvania Ave NW, Washington, DC
None
$2,150+ 1 bd
None
-------------
675 E St NW APT 820, Washington, DC 20004
<div class="list-card-price">$2,950/mo</div>
1 bd
959 sqft
-------------
912 F St NW APT 704, Washington, DC 20004
<div class="list-card-price">$2,500/mo</div>
1 bd
935 sqft

In [318]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20004): 
    if word in stopwords:
        words.remove(word)

In [319]:
zip_code ="20004"

apts_20004_df = pd.DataFrame(apartments_20004)
apts_20004_df['also_price'] = apts_20004_df['also_price'].str[:-4]
apts_20004_df["Zip Code"] = zip_code
apts_20004_df

,address,price_monthly,also_price,sqft,Zip Code
0,The Lexington at Market Square | 400 8th St NW...,None,"$2,323+",None,20004
1,"Historic Row | 515 9th St NW, Washington, DC",None,"$2,450+",None,20004
2,"425 8th St NW #1678532, Washington, DC 20004","$2,100+/mo",,680 sqft,20004
3,"801 Pennsylvania Ave NW, Washington, DC",None,"$1,900+",None,20004
4,"915 E St NW, Washington, DC",None,"$2,300+",None,20004
5,"915 E St NW, Washington, DC",None,"$1,545+",None,20004
6,"912 F St NW, Washington, DC 20004","$2,195/mo",,760 sqft,20004
7,"631 D St NW, Washington, DC",None,"$1,975+",None,20004
8,"(undisclosed Address), Washington, DC 20004","$3,060/mo",,680 sqft,20004
9,"616 E St NW, Washington, DC",None,"$2,350+",None,20004
10,"701 Pennsylvania Ave NW, Washington, DC",None,"$2,150+",None,20004
11,"675 E St NW APT 820, Washington, DC 20004","$2,950/mo",,959 sqft,20004
12,"912 F St NW APT 704, Washington, DC 20004","$2,500/mo",,935 sqft,20004

In [320]:
#20024

apartments_20024 = []

In [321]:
url = 'https://www.zillow.com/washington-dc-20024/apartments/1-bedrooms/'
browser.visit(url)

In [322]:
html = browser.html
soup = bs(html,'html.parser')

In [323]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20024.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
1331 | 1331 Maryland Ave SW, Washington, DC
None
$2,495+ 1 bd
None
-------------
555 | 555 E St SW, Washington, DC
None
$2,074+ 1 bd
None
-------------
Modern on M | 465 M St SW, Washington, DC
None
$1,744+ 1 bd
None
-------------
Lex and Leo at Waterfront Station | 1150 4th St SW, Washington, DC
None
$1,730+ 1 bd
None
-------------
Eliot on 4th | 1001 4th St SW, Washington, DC
None
$1,705+ 1 bd
None
-------------
Valo | 222 M St SW, Washington, DC
None
$1,803+ 1 bd
None
-------------
Waterside Towers | 907 6th St SW, Washington, DC
None
$1,599+ 1 bd
None
-------------
350 G St SW, Washington, DC
None
$1,675+ 1 bd
None
-------------
240 M St SW #E505, Washington, DC 20024
<div class="list-card-price">$1,950/mo</div>
1 bd
546 sqft
-------------
700 7th St SW APT 628, Washington, DC 20024
<div class="list-card-price">$2,100/mo</div>
1 bd
742 sqft
-------------
1301 Delaware Ave SW, Washington, DC
None
$1,600+ 1 bd
None
-------------
1250 4th St SW #W614, Washington, DC 20024
<div class="list-card-price">$2,100/mo</div>
1 bd
898 sqft
-------------
Capitol Park Tower | 301 G St SW, Washington, DC
None
$1,470+ 1 bd
None
-------------
300 M St SW, Washington, DC
None
$1,700+ 1 bd
None
-------------
1101 3rd St SW, Washington, DC
None
$1,850+ 1 bd
None
-------------
355 I St SW, Washington, DC
None
$1,950+ 1 bd
None
-------------
115 O St SW, Washington, DC 20024
<div class="list-card-price">$1,600/mo</div>
1 bd
500 sqft
-------------
1250 4th St SW, Washington, DC
None
$1,650+ 1 bd
None
-------------
525 Water St SW #306, Washington, DC 20024
<div class="list-card-price">$2,150/mo</div>
1 bd
510 sqft
-------------
Channel Square Apartments | 325 P St SW, Washington, DC
None
$1,850+ 1 bd
None
-------------
Watermark at Buzzard Point | 1900 Half St SW, Washington, DC
None
$1,865+ 1 bd
None
-------------
800 4th St SW, Washington, DC
None
$1,528+ 1 bd
None
-------------
1311 Delaware Ave SW APT S529, Washington, DC 20024
<div class="list-card-price">$1,800/mo</div>
1 bd
680 sqft
-------------
800 4th St SW, Washington, DC 20024
<div class="list-card-price">$1,850/mo</div>
1 bd
686 sqft
-------------
103 P St SW APT 1, Washington, DC 20024
<div class="list-card-price">$1,300/mo</div>
1 bd
-- sqft
-------------
1425 4th St SW, Washington, DC
None
$1,900+ 1 bd
None
-------------
1240 Carrollsburg Pl SW APT B, Washington, DC 20024
<div class="list-card-price">$1,625/mo</div>
1 bd
800 sqft
-------------
1245 4th St SW APT E305, Washington, DC 20024
<div class="list-card-price">$1,800/mo</div>
1 bd
807 sqft
-------------
301 G St SW APT 802, Washington, DC 20024
<div class="list-card-price">$1,834/mo</div>
1 bd
558 sqft
-------------
88 V St SW, Washington, DC
None
$2,500+ 1 bd
None
-------------
240 M St SW #479, Washington, DC 20024
<div class="list-card-price">$1,690/mo</div>
1 bd
690 sqft
-------------
1435 4th St SW APT B114, Washington, DC 20024
<div class="list-card-price">$1,950/mo</div>
1 bd
713 sqft

In [324]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20024): 
    if word in stopwords:
        words.remove(word)

In [325]:
zip_code ="20024"

apts_20024_df = pd.DataFrame(apartments_20024)
apts_20024_df['also_price'] = apts_20024_df['also_price'].str[:-4]
apts_20024_df["Zip Code"] = zip_code
apts_20024_df

,address,price_monthly,also_price,sqft,Zip Code
0,"1331 | 1331 Maryland Ave SW, Washington, DC",None,"$2,495+",None,20024
1,"555 | 555 E St SW, Washington, DC",None,"$2,074+",None,20024
2,"Modern on M | 465 M St SW, Washington, DC",None,"$1,744+",None,20024
3,Lex and Leo at Waterfront Station | 1150 4th S...,None,"$1,730+",None,20024
4,"Eliot on 4th | 1001 4th St SW, Washington, DC",None,"$1,705+",None,20024
5,"Valo | 222 M St SW, Washington, DC",None,"$1,803+",None,20024
6,"Waterside Towers | 907 6th St SW, Washington, DC",None,"$1,599+",None,20024
7,"350 G St SW, Washington, DC",None,"$1,675+",None,20024
8,"240 M St SW #E505, Washington, DC 20024","$1,950/mo",,546 sqft,20024
9,"700 7th St SW APT 628, Washington, DC 20024","$2,100/mo",,742 sqft,20024
10,"1301 Delaware Ave SW, Washington, DC",None,"$1,600+",None,20024
11,"1250 4th St SW #W614, Washington, DC 20024","$2,100/mo",,898 sqft,20024
12,"Capitol Park Tower | 301 G St SW, Washington, DC",None,"$1,470+",None,20024
13,"300 M St SW, Washington, DC",None,"$1,700+",None,20024
14,"1101 3rd St SW, Washington, DC",None,"$1,850+",None,20024
15,"355 I St SW, Washington, DC",None,"$1,950+",None,20024
16,"115 O St SW, Washington, DC 20024","$1,600/mo",,500 sqft,20024
17,"1250 4th St SW, Washington, DC",None,"$1,650+",None,20024
18,"525 Water St SW #306, Washington, DC 20024","$2,150/mo",,510 sqft,20024
19,"Channel Square Apartments | 325 P St SW, Washi...",None,"$1,850+",None,20024
20,"Watermark at Buzzard Point | 1900 Half St SW, ...",None,"$1,865+",None,20024
21,"800 4th St SW, Washington, DC",None,"$1,528+",None,20024
22,"1311 Delaware Ave SW APT S529, Washington, DC ...","$1,800/mo",,680 sqft,20024
23,"800 4th St SW, Washington, DC 20024","$1,850/mo",,686 sqft,20024
24,"103 P St SW APT 1, Washington, DC 20024","$1,300/mo",,-- sqft,20024
25,"1425 4th St SW, Washington, DC",None,"$1,900+",None,20024
26,"1240 Carrollsburg Pl SW APT B, Washington, DC ...","$1,625/mo",,800 sqft,20024
27,"1245 4th St SW APT E305, Washington, DC 20024","$1,800/mo",,807 sqft,20024
28,"301 G St SW APT 802, Washington, DC 20024","$1,834/mo",,558 sqft,20024
29,"88 V St SW, Washington, DC",None,"$2,500+",None,20024
30,"240 M St SW #479, Washington, DC 20024","$1,690/mo",,690 sqft,20024
31,"1435 4th St SW APT B114, Washington, DC 20024","$1,950/mo",,713 sqft,20024

In [326]:
#20032

apartments_20032 = []

In [327]:
url = 'https://www.zillow.com/washington-dc-20032/apartments/1-bedrooms/'
browser.visit(url)

In [328]:
html = browser.html
soup = bs(html,'html.parser')

In [329]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20032.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Eagle's Crossing | 116 Irvington St SW, Washington, DC
None
$936+ 1 bd
None
-------------
625 Mellon St SE #2, Washington, DC 20032
<div class="list-card-price">$1,100/mo</div>
1 bd
-- sqft
-------------
601 Atlantic St SE #1, Washington, DC 20032
<div class="list-card-price">$900/mo</div>
1 bd
3,090 sqft
-------------
2 Forrester St SE #6SE-101, Washington, DC 20032
<div class="list-card-price">$1,035/mo</div>
1 bd
577 sqft
-------------
Oak Hill Apartments | 3322 Wheeler Rd SE, Washington, DC
None
$1,109+ 1 bd
None
-------------
39 Galveston Pl SW, Washington, DC 20032
<div class="list-card-price">$1,202/mo</div>
1 bd
2,720 sqft
-------------
535 Mellon St SE APT 7, Washington, DC 20032
<div class="list-card-price">$1,250/mo</div>
1 bd
-- sqft
-------------
47 Forrester St SW, Washington, DC 20032
<div class="list-card-price">$1,100/mo</div>
1 bd
3,834 sqft
-------------
3325 Martin Luther King Jr Ave SE APT 2, Washington, DC 20032
<div class="list-card-price">$895/mo</div>
1 bd
-- sqft
-------------
4201 7th St SE #0NJBWFXMY, Washington, DC 20032
<div class="list-card-price">$995+/mo</div>
1 bd
680 sqft

In [330]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20032): 
    if word in stopwords:
        words.remove(word)

In [331]:
zip_code ="20032"

apts_20032_df = pd.DataFrame(apartments_20032)
apts_20032_df['also_price'] = apts_20032_df['also_price'].str[:-4]
apts_20032_df["Zip Code"] = zip_code
apts_20032_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Eagle's Crossing | 116 Irvington St SW, Washin...",None,$936+,None,20032
1,"625 Mellon St SE #2, Washington, DC 20032","$1,100/mo",,-- sqft,20032
2,"601 Atlantic St SE #1, Washington, DC 20032",$900/mo,,"3,090 sqft",20032
3,"2 Forrester St SE #6SE-101, Washington, DC 20032","$1,035/mo",,577 sqft,20032
4,"Oak Hill Apartments | 3322 Wheeler Rd SE, Wash...",None,"$1,109+",None,20032
5,"39 Galveston Pl SW, Washington, DC 20032","$1,202/mo",,"2,720 sqft",20032
6,"535 Mellon St SE APT 7, Washington, DC 20032","$1,250/mo",,-- sqft,20032
7,"47 Forrester St SW, Washington, DC 20032","$1,100/mo",,"3,834 sqft",20032
8,"3325 Martin Luther King Jr Ave SE APT 2, Washi...",$895/mo,,-- sqft,20032
9,"4201 7th St SE #0NJBWFXMY, Washington, DC 20032",$995+/mo,,680 sqft,20032

In [332]:
#20020

apartments_20020 = []

In [333]:
url = 'https://www.zillow.com/washington-dc-20020/apartments/1-bedrooms/'
browser.visit(url)

In [334]:
html = browser.html
soup = bs(html,'html.parser')

In [335]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20020.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
2333 Skyland Pl SE #360-0605, Washington, DC 20020
<div class="list-card-price">$1,145/mo</div>
1 bd
575 sqft
-------------
2633-2645 Naylor Rd SE #2633-0T2, Washington, DC 20020
<div class="list-card-price">$1,225/mo</div>
1 bd
715 sqft
-------------
2139 Suitland Ter SE APT 101, Washington, DC 20020
<div class="list-card-price">$1,375/mo</div>
1 bd
625 sqft
-------------
2110 38th St SE APT 301, Washington, DC 20020
<div class="list-card-price">$1,450/mo</div>
1 bd
640 sqft
-------------
1501 27th St SE APT 102, Washington, DC 20020
<div class="list-card-price">$1,150/mo</div>
1 bd
650 sqft
-------------
3111 Naylor Rd SE APT 104, Washington, DC 20020
<div class="list-card-price">$1,100/mo</div>
1 bd
654 sqft
-------------
3937 S St SE APT 207, Washington, DC 20020
<div class="list-card-price">$1,300/mo</div>
1 bd
635 sqft
-------------
2345 Green St SE #3, Washington, DC 20020
<div class="list-card-price">$1,025/mo</div>
1 bd
-- sqft
-------------
(undisclosed Address), Washington, DC 20020
<div class="list-card-price">$1,250/mo</div>
1 bd
-- sqft
-------------
2337 Green St SE #2345-3, Washington, DC 20020
<div class="list-card-price">$975/mo</div>
1 bd
-- sqft
-------------
Parkway Overlook Apartments | 2841 Robinson Pl SE, Washington, DC
None
$1,070+ 1 bd
None
-------------
2612 29th St SE #4, Washington, DC 20020
<div class="list-card-price">$1,350/mo</div>
1 bd
3,024 sqft
-------------
1831 P St SE #32I, Washington, DC 20020
<div class="list-card-price">$895/mo</div>
1 bd
550 sqft
-------------
2106 38th St SE APT 102, Washington, DC 20020
<div class="list-card-price">$1,375/mo</div>
1 bd
625 sqft
-------------
Oxford Manor | 2607 Bowen Rd SE, Washington, DC
None
$1,200+ 1 bd
None
-------------
1812 23rd St SE #2308260, Washington, DC 20020
<div class="list-card-price">$1,195+/mo</div>
1 bd
650 sqft

In [336]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20020): 
    if word in stopwords:
        words.remove(word)

In [337]:
zip_code ="20020"

apts_20020_df = pd.DataFrame(apartments_20020)
apts_20020_df['also_price'] = apts_20020_df['also_price'].str[:-4]
apts_20020_df["Zip Code"] = zip_code
apts_20020_df

,address,price_monthly,also_price,sqft,Zip Code
0,"2333 Skyland Pl SE #360-0605, Washington, DC 2...","$1,145/mo",,575 sqft,20020
1,"2633-2645 Naylor Rd SE #2633-0T2, Washington, ...","$1,225/mo",,715 sqft,20020
2,"2139 Suitland Ter SE APT 101, Washington, DC 2...","$1,375/mo",,625 sqft,20020
3,"2110 38th St SE APT 301, Washington, DC 20020","$1,450/mo",,640 sqft,20020
4,"1501 27th St SE APT 102, Washington, DC 20020","$1,150/mo",,650 sqft,20020
5,"3111 Naylor Rd SE APT 104, Washington, DC 20020","$1,100/mo",,654 sqft,20020
6,"3937 S St SE APT 207, Washington, DC 20020","$1,300/mo",,635 sqft,20020
7,"2345 Green St SE #3, Washington, DC 20020","$1,025/mo",,-- sqft,20020
8,"(undisclosed Address), Washington, DC 20020","$1,250/mo",,-- sqft,20020
9,"2337 Green St SE #2345-3, Washington, DC 20020",$975/mo,,-- sqft,20020
10,Parkway Overlook Apartments | 2841 Robinson Pl...,None,"$1,070+",None,20020
11,"2612 29th St SE #4, Washington, DC 20020","$1,350/mo",,"3,024 sqft",20020
12,"1831 P St SE #32I, Washington, DC 20020",$895/mo,,550 sqft,20020
13,"2106 38th St SE APT 102, Washington, DC 20020","$1,375/mo",,625 sqft,20020
14,"Oxford Manor | 2607 Bowen Rd SE, Washington, DC",None,"$1,200+",None,20020
15,"1812 23rd St SE #2308260, Washington, DC 20020","$1,195+/mo",,650 sqft,20020

In [338]:
#20019

apartments_20019 = []

In [339]:
url = 'https://www.zillow.com/washington-dc-20019/apartments/1-bedrooms/'
browser.visit(url)

In [340]:
html = browser.html
soup = bs(html,'html.parser')

In [341]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20019.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Meadow Green Courts | 3539 A St SE, Washington, DC
None
$1,223+ 1 bd
None
-------------
2928 K St SE #2, Washington, DC 20019
<div class="list-card-price">$1,423/mo</div>
1 bd
-- sqft
-------------
4221 Brooks St NE #2, Washington, DC 20019
<div class="list-card-price">$812/mo</div>
1 bd
-- sqft
-------------
5029 Hanna Pl SE, Washington, DC 20019
<div class="list-card-price">$1,350/mo</div>
1 bd
550 sqft
-------------
1221 47th Pl NE, Washington, DC
None
$1,250+ 1 bd
None
-------------
4800 C St SE APT 202, Washington, DC 20019
<div class="list-card-price">$1,400/mo</div>
1 bd
502 sqft
-------------
5222 Hayes St NE #A, Washington, DC 20019
<div class="list-card-price">$1,000/mo</div>
1 bd
810 sqft
-------------
4040 E Capitol St NE #E12, Washington, DC 20019
<div class="list-card-price">$1,200/mo</div>
1 bd
648 sqft
-------------
5045 Hanna Pl APT 1, Washington, DC 20019
<div class="list-card-price">$1,150/mo</div>
1 bd
-- sqft
-------------
640 Croissant Pl SE, Washington, DC 20019
<div class="list-card-price">$1,500/mo</div>
1 bd
600 sqft
-------------
4225 Eads St NE APT 1, Washington, DC 20019
<div class="list-card-price">$1,200/mo</div>
1 bd
595 sqft
-------------
4223 Eads St NE APT 2, Washington, DC 20019
<div class="list-card-price">$1,200/mo</div>
1 bd
595 sqft
-------------
515 59th St NE APT A, Washington, DC 20019
<div class="list-card-price">$1,290/mo</div>
1 bd
710 sqft
-------------
4916 Nash St NE #6, Washington, DC 20019
<div class="list-card-price">$1,175/mo</div>
1 bd
-- sqft
-------------
(undisclosed Address), Washington, DC 20019
<div class="list-card-price">$1,700/mo</div>
1 bd
684 sqft
-------------
4724 Benning Rd SE APT 302, Washington, DC 20019
<div class="list-card-price">$1,350/mo</div>
1 bd
624 sqft
-------------
944 Eastern Ave NE APT 2, Washington, DC 20019
<div class="list-card-price">$1,299/mo</div>
1 bd
600 sqft
-------------
5210 E St SE APT 14, Washington, DC 20019
<div class="list-card-price">$1,250/mo</div>
1 bd
-- sqft
-------------
4202 Grant St NE, Washington, DC 20019
<div class="list-card-price">$1,200/mo</div>
1 bd
650 sqft
-------------
4929 Foote St NE APT 9, Washington, DC 20019
<div class="list-card-price">$1,250/mo</div>
1 bd
718 sqft
-------------
4662 Hillside Rd SE, Washington, DC 20019
<div class="list-card-price">$1,287/mo</div>
1 bd
2,444 sqft

In [342]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20019): 
    if word in stopwords:
        words.remove(word)

In [343]:
zip_code ="20019"

apts_20019_df = pd.DataFrame(apartments_20019)
apts_20019_df['also_price'] = apts_20019_df['also_price'].str[:-4]
apts_20019_df["Zip Code"] = zip_code
apts_20019_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Meadow Green Courts | 3539 A St SE, Washington...",None,"$1,223+",None,20019
1,"2928 K St SE #2, Washington, DC 20019","$1,423/mo",,-- sqft,20019
2,"4221 Brooks St NE #2, Washington, DC 20019",$812/mo,,-- sqft,20019
3,"5029 Hanna Pl SE, Washington, DC 20019","$1,350/mo",,550 sqft,20019
4,"1221 47th Pl NE, Washington, DC",None,"$1,250+",None,20019
5,"4800 C St SE APT 202, Washington, DC 20019","$1,400/mo",,502 sqft,20019
6,"5222 Hayes St NE #A, Washington, DC 20019","$1,000/mo",,810 sqft,20019
7,"4040 E Capitol St NE #E12, Washington, DC 20019","$1,200/mo",,648 sqft,20019
8,"5045 Hanna Pl APT 1, Washington, DC 20019","$1,150/mo",,-- sqft,20019
9,"640 Croissant Pl SE, Washington, DC 20019","$1,500/mo",,600 sqft,20019
10,"4225 Eads St NE APT 1, Washington, DC 20019","$1,200/mo",,595 sqft,20019
11,"4223 Eads St NE APT 2, Washington, DC 20019","$1,200/mo",,595 sqft,20019
12,"515 59th St NE APT A, Washington, DC 20019","$1,290/mo",,710 sqft,20019
13,"4916 Nash St NE #6, Washington, DC 20019","$1,175/mo",,-- sqft,20019
14,"(undisclosed Address), Washington, DC 20019","$1,700/mo",,684 sqft,20019
15,"4724 Benning Rd SE APT 302, Washington, DC 20019","$1,350/mo",,624 sqft,20019
16,"944 Eastern Ave NE APT 2, Washington, DC 20019","$1,299/mo",,600 sqft,20019
17,"5210 E St SE APT 14, Washington, DC 20019","$1,250/mo",,-- sqft,20019
18,"4202 Grant St NE, Washington, DC 20019","$1,200/mo",,650 sqft,20019
19,"4929 Foote St NE APT 9, Washington, DC 20019","$1,250/mo",,718 sqft,20019
20,"4662 Hillside Rd SE, Washington, DC 20019","$1,287/mo",,"2,444 sqft",20019

In [344]:
#20018

apartments_20018 = []

In [345]:
url = 'https://www.zillow.com/washington-dc-20018/apartments/1-bedrooms/'
browser.visit(url)

In [346]:
html = browser.html
soup = bs(html,'html.parser')

In [347]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20018.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Rhode Island Row | 2300 Washington Pl NE, Washington, DC
None
$1,817+ 1 bd
None
-------------
Brookland Press | 806 Channing Pl NE, Washington, DC
None
$1,525+ 1 bd
None
-------------
The Jamison | 3750 Jamison St NE, Washington, DC
None
$1,917+ 1 bd
None
-------------
1511 Franklin St NE #T4, Washington, DC 20018
<div class="list-card-price">$1,300/mo</div>
1 bd
650 sqft
-------------
Carrolton II | 1625 Franklin St NE, Washington, DC
None
$1,300+ 1 bd
None
-------------
1330 Downing Pl NE APT 3, Washington, DC 20018
<div class="list-card-price">$1,500/mo</div>
1 bd
700 sqft
-------------
1800 Shepherd St NE #101, Washington, DC 20018
<div class="list-card-price">$1,829/mo</div>
1 bd
785 sqft
-------------
1904 Irving St NE #204, Washington, DC 20018
<div class="list-card-price">$1,545/mo</div>
1 bd
-- sqft
-------------
1328 Adams St NE APT 3, Washington, DC 20018
<div class="list-card-price">$1,595/mo</div>
1 bd
770 sqft
-------------
1380 Bryant St NE APT 203, Washington, DC 20018
<div class="list-card-price">$1,395/mo</div>
1 bd
800 sqft
-------------
(undisclosed Address), Washington, DC 20018
<div class="list-card-price">$1,475/mo</div>
1 bd
680 sqft
-------------
911 Evarts St NE, Washington, DC
None
$1,600+ 1 bd
None
-------------
1615 Franklin St NE #202, Washington, DC 20018
<div class="list-card-price">$1,275/mo</div>
1 bd
721 sqft
-------------
1390 Bryant St NE APT 304, Washington, DC 20018
<div class="list-card-price">$1,500/mo</div>
1 bd
700 sqft

In [348]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20018): 
    if word in stopwords:
        words.remove(word)

In [349]:
zip_code ="20018"

apts_20018_df = pd.DataFrame(apartments_20018)
apts_20018_df['also_price'] = apts_20018_df['also_price'].str[:-4]
apts_20018_df["Zip Code"] = zip_code
apts_20018_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Rhode Island Row | 2300 Washington Pl NE, Wash...",None,"$1,817+",None,20018
1,"Brookland Press | 806 Channing Pl NE, Washingt...",None,"$1,525+",None,20018
2,"The Jamison | 3750 Jamison St NE, Washington, DC",None,"$1,917+",None,20018
3,"1511 Franklin St NE #T4, Washington, DC 20018","$1,300/mo",,650 sqft,20018
4,"Carrolton II | 1625 Franklin St NE, Washington...",None,"$1,300+",None,20018
5,"1330 Downing Pl NE APT 3, Washington, DC 20018","$1,500/mo",,700 sqft,20018
6,"1800 Shepherd St NE #101, Washington, DC 20018","$1,829/mo",,785 sqft,20018
7,"1904 Irving St NE #204, Washington, DC 20018","$1,545/mo",,-- sqft,20018
8,"1328 Adams St NE APT 3, Washington, DC 20018","$1,595/mo",,770 sqft,20018
9,"1380 Bryant St NE APT 203, Washington, DC 20018","$1,395/mo",,800 sqft,20018
10,"(undisclosed Address), Washington, DC 20018","$1,475/mo",,680 sqft,20018
11,"911 Evarts St NE, Washington, DC",None,"$1,600+",None,20018
12,"1615 Franklin St NE #202, Washington, DC 20018","$1,275/mo",,721 sqft,20018
13,"1390 Bryant St NE APT 304, Washington, DC 20018","$1,500/mo",,700 sqft,20018

In [350]:
#20017

apartments_20017 = []

In [351]:
url = 'https://www.zillow.com/washington-dc-20017/apartments/1-bedrooms/'
browser.visit(url)

In [352]:
html = browser.html
soup = bs(html,'html.parser')

In [353]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20017.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Brookland Ridge Apartments | 400 Taylor St NE, Washington, DC
None
$1,480+ 1 bd
None
-------------
Monroe Street Market | 625 Monroe St NE, Washington, DC
None
$1,629+ 1 bd
None
-------------
3742 12th St NE, Washington, DC
None
$1,499+ 1 bd
None
-------------
3725 12th St NE, Washington, DC
None
$1,400+ 1 bd
None
-------------
2821 7th St NE, Washington, DC 20017
<div class="list-card-price">$1,700/mo</div>
1 bd
3,522 sqft
-------------
3911 7th St NE APT 3, Washington, DC 20017
<div class="list-card-price">$1,170/mo</div>
1 bd
-- sqft
-------------
3111 12th St NE #B, Washington, DC 20017
<div class="list-card-price">$1,295/mo</div>
1 bd
-- sqft
-------------
The Cloisters | 100 Michigan Ave NE, Washington, DC
None
$1,530+ 1 bd
None
-------------
3220 12th St NE #24, Washington, DC 20017
<div class="list-card-price">$1,299/mo</div>
1 bd
-- sqft
-------------
3230 7th St NE #B31, Washington, DC 20017
<div class="list-card-price">$1,465/mo</div>
1 bd
650 sqft
-------------
3935 9th St NE APT 4, Washington, DC 20017
<div class="list-card-price">$1,600/mo</div>
1 bd
1,100 sqft
-------------
1328 Taylor St NE, Washington, DC 20017
<div class="list-card-price">$1,575/mo</div>
1 bd
700 sqft

In [354]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20017): 
    if word in stopwords:
        words.remove(word)

In [355]:
zip_code ="20017"

apts_20017_df = pd.DataFrame(apartments_20017)
apts_20017_df['also_price'] = apts_20017_df['also_price'].str[:-4]
apts_20017_df["Zip Code"] = zip_code
apts_20017_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Brookland Ridge Apartments | 400 Taylor St NE,...",None,"$1,480+",None,20017
1,"Monroe Street Market | 625 Monroe St NE, Washi...",None,"$1,629+",None,20017
2,"3742 12th St NE, Washington, DC",None,"$1,499+",None,20017
3,"3725 12th St NE, Washington, DC",None,"$1,400+",None,20017
4,"2821 7th St NE, Washington, DC 20017","$1,700/mo",,"3,522 sqft",20017
5,"3911 7th St NE APT 3, Washington, DC 20017","$1,170/mo",,-- sqft,20017
6,"3111 12th St NE #B, Washington, DC 20017","$1,295/mo",,-- sqft,20017
7,"The Cloisters | 100 Michigan Ave NE, Washingto...",None,"$1,530+",None,20017
8,"3220 12th St NE #24, Washington, DC 20017","$1,299/mo",,-- sqft,20017
9,"3230 7th St NE #B31, Washington, DC 20017","$1,465/mo",,650 sqft,20017
10,"3935 9th St NE APT 4, Washington, DC 20017","$1,600/mo",,"1,100 sqft",20017
11,"1328 Taylor St NE, Washington, DC 20017","$1,575/mo",,700 sqft,20017

In [356]:
#20015

apartments_20015 = []

In [357]:
url = 'https://www.zillow.com/washington-dc-20015/apartments/1-bedrooms/'
browser.visit(url)

In [358]:
html = browser.html
soup = bs(html,'html.parser')

In [359]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20015.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
The Kenmore | 5415 Connecticut Ave NW, Washington, DC
None
$1,399+ 1 bd
None
-------------
5333 Connecticut | 5333 Connecticut Ave NW, Washington, DC
None
$1,724+ 1 bd
None
-------------
Roberta | 5429 Connecticut Ave NW, Washington, DC
None
$1,299+ 1 bd
None
-------------
La Reine | 5425 Connecticut Ave NW, Washington, DC
None
$1,585+ 1 bd
None
-------------
4415 Harrison St NW #BASEMENT, Washington, DC 20015
<div class="list-card-price">$1,600/mo</div>
1 bd
520 sqft
-------------
5435 Connecticut Ave NW, Washington, DC
None
$1,575+ 1 bd
None
-------------
1629 Nebraska Ave NW #L, Washington, DC 20015
<div class="list-card-price">$2,100/mo</div>
1 bd
700 sqft
-------------
Livingston | 5437 Connecticut Ave NW, Washington, DC
None
$1,598+ 1 bd
None
-------------
5410 Connecticut Ave NW, Washington, DC
None
$1,495+ 1 bd
None
-------------
5402 Connecticut Ave NW APT 505, Washington, DC 20015
<div class="list-card-price">$1,800/mo</div>
1 bd
628 sqft
-------------
5201 Wisconsin Ave NW #409, Washington, DC 20015
<div class="list-card-price">$1,600/mo</div>
1 bd
669 sqft
-------------
3719 Military Rd NW APT B, Washington, DC 20015
<div class="list-card-price">$1,600/mo</div>
1 bd
545 sqft

In [360]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20015): 
    if word in stopwords:
        words.remove(word)

In [361]:
zip_code ="20015"

apts_20015_df = pd.DataFrame(apartments_20015)
apts_20015_df['also_price'] = apts_20015_df['also_price'].str[:-4]
apts_20015_df["Zip Code"] = zip_code
apts_20015_df

,address,price_monthly,also_price,sqft,Zip Code
0,"The Kenmore | 5415 Connecticut Ave NW, Washing...",None,"$1,399+",None,20015
1,"5333 Connecticut | 5333 Connecticut Ave NW, Wa...",None,"$1,724+",None,20015
2,"Roberta | 5429 Connecticut Ave NW, Washington, DC",None,"$1,299+",None,20015
3,"La Reine | 5425 Connecticut Ave NW, Washington...",None,"$1,585+",None,20015
4,"4415 Harrison St NW #BASEMENT, Washington, DC ...","$1,600/mo",,520 sqft,20015
5,"5435 Connecticut Ave NW, Washington, DC",None,"$1,575+",None,20015
6,"1629 Nebraska Ave NW #L, Washington, DC 20015","$2,100/mo",,700 sqft,20015
7,"Livingston | 5437 Connecticut Ave NW, Washingt...",None,"$1,598+",None,20015
8,"5410 Connecticut Ave NW, Washington, DC",None,"$1,495+",None,20015
9,"5402 Connecticut Ave NW APT 505, Washington, D...","$1,800/mo",,628 sqft,20015
10,"5201 Wisconsin Ave NW #409, Washington, DC 20015","$1,600/mo",,669 sqft,20015
11,"3719 Military Rd NW APT B, Washington, DC 20015","$1,600/mo",,545 sqft,20015

In [362]:
#20016

apartments_20016 = []

In [363]:
url = 'https://www.zillow.com/washington-dc-20016/apartments/1-bedrooms/'
browser.visit(url)

In [364]:
html = browser.html
soup = bs(html,'html.parser')

In [365]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_20016.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Cathedral Commons | 3401 Idaho Ave NW, Washington, DC
None
$2,239+ 1 bd
None
-------------
Avalon at Foxhall | 4100 Massachusetts Ave NW, Washington, DC
None
$1,727+ 1 bd
None
-------------
3511 39th St NW APT D490, Washington, DC 20016
<div class="list-card-price">$1,895/mo</div>
1 bd
707 sqft
-------------
The Fleetwood | 3707 Woodley Rd NW, Washington, DC
None
$1,395+ 1 bd
None
-------------
Vaughan Place | 3401 38th St NW, Washington, DC
None
$1,771+ 1 bd
None
-------------
Alban Towers | 3700 Massachusetts Ave NW, Washington, DC
None
$2,045+ 1 bd
None
-------------
Tenley View Apartments | 4600 Wisconsin Ave NW, Washington, DC
None
$1,799+ 1 bd
None
-------------
4000-4013 47th St NW #1B, Washington, DC 20016
<div class="list-card-price">$2,400+/mo</div>
1 bd
-- sqft
-------------
Macomb Gardens | 3725 Macomb St NW, Washington, DC
None
$1,645+ 1 bd
None
-------------
4000 Massachusetts Ave NW #776920538, Washington, DC 20016
<div class="list-card-price">$1,900+/mo</div>
1 bd
900 sqft
-------------
The Devonshire Court South Apartment | 4105 Wisconsin Ave NW, Washington, DC
None
$1,225+ 1 bd
None
-------------
Adams-View | 3201 Wisconsin Ave NW, Washington, DC
None
$1,650+ 1 bd
None
-------------
Archer Apartments | 3701 Massachusetts Ave NW, Washington, DC
None
$1,950+ 1 bd
None
-------------
3900 Cathedral Ave NW APT 301A, Washington, DC 20016
<div class="list-card-price">$2,300/mo</div>
1 bd
1,050 sqft
-------------
3601 Wisconsin Ave NW APT 110, Washington, DC 20016
<div class="list-card-price">$1,675/mo</div>
1 bd
707 sqft
-------------
3014 New Mexico Ave NW, Washington, DC 20016
<div class="list-card-price">$2,950/mo</div>
1 bd
600 sqft
-------------
Alto Towers | 3206 Wisconsin Ave NW, Washington, DC
None
$1,650+ 1 bd
None
-------------
3010 Wisconsin Ave NW APT 205, Washington, DC 20016
<div class="list-card-price">$1,700/mo</div>
1 bd
595 sqft
-------------
3101 New Mexico Ave NW, Washington, DC
None
$2,490+ 1 bd
None
-------------
4201 Cathedral Ave NW, Washington, DC
None
$1,595+ 1 bd
None
-------------
3026 Wisconsin Ave NW, Washington, DC
None
$1,495+ 1 bd
None
-------------
4943 Albemarle St NW, Washington, DC 20016
<div class="list-card-price">$1,600/mo</div>
1 bd
400 sqft
-------------
3770 39th St NW APT D136, Washington, DC 20016
<div class="list-card-price">$1,700/mo</div>
1 bd
520 sqft
-------------
The Berkshire | 4201 Mass Ave NW, Washington, DC
None
$1,699+ 1 bd
None
-------------
3609 38th St NW #343, Washington, DC 20016
<div class="list-card-price">$1,500/mo</div>
1 bd
424 sqft
-------------
Idaho Terrace | 3040 Idaho Ave NW, Washington, DC
None
$1,733+ 1 bd
None
-------------
4114 Chesapeake St NW, Washington, DC 20016
<div class="list-card-price">$1,800/mo</div>
1 bd
800 sqft
-------------
4101 Albemarle St NW, Washington, DC
None
$1,850+ 1 bd
None
-------------
4115 Wisconsin | 4115 Wisconsin Ave NW, Washington, DC
None
$1,608+ 1 bd
None
-------------
5112 Macarthur Blvd NW APT 110, Washington, DC 20016
<div class="list-card-price">$1,825/mo</div>
1 bd
724 sqft
-------------
3401-3420 38th St NW #724, Washington, DC 20016
<div class="list-card-price">$2,500/mo</div>
1 bd
620 sqft
-------------
3401 38th St NW, Washington, DC
None
$1,600+ 1 bd
None
-------------
3410 39th St NW APT C711, Washington, DC 20016
<div class="list-card-price">$1,950/mo</div>
1 bd
746 sqft
-------------
4301 Massachusetts Ave NW APT 6007, Washington, DC 20016
<div class="list-card-price">$2,000/mo</div>
1 bd
956 sqft
-------------
3901 Cathedral Ave NW #620, Washington, DC 20016
<div class="list-card-price">$1,600/mo</div>
1 bd
765 sqft
-------------
3855 Rodman St NW APT F48, Washington, DC 20016
<div class="list-card-price">$2,950/mo</div>
1 bd
1,189 sqft
-------------
The Elaine | 3210 Wisconsin Ave NW, Washington, DC
None
$1,695+ 1 bd
None
-------------
3051 Idaho Ave NW APT 124, Washington, DC 20016
<div class="list-card-price">$1,800/mo</div>
1 bd
638 sqft
-------------
3100 Wisconsin Ave NW APT 202, Washington, DC 20016
<div class="list-card-price">$2,450/mo</div>
1 bd
783 sqft
-------------
3218 Wisconsin Ave NW APT 201, Washington, DC 20016
<div class="list-card-price">$1,600/mo</div>
1 bd
425 sqft

In [366]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_20016): 
    if word in stopwords:
        words.remove(word)

In [367]:
zip_code ="20016"

apts_20016_df = pd.DataFrame(apartments_20016)
apts_20016_df['also_price'] = apts_20016_df['also_price'].str[:-4]
apts_20016_df["Zip Code"] = zip_code
apts_20016_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Cathedral Commons | 3401 Idaho Ave NW, Washing...",None,"$2,239+",None,20016
1,"Avalon at Foxhall | 4100 Massachusetts Ave NW,...",None,"$1,727+",None,20016
2,"3511 39th St NW APT D490, Washington, DC 20016","$1,895/mo",,707 sqft,20016
3,"The Fleetwood | 3707 Woodley Rd NW, Washington...",None,"$1,395+",None,20016
4,"Vaughan Place | 3401 38th St NW, Washington, DC",None,"$1,771+",None,20016
5,"Alban Towers | 3700 Massachusetts Ave NW, Wash...",None,"$2,045+",None,20016
6,Tenley View Apartments | 4600 Wisconsin Ave NW...,None,"$1,799+",None,20016
7,"4000-4013 47th St NW #1B, Washington, DC 20016","$2,400+/mo",,-- sqft,20016
8,"Macomb Gardens | 3725 Macomb St NW, Washington...",None,"$1,645+",None,20016
9,"4000 Massachusetts Ave NW #776920538, Washingt...","$1,900+/mo",,900 sqft,20016
10,The Devonshire Court South Apartment | 4105 Wi...,None,"$1,225+",None,20016
11,"Adams-View | 3201 Wisconsin Ave NW, Washington...",None,"$1,650+",None,20016
12,"Archer Apartments | 3701 Massachusetts Ave NW,...",None,"$1,950+",None,20016
13,"3900 Cathedral Ave NW APT 301A, Washington, DC...","$2,300/mo",,"1,050 sqft",20016
14,"3601 Wisconsin Ave NW APT 110, Washington, DC ...","$1,675/mo",,707 sqft,20016
15,"3014 New Mexico Ave NW, Washington, DC 20016","$2,950/mo",,600 sqft,20016
16,"Alto Towers | 3206 Wisconsin Ave NW, Washingto...",None,"$1,650+",None,20016
17,"3010 Wisconsin Ave NW APT 205, Washington, DC ...","$1,700/mo",,595 sqft,20016
18,"3101 New Mexico Ave NW, Washington, DC",None,"$2,490+",None,20016
19,"4201 Cathedral Ave NW, Washington, DC",None,"$1,595+",None,20016
20,"3026 Wisconsin Ave NW, Washington, DC",None,"$1,495+",None,20016
21,"4943 Albemarle St NW, Washington, DC 20016","$1,600/mo",,400 sqft,20016
22,"3770 39th St NW APT D136, Washington, DC 20016","$1,700/mo",,520 sqft,20016
23,"The Berkshire | 4201 Mass Ave NW, Washington, DC",None,"$1,699+",None,20016
24,"3609 38th St NW #343, Washington, DC 20016","$1,500/mo",,424 sqft,20016
25,"Idaho Terrace | 3040 Idaho Ave NW, Washington, DC",None,"$1,733+",None,20016
26,"4114 Chesapeake St NW, Washington, DC 20016","$1,800/mo",,800 sqft,20016
27,"4101 Albemarle St NW, Washington, DC",None,"$1,850+",None,20016
28,"4115 Wisconsin | 4115 Wisconsin Ave NW, Washin...",None,"$1,608+",None,20016
29,"5112 Macarthur Blvd NW APT 110, Washington, DC...","$1,825/mo",,724 sqft,20016
30,"3401-3420 38th St NW #724, Washington, DC 20016","$2,500/mo",,620 sqft,20016
31,"3401 38th St NW, Washington, DC",None,"$1,600+",None,20016
32,"3410 39th St NW APT C711, Washington, DC 20016","$1,950/mo",,746 sqft,20016
33,"4301 Massachusetts Ave NW APT 6007, Washington...","$2,000/mo",,956 sqft,20016
34,"3901 Cathedral Ave NW #620, Washington, DC 20016","$1,600/mo",,765 sqft,20016
35,"3855 Rodman St NW APT F48, Washington, DC 20016","$2,950/mo",,"1,189 sqft",20016
36,"The Elaine | 3210 Wisconsin Ave NW, Washington...",None,"$1,695+",None,20016
37,"3051 Idaho Ave NW APT 124, Washington, DC 20016","$1,800/mo",,638 sqft,20016
38,"3100 Wisconsin Ave NW APT 202, Washington, DC ...","$2,450/mo",,783 sqft,20016
39,"3218 Wisconsin Ave NW APT 201, Washington, DC ...","$1,600/mo",,425 sqft,20016

In [368]:
#22302

apartments_22302 = []

In [369]:
url = 'https://www.zillow.com/alexandria-va-22302/apartments/1-bedrooms/'
browser.visit(url)

In [370]:
html = browser.html
soup = bs(html,'html.parser')

In [371]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22302.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Array at West Alex | 3445 Berkeley St, Alexandria, VA
None
$1,650+ 1 bd
None
-------------
e-lofts | 4501 Ford Ave, Alexandria, VA
None
$1,643+ 1 bd
None
-------------
Newport Village | 4757 W Braddock Rd, Alexandria, VA
None
$1,260+ 1 bd
None
-------------
Halstead Tower by Windsor | 4380 King St, Alexandria, VA
None
$1,690+ 1 bd
None
-------------
Braddock Lee Apartments | 2423 Menokin Dr, Alexandria, VA
None
$1,390+ 1 bd
None
-------------
Arrive 2801 | 2801 Park Center Dr, Alexandria, VA
None
$1,435+ 1 bd
None
-------------
3304 Wyndham Cir, Alexandria, VA
None
$1,495+ 1 bd
None
-------------
3336 Martha Custis Dr, Alexandria, VA 22302
<div class="list-card-price">$1,695/mo</div>
1 bd
780 sqft
-------------
3436 Martha Custis Dr, Alexandria, VA
None
$1,790+ 1 bd
None
-------------
3303 Wyndham Cir APT 142, Alexandria, VA 22302
<div class="list-card-price">$1,530/mo</div>
1 bd
736 sqft
-------------
3307 Wyndham Cir APT 4166, Alexandria, VA 22302
<div class="list-card-price">$1,525/mo</div>
1 bd
648 sqft
-------------
1225 Martha Custis Dr, Alexandria, VA
None
$1,200+ 1 bd
None
-------------
4520 King St APT 803, Alexandria, VA 22302
<div class="list-card-price">$1,550/mo</div>
1 bd
756 sqft
-------------
3101 N Hampton Dr APT 316, Alexandria, VA 22302
<div class="list-card-price">$1,600/mo</div>
1 bd
704 sqft
-------------
2500 N Van Dorn St PENTHOUSE 10, Alexandria, VA 22302
<div class="list-card-price">$1,575/mo</div>
1 bd
567 sqft
-------------
3310 Wyndham Cir APT 109, Alexandria, VA 22302
<div class="list-card-price">$1,600/mo</div>
1 bd
735 sqft
-------------
3210 S 28th St APT 304, Alexandria, VA 22302
<div class="list-card-price">$1,350/mo</div>
1 bd
700 sqft
-------------
3311 Wyndham Cir APT 2200, Alexandria, VA 22302
<div class="list-card-price">$1,590/mo</div>
1 bd
826 sqft

In [372]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22302): 
    if word in stopwords:
        words.remove(word)

In [373]:
zip_code ="22302"

apts_22302_df = pd.DataFrame(apartments_22302)
apts_22302_df['also_price'] = apts_22302_df['also_price'].str[:-4]
apts_22302_df["Zip Code"] = zip_code
apts_22302_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Array at West Alex | 3445 Berkeley St, Alexand...",None,"$1,650+",None,22302
1,"e-lofts | 4501 Ford Ave, Alexandria, VA",None,"$1,643+",None,22302
2,"Newport Village | 4757 W Braddock Rd, Alexandr...",None,"$1,260+",None,22302
3,"Halstead Tower by Windsor | 4380 King St, Alex...",None,"$1,690+",None,22302
4,"Braddock Lee Apartments | 2423 Menokin Dr, Ale...",None,"$1,390+",None,22302
5,"Arrive 2801 | 2801 Park Center Dr, Alexandria, VA",None,"$1,435+",None,22302
6,"3304 Wyndham Cir, Alexandria, VA",None,"$1,495+",None,22302
7,"3336 Martha Custis Dr, Alexandria, VA 22302","$1,695/mo",,780 sqft,22302
8,"3436 Martha Custis Dr, Alexandria, VA",None,"$1,790+",None,22302
9,"3303 Wyndham Cir APT 142, Alexandria, VA 22302","$1,530/mo",,736 sqft,22302
10,"3307 Wyndham Cir APT 4166, Alexandria, VA 22302","$1,525/mo",,648 sqft,22302
11,"1225 Martha Custis Dr, Alexandria, VA",None,"$1,200+",None,22302
12,"4520 King St APT 803, Alexandria, VA 22302","$1,550/mo",,756 sqft,22302
13,"3101 N Hampton Dr APT 316, Alexandria, VA 22302","$1,600/mo",,704 sqft,22302
14,"2500 N Van Dorn St PENTHOUSE 10, Alexandria, V...","$1,575/mo",,567 sqft,22302
15,"3310 Wyndham Cir APT 109, Alexandria, VA 22302","$1,600/mo",,735 sqft,22302
16,"3210 S 28th St APT 304, Alexandria, VA 22302","$1,350/mo",,700 sqft,22302
17,"3311 Wyndham Cir APT 2200, Alexandria, VA 22302","$1,590/mo",,826 sqft,22302

In [374]:
#22301

apartments_22301 = []

In [375]:
url = 'https://www.zillow.com/alexandria-va-22301/apartments/1-bedrooms/'
browser.visit(url)

In [376]:
html = browser.html
soup = bs(html,'html.parser')

In [377]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22301.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Notch 8 | 2900 Main Line Blvd, Alexandria, VA
None
$1,431+ 1 bd
None
-------------
The Porter Del Ray | 625 E Monroe Ave, Alexandria, VA
None
$1,853+ 1 bd
None
-------------
The Frasier | 615 Swann Ave, Alexandria, VA
None
$1,672+ 1 bd
None
-------------
Station 650 | 650 Potomac Ave, Alexandria, VA
None
$1,678+ 1 bd
None
-------------
The Gardens at Del Ray | 4 E Cliff St, Alexandria, VA
None
$1,600+ 1 bd
None
-------------
Commonwealth Crossing | 1710 Commonwealth Ave, Alexandria, VA
None
$1,299+ 1 bd
None
-------------
Manor House Apartments | 6 E Nelson Ave, Alexandria, VA
None
$1,595+ 1 bd
None
-------------
5 E Mason Ave #C0ZAWXQXU, Alexandria, VA 22301
<div class="list-card-price">$1,350+/mo</div>
1 bd
750 sqft
-------------
8 E Monroe Ave #5MMK4BUVC, Alexandria, VA 22301
<div class="list-card-price">$1,300+/mo</div>
1 bd
700 sqft
-------------
Linden at Del Ray | 415 E Bellefonte Ave, Alexandria, VA
None
$1,525+ 1 bd
None
-------------
304 E Duncan Ave, Alexandria, VA 22301
<div class="list-card-price">$1,475/mo</div>
1 bd
430 sqft
-------------
650 Maskell St #KAGK91151, Alexandria, VA 22301
<div class="list-card-price">$1,763+/mo</div>
1 bd
726 sqft
-------------
104 Stewart Ave APT 4, Alexandria, VA 22301
<div class="list-card-price">$1,575/mo</div>
1 bd
675 sqft
-------------
1707 Dewitt Ave APT F, Alexandria, VA 22301
<div class="list-card-price">$1,550/mo</div>
1 bd
437 sqft
-------------
2406 Clyde Ave #4, Alexandria, VA 22301
<div class="list-card-price">$1,625/mo</div>
1 bd
800 sqft
-------------
210 E Windsor Ave #4, Alexandria, VA 22301
<div class="list-card-price">$1,600/mo</div>
1 bd
4,922 sqft
-------------
1800 Mount Vernon Ave APT 209, Alexandria, VA 22301
<div class="list-card-price">$1,800/mo</div>
1 bd
650 sqft
-------------
401 Commonwealth Ave APT 10A, Alexandria, VA 22301
<div class="list-card-price">$1,790/mo</div>
1 bd
900 sqft
-------------
12 Sunset Dr #5B, Alexandria, VA 22301
<div class="list-card-price">$1,750/mo</div>
1 bd
670 sqft
-------------
513 E Custis Ave APT 2, Alexandria, VA 22301
<div class="list-card-price">$1,100/mo</div>
1 bd
325 sqft
-------------
306 Adams Ave #302, Alexandria, VA 22301
<div class="list-card-price">$1,499/mo</div>
1 bd
665 sqft

In [378]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22301): 
    if word in stopwords:
        words.remove(word)

In [379]:
zip_code ="22301"

apts_22301_df = pd.DataFrame(apartments_22301)
apts_22301_df['also_price'] = apts_22301_df['also_price'].str[:-4]
apts_22301_df["Zip Code"] = zip_code
apts_22301_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Notch 8 | 2900 Main Line Blvd, Alexandria, VA",None,"$1,431+",None,22301
1,"The Porter Del Ray | 625 E Monroe Ave, Alexand...",None,"$1,853+",None,22301
2,"The Frasier | 615 Swann Ave, Alexandria, VA",None,"$1,672+",None,22301
3,"Station 650 | 650 Potomac Ave, Alexandria, VA",None,"$1,678+",None,22301
4,"The Gardens at Del Ray | 4 E Cliff St, Alexand...",None,"$1,600+",None,22301
5,"Commonwealth Crossing | 1710 Commonwealth Ave,...",None,"$1,299+",None,22301
6,"Manor House Apartments | 6 E Nelson Ave, Alexa...",None,"$1,595+",None,22301
7,"5 E Mason Ave #C0ZAWXQXU, Alexandria, VA 22301","$1,350+/mo",,750 sqft,22301
8,"8 E Monroe Ave #5MMK4BUVC, Alexandria, VA 22301","$1,300+/mo",,700 sqft,22301
9,"Linden at Del Ray | 415 E Bellefonte Ave, Alex...",None,"$1,525+",None,22301
10,"304 E Duncan Ave, Alexandria, VA 22301","$1,475/mo",,430 sqft,22301
11,"650 Maskell St #KAGK91151, Alexandria, VA 22301","$1,763+/mo",,726 sqft,22301
12,"104 Stewart Ave APT 4, Alexandria, VA 22301","$1,575/mo",,675 sqft,22301
13,"1707 Dewitt Ave APT F, Alexandria, VA 22301","$1,550/mo",,437 sqft,22301
14,"2406 Clyde Ave #4, Alexandria, VA 22301","$1,625/mo",,800 sqft,22301
15,"210 E Windsor Ave #4, Alexandria, VA 22301","$1,600/mo",,"4,922 sqft",22301
16,"1800 Mount Vernon Ave APT 209, Alexandria, VA ...","$1,800/mo",,650 sqft,22301
17,"401 Commonwealth Ave APT 10A, Alexandria, VA 2...","$1,790/mo",,900 sqft,22301
18,"12 Sunset Dr #5B, Alexandria, VA 22301","$1,750/mo",,670 sqft,22301
19,"513 E Custis Ave APT 2, Alexandria, VA 22301","$1,100/mo",,325 sqft,22301
20,"306 Adams Ave #302, Alexandria, VA 22301","$1,499/mo",,665 sqft,22301

In [380]:
#22305

apartments_22305 = []

In [381]:
url = 'https://www.zillow.com/alexandria-va-22305/apartments/1-bedrooms/'
browser.visit(url)

In [382]:
html = browser.html
soup = bs(html,'html.parser')

In [383]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22305.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Reserve at Potomac Yard | 3700 Richmond Hwy, Alexandria, VA
None
$1,354+ 1 bd
None
-------------
3051 Mount Vernon Ave UNIT S225, Alexandria, VA 22305
<div class="list-card-price">$1,760/mo</div>
1 bd
681 sqft
-------------
Del Ray Central | 3051 Mount Vernon Ave, Alexandria, VA
None
$1,706+ 1 bd
None
-------------
Avalon Potomac Yard | 731 Seaton Ave, Alexandria, VA
None
$1,421+ 1 bd
None
-------------
DelRay Tower | 3110 Mount Vernon Ave, Alexandria, VA
None
$1,394+ 1 bd
None
-------------
Park Vue of Alexandria | 511 Four Mile Rd, Alexandria, VA
None
$1,344+ 1 bd
None
-------------
Presidential Greens | 3904 Executive Ave, Alexandria, VA
None
$1,080+ 1 bd
None
-------------
Lloyd Apartments | 800 Tennessee Ave, Alexandria, VA
None
$1,259+ 1 bd
None
-------------
11 E Glebe Rd APT C, Alexandria, VA 22305
<div class="list-card-price">$1,365/mo</div>
1 bd
600 sqft
-------------
The Aspen | 3201 Landover St, Alexandria, VA
None
$1,564+ 1 bd
None
-------------
7-3 One Seaton Ave #505, Alexandria, VA 22305
<div class="list-card-price">$2,273/mo</div>
1 bd
842 sqft
-------------
602 Notabene Dr #10, Alexandria, VA 22305
<div class="list-card-price">$1,299/mo</div>
1 bd
7,038 sqft
-------------
16 Ashby St APT D, Alexandria, VA 22305
<div class="list-card-price">$1,750/mo</div>
1 bd
700 sqft
-------------
3102 Commonwealth Ave, Alexandria, VA 22305
<div class="list-card-price">$1,495/mo</div>
1 bd
670 sqft
-------------
181 E Reed Ave APT 403, Alexandria, VA 22305
<div class="list-card-price">$2,250/mo</div>
1 bd
908 sqft

In [384]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22305): 
    if word in stopwords:
        words.remove(word)

In [385]:
zip_code ="22305"

apts_22305_df = pd.DataFrame(apartments_22305)
apts_22305_df['also_price'] = apts_22305_df['also_price'].str[:-4]
apts_22305_df["Zip Code"] = zip_code
apts_22305_df

,address,price_monthly,also_price,sqft,Zip Code
0,"Reserve at Potomac Yard | 3700 Richmond Hwy, A...",None,"$1,354+",None,22305
1,"3051 Mount Vernon Ave UNIT S225, Alexandria, V...","$1,760/mo",,681 sqft,22305
2,"Del Ray Central | 3051 Mount Vernon Ave, Alexa...",None,"$1,706+",None,22305
3,"Avalon Potomac Yard | 731 Seaton Ave, Alexandr...",None,"$1,421+",None,22305
4,"DelRay Tower | 3110 Mount Vernon Ave, Alexandr...",None,"$1,394+",None,22305
5,"Park Vue of Alexandria | 511 Four Mile Rd, Ale...",None,"$1,344+",None,22305
6,"Presidential Greens | 3904 Executive Ave, Alex...",None,"$1,080+",None,22305
7,"Lloyd Apartments | 800 Tennessee Ave, Alexandr...",None,"$1,259+",None,22305
8,"11 E Glebe Rd APT C, Alexandria, VA 22305","$1,365/mo",,600 sqft,22305
9,"The Aspen | 3201 Landover St, Alexandria, VA",None,"$1,564+",None,22305
10,"7-3 One Seaton Ave #505, Alexandria, VA 22305","$2,273/mo",,842 sqft,22305
11,"602 Notabene Dr #10, Alexandria, VA 22305","$1,299/mo",,"7,038 sqft",22305
12,"16 Ashby St APT D, Alexandria, VA 22305","$1,750/mo",,700 sqft,22305
13,"3102 Commonwealth Ave, Alexandria, VA 22305","$1,495/mo",,670 sqft,22305
14,"181 E Reed Ave APT 403, Alexandria, VA 22305","$2,250/mo",,908 sqft,22305

In [386]:
#22206

apartments_22206 = []

In [387]:
url = 'https://www.zillow.com/arlington-va-22206/apartments/1-bedrooms/'
browser.visit(url)

In [388]:
html = browser.html
soup = bs(html,'html.parser')

In [389]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22206.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
IO Piazza by Windsor | 2727 S Quincy St, Arlington, VA
None
$1,975+ 1 bd
None
-------------
Delancey at Shirlington Village | 4220 Campbell Ave, Arlington, VA
None
$1,617+ 1 bd
None
-------------
Avalon at Arlington Square | 2350 26th Ct S, Arlington, VA
None
$1,354+ 1 bd
None
-------------
The Citizen at Shirlington Village | 3000 S Randolph St, Arlington, VA
None
$1,495+ 1 bd
None
-------------
3462 S Stafford St APT A2, Arlington, VA 22206
<div class="list-card-price">$2,595/mo</div>
1 bd
1,495 sqft
-------------
Bell Arlington Ridge | 2400 24th Rd S, Arlington, VA
None
$1,471+ 1 bd
None
-------------
4510 31st St S APT 104, Arlington, VA 22206
<div class="list-card-price">$1,524/mo</div>
1 bd
680 sqft
-------------
Shirlington House | 4201 31st St S, Arlington, VA
None
$1,424+ 1 bd
None
-------------
Alister Arlington Ridge | 2400 S Glebe Rd, Arlington, VA
None
$1,376+ 1 bd
None
-------------
4552 28th Rd S UNIT B, Arlington, VA 22206
<div class="list-card-price">$1,650/mo</div>
1 bd
673 sqft
-------------
2465 Army Navy Dr #1-404, Arlington, VA 22206
<div class="list-card-price">$1,600/mo</div>
1 bd
701 sqft
-------------
4817 31st St S APT B1, Arlington, VA 22206
<div class="list-card-price">$1,650/mo</div>
1 bd
767 sqft
-------------
Dolley Madison Towers | 2300 S 24th Rd, Arlington, VA
None
$1,495+ 1 bd
None
-------------
4317 36th St S APT B1, Arlington, VA 22206
<div class="list-card-price">$1,600/mo</div>
1 bd
711 sqft
-------------
(undisclosed Address), Arlington, VA 22206
<div class="list-card-price">$1,495/mo</div>
1 bd
700 sqft
-------------
4862 28th St S APT B1, Arlington, VA 22206
<div class="list-card-price">$1,485/mo</div>
1 bd
711 sqft
-------------
4550 28th Rd S #16, Arlington, VA 22206
<div class="list-card-price">$1,575/mo</div>
1 bd
673 sqft
-------------
3074 S Abingdon St APT C2, Arlington, VA 22206
<div class="list-card-price">$1,750/mo</div>
1 bd
1,008 sqft
-------------
3441 S Stafford St APT B2, Arlington, VA 22206
<div class="list-card-price">$1,725/mo</div>
1 bd
711 sqft
-------------
The Park at Arlington Ridge | 1800 26th St S, Arlington, VA
None
$1,358+ 1 bd
None
-------------
2321 25th St S APT 107, Arlington, VA 22206
<div class="list-card-price">$2,000/mo</div>
1 bd
800 sqft
-------------
2923 E South Woodley St #1, Arlington, VA 22206
<div class="list-card-price">$1,590/mo</div>
1 bd
613 sqft
-------------
4415 36th St S APT B1, Arlington, VA 22206
<div class="list-card-price">$1,900/mo</div>
1 bd
840 sqft
-------------
2802 S Columbus St APT C2, Arlington, VA 22206
<div class="list-card-price">$1,400/mo</div>
1 bd
711 sqft
-------------
2874 S Abingdon St APT C1, Arlington, VA 22206
<div class="list-card-price">$1,600/mo</div>
1 bd
711 sqft
-------------
3059 S Buchanan St APT A1, Arlington, VA 22206
<div class="list-card-price">$2,695/mo</div>
1 bd
1,712 sqft
-------------
4715 31st St S APT A2, Arlington, VA 22206
<div class="list-card-price">$2,350/mo</div>
1 bd
1,712 sqft

In [390]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22206): 
    if word in stopwords:
        words.remove(word)

In [404]:
zip_code ="22206"

apts_22206_df = pd.DataFrame(apartments_22206)
apts_22206_df['also_price'] = apts_22206_df['also_price'].str[:-4]
apts_22206_df["Zip Code"] = zip_code
apts_22206_df

,address,price_monthly,also_price,sqft,Zip Code
0,"IO Piazza by Windsor | 2727 S Quincy St, Arlin...",None,"$1,975+",None,22206
1,Delancey at Shirlington Village | 4220 Campbel...,None,"$1,617+",None,22206
2,"Avalon at Arlington Square | 2350 26th Ct S, A...",None,"$1,354+",None,22206
3,The Citizen at Shirlington Village | 3000 S Ra...,None,"$1,495+",None,22206
4,"3462 S Stafford St APT A2, Arlington, VA 22206","$2,595/mo",,"1,495 sqft",22206
5,"Bell Arlington Ridge | 2400 24th Rd S, Arlingt...",None,"$1,471+",None,22206
6,"4510 31st St S APT 104, Arlington, VA 22206","$1,524/mo",,680 sqft,22206
7,"Shirlington House | 4201 31st St S, Arlington, VA",None,"$1,424+",None,22206
8,"Alister Arlington Ridge | 2400 S Glebe Rd, Arl...",None,"$1,376+",None,22206
9,"4552 28th Rd S UNIT B, Arlington, VA 22206","$1,650/mo",,673 sqft,22206
10,"2465 Army Navy Dr #1-404, Arlington, VA 22206","$1,600/mo",,701 sqft,22206
11,"4817 31st St S APT B1, Arlington, VA 22206","$1,650/mo",,767 sqft,22206
12,"Dolley Madison Towers | 2300 S 24th Rd, Arling...",None,"$1,495+",None,22206
13,"4317 36th St S APT B1, Arlington, VA 22206","$1,600/mo",,711 sqft,22206
14,"(undisclosed Address), Arlington, VA 22206","$1,495/mo",,700 sqft,22206
15,"4862 28th St S APT B1, Arlington, VA 22206","$1,485/mo",,711 sqft,22206
16,"4550 28th Rd S #16, Arlington, VA 22206","$1,575/mo",,673 sqft,22206
17,"3074 S Abingdon St APT C2, Arlington, VA 22206","$1,750/mo",,"1,008 sqft",22206
18,"3441 S Stafford St APT B2, Arlington, VA 22206","$1,725/mo",,711 sqft,22206
19,"The Park at Arlington Ridge | 1800 26th St S, ...",None,"$1,358+",None,22206
20,"2321 25th St S APT 107, Arlington, VA 22206","$2,000/mo",,800 sqft,22206
21,"2923 E South Woodley St #1, Arlington, VA 22206","$1,590/mo",,613 sqft,22206
22,"4415 36th St S APT B1, Arlington, VA 22206","$1,900/mo",,840 sqft,22206
23,"2802 S Columbus St APT C2, Arlington, VA 22206","$1,400/mo",,711 sqft,22206
24,"2874 S Abingdon St APT C1, Arlington, VA 22206","$1,600/mo",,711 sqft,22206
25,"3059 S Buchanan St APT A1, Arlington, VA 22206","$2,695/mo",,"1,712 sqft",22206
26,"4715 31st St S APT A2, Arlington, VA 22206","$2,350/mo",,"1,712 sqft",22206

In [392]:
#22213

apartments_22213 = []

In [393]:
url = 'https://www.zillow.com/arlington-va-22213/apartments/1-bedrooms/'
browser.visit(url)

In [394]:
html = browser.html
soup = bs(html,'html.parser')

In [395]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22213.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
Crescent Falls Church | 2121 N Westmoreland St, Arlington, VA
None
$1,569+ 1 bd
None
-------------
2200 N Westmoreland St UNIT 225, Arlington, VA 22213
<div class="list-card-price">$2,050/mo</div>
1 bd
840 sqft
-------------
1100 N Kenilworth St APT 4, Arlington, VA 22205
<div class="list-card-price">$1,395/mo</div>
1 bd
700 sqft
-------------
Falls Green | 501 Roosevelt Blvd, Falls Church, VA
None
$1,483+ 1 bd
None
-------------
West Broad | 301 W Broad St, Falls Church, VA
None
$1,461+ 1 bd
None
-------------
Roosevelt Towers | 500 N Roosevelt Blvd, Falls Church, VA
None
$1,242+ 1 bd
None
-------------
Merrill House | 210 E Fairfax St, Falls Church, VA
None
$1,292+ 1 bd
None
-------------
Cavalier Club | 6200 Wilson Blvd, Falls Church, VA
None
$1,648+ 1 bd
None
-------------
Avalon Falls Church | 6600 Colton Crawford Cir, Falls Church, VA
None
$1,525+ 1 bd
None
-------------
6122 Willston Dr #MZ19ENX32, Falls Church, VA 22044
<div class="list-card-price">$1,300+/mo</div>
1 bd
-- sqft

In [396]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22213): 
    if word in stopwords:
        words.remove(word)

In [397]:
zip_code ="22213"

apts_22213_df = pd.DataFrame(apartments_22213)
apts_22213_df['also_price'] = apts_22213_df['also_price'].str[:-4]
apts_22213_df["Zip Code"] = zip_code
apts_22213_df

,address,price_monthly,also_price,sqft,Zip Code
0,Crescent Falls Church | 2121 N Westmoreland St...,None,"$1,569+",None,22213
1,"2200 N Westmoreland St UNIT 225, Arlington, VA...","$2,050/mo",,840 sqft,22213
2,"1100 N Kenilworth St APT 4, Arlington, VA 22205","$1,395/mo",,700 sqft,22213
3,"Falls Green | 501 Roosevelt Blvd, Falls Church...",None,"$1,483+",None,22213
4,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22213
5,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22213
6,"Merrill House | 210 E Fairfax St, Falls Church...",None,"$1,292+",None,22213
7,"Cavalier Club | 6200 Wilson Blvd, Falls Church...",None,"$1,648+",None,22213
8,Avalon Falls Church | 6600 Colton Crawford Cir...,None,"$1,525+",None,22213
9,"6122 Willston Dr #MZ19ENX32, Falls Church, VA ...","$1,300+/mo",,-- sqft,22213

In [398]:
#22205

apartments_22205 = []

In [399]:
url = 'https://www.zillow.com/arlington-va-22205/apartments/1-bedrooms/'
browser.visit(url)

In [400]:
html = browser.html
soup = bs(html,'html.parser')

In [401]:
list_cards = soup.find_all('div', class_='list-card-info')
for listing in list_cards:
    try:
        table = []
        address = listing.find('address', class_="list-card-addr").text
        price_monthly = listing.find('div', class_="list-card-price")
        if price_monthly is not None:
            monthly_price = price_monthly.text
        else:
            monthly_price = None
        search = listing.find('ul', class_="list-card-details")
        lis = search.find_all('li')
        table.append(lis)
        also_price = lis[0].text
        if price_monthly is not None:
            sqft = lis[2].text
        else:
            sqft = None
        house_dict = {"address": address, "price_monthly": monthly_price, "also_price": also_price, "sqft": sqft}
        apartments_22205.append(house_dict)
                
        if (address):
            print('-------------')
            print(address)
            print(price_monthly)
            print(also_price)
            print(sqft)
    
    except IndexError as e:
        print(e)

-------------
5714 11th St N APT 10, Arlington, VA 22205
<div class="list-card-price">$1,295/mo</div>
1 bd
700 sqft
-------------
1100 N Kenilworth St APT 4, Arlington, VA 22205
<div class="list-card-price">$1,395/mo</div>
1 bd
700 sqft
-------------
1110 N Kensington St APT 6, Arlington, VA 22205
<div class="list-card-price">$1,295/mo</div>
1 bd
750 sqft
-------------
5721 11th St N APT 8, Arlington, VA 22205
<div class="list-card-price">$1,295/mo</div>
1 bd
730 sqft
-------------
4040 Wilson | 4040 Wilson Blvd, Arlington, VA
None
$2,041+ 1 bd
None
-------------
Falls Green | 501 Roosevelt Blvd, Falls Church, VA
None
$1,483+ 1 bd
None
-------------
The View at Liberty Center | 4000 Wilson Blvd, Arlington, VA
None
$1,625+ 1 bd
None
-------------
West Broad | 301 W Broad St, Falls Church, VA
None
$1,461+ 1 bd
None
-------------
The Maxwell | 4200 N Carlin Springs Rd, Arlington, VA
None
$1,700+ 1 bd
None
-------------
Roosevelt Towers | 500 N Roosevelt Blvd, Falls Church, VA
None
$1,242+ 1 bd
None
-------------
The Waycroft | 750 N Glebe Rd, Arlington, VA
None
$1,860+ 1 bd
None
-------------
Birchwood | 545 N Pollard St, Arlington, VA
None
$1,895+ 1 bd
None

In [402]:
stopwords = ['<div class="list-card-price">', '</div>']
for word in list(apartments_22205): 
    if word in stopwords:
        words.remove(word)

In [403]:
zip_code ="22205"

apts_22205_df = pd.DataFrame(apartments_22205)
apts_22205_df['also_price'] = apts_22205_df['also_price'].str[:-4]
apts_22205_df["Zip Code"] = zip_code
apts_22205_df

,address,price_monthly,also_price,sqft,Zip Code
0,"5714 11th St N APT 10, Arlington, VA 22205","$1,295/mo",,700 sqft,22205
1,"1100 N Kenilworth St APT 4, Arlington, VA 22205","$1,395/mo",,700 sqft,22205
2,"1110 N Kensington St APT 6, Arlington, VA 22205","$1,295/mo",,750 sqft,22205
3,"5721 11th St N APT 8, Arlington, VA 22205","$1,295/mo",,730 sqft,22205
4,"4040 Wilson | 4040 Wilson Blvd, Arlington, VA",None,"$2,041+",None,22205
5,"Falls Green | 501 Roosevelt Blvd, Falls Church...",None,"$1,483+",None,22205
6,"The View at Liberty Center | 4000 Wilson Blvd,...",None,"$1,625+",None,22205
7,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22205
8,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22205
9,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22205
10,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22205
11,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22205

In [406]:
Zips = [apts_20009_df,apts_20002_df,apts_20001_df,apts_22201_df,apts_20003_df,apts_20007_df,apts_22209_df,apts_20037_df,apts_20005_df,apts_20010_df,apts_20011_df,apts_20008_df,apts_22314_df,apts_22204_df,apts_22203_df,apts_22202_df,apts_22207_df,apts_20036_df,apts_20004_df,apts_20024_df,apts_20032_df,apts_20020_df,apts_20019_df,apts_20018_df,apts_20017_df,apts_20015_df,apts_20016_df,apts_22302_df,apts_22301_df,apts_22305_df,apts_22206_df,apts_22213_df,apts_22205_df]
all_Zips = pd.concat(Zips)
all_Zips

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"$1,736+",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"$2,454+",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","$2,995/mo",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"$1,745+",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","$1,950/mo",,600 sqft,20009
...,...,...,...,...,...
7,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22205
8,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22205
9,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22205
10,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22205
11,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22205

In [407]:
ALL_ZIP_CODES = all_Zips.reset_index(drop=True)
ALL_ZIP_CODES

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"$1,736+",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"$2,454+",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","$2,995/mo",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"$1,745+",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","$1,950/mo",,600 sqft,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22205

In [408]:
ALL_ZIP_CODES_1 = ALL_ZIP_CODES
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"$1,736+",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"$2,454+",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","$2,995/mo",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"$1,745+",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","$1,950/mo",,600 sqft,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22205

In [410]:
ALL_ZIP_CODES_1['price_monthly'] = ALL_ZIP_CODES_1['price_monthly'].str.replace('$','')
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"$1,736+",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"$2,454+",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995/mo",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"$1,745+",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950/mo",,600 sqft,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22205

In [411]:
ALL_ZIP_CODES_1['price_monthly'] = ALL_ZIP_CODES_1['price_monthly'].str.replace('/mo','')
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"$1,736+",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"$2,454+",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"$1,745+",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600 sqft,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"$1,461+",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"$1,700+",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"$1,242+",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"$1,860+",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"$1,895+",None,22205

In [412]:
ALL_ZIP_CODES_1['also_price'] = ALL_ZIP_CODES_1['also_price'].str.replace('$','')
ALL_ZIP_CODES_1['also_price'] = ALL_ZIP_CODES_1['also_price'].str.replace('+','')
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"1,736",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"2,454",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690 sqft,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"1,745",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600 sqft,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"1,461",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"1,700",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"1,242",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"1,860",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"1,895",None,22205

In [413]:
ALL_ZIP_CODES_1['sqft'] = ALL_ZIP_CODES_1['sqft'].str.replace(' sqft','')
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"1,736",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"2,454",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"1,745",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"1,461",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"1,700",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"1,242",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"1,860",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"1,895",None,22205

In [417]:
ALL_ZIP_CODES_1.replace({'--': None})

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"1,736",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"2,454",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"1,745",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"1,461",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"1,700",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"1,242",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"1,860",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"1,895",None,22205

In [420]:
ALL_ZIP_CODES_1['sqft'].unique()

array([None, '690', '600', '521', '--', '550', '621', '450', '400', '650',
       '700', '651', '973', '680', '775', '564', '686', '490', '955',
       '674', '574', '750', '2,810', '425', '646', '944', '463', '718',
       '507', '688', '3,844', '1,000', '974', '665', '1,007', '883',
       '578', '510', '660', '900', '503', '670', '500', '506', '542',
       '662', '829', '1,068', '580', '565', '1,970', '575', '479', '610',
       '612', '555', '512', '745', '694', '537', '783', '800', '834',
       '589', '527', '485', '675', '730', '524', '854', '540', '716',
       '740', '1,845', '560', '741', '908', '701', '588', '1,029', '667',
       '655', '693', '523', '649', '625', '552', '769', '592', '613',
       '640', '720', '628', '668', '2,632', '458', '855', '3,232', '568',
       '1,224', '2,598', '605', '407', '950', '797', '528', '569', '532',
       '709', '2,560', '1,050', '725', '689', '754', '533', '830', '820',
       '1,190', '420', '520', '645', '428', '547', '624', '535', '525',
       '434', '766', '3,602', '1,184', '840', '843', '452', '708', '514',
       '513', '1,150', '2,978', '410', '779', '1,902', '3,080', '409',
       '617', '744', '517', '1,139', '742', '1,327', '850', '2,220',
       '710', '1,200', '593', '620', '758', '627', '3,344', '990',
       '1,774', '1,415', '672', '2,837', '3,004', '519', '502', '774',
       '618', '751', '747', '603', '3,880', '643', '581', '877', '695',
       '748', '735', '696', '663', '634', '648', '1,100', '602', '630',
       '2,132', '721', '642', '792', '544', '3,120', '980', '915', '644',
       '3,168', '546', '714', '1,056', '765', '470', '608', '460', '563',
       '703', '732', '499', '920', '492', '825', '867', '467', '1,201',
       '1,500', '2,800', '558', '890', '872', '459', '435', '851', '530',
       '471', '870', '480', '2,886', '536', '866', '756', '562', '679',
       '3,554', '487', '483', '635', '387', '719', '607', '760', '1,207',
       '1,520', '805', '641', '945', '895', '715', '1,022', '577',
       '2,294', '963', '728', '862', '676', '698', '888', '405', '975',
       '1,017', '597', '911', '2,520', '892', '498', '930', '518', '780',
       '531', '678', '839', '585', '2,295', '1,058', '3,027', '424',
       '827', '938', '677', '739', '551', '504', '637', '925', '437',
       '2,155', '1,476', '3,242', '590', '802', '614', '929', '734',
       '804', '566', '874', '828', '632', '656', '543', '860', '549',
       '996', '683', '631', '770', '927', '475', '738', '726', '687',
       '727', '666', '699', '752', '729', '837', '629', '809', '583',
       '633', '711', '755', '488', '959', '935', '898', '807', '713',
       '3,090', '2,720', '3,834', '654', '3,024', '810', '595', '684',
       '2,444', '785', '3,522', '669', '545', '707', '724', '746', '956',
       '1,189', '638', '736', '704', '567', '826', '430', '4,922', '325',
       '681', '842', '7,038', '1,495', '673', '767', '1,008', '1,712'],
      dtype=object)

In [424]:
ALL_ZIP_CODES_1.replace({'--': None})

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"1,736",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"2,454",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"1,745",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"1,461",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"1,700",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"1,242",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"1,860",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"1,895",None,22205

In [429]:
ALL_ZIP_CODES_1['sqft'].unique()

array([None, '690', '600', '521', '--', '550', '621', '450', '400', '650',
       '700', '651', '973', '680', '775', '564', '686', '490', '955',
       '674', '574', '750', '2,810', '425', '646', '944', '463', '718',
       '507', '688', '3,844', '1,000', '974', '665', '1,007', '883',
       '578', '510', '660', '900', '503', '670', '500', '506', '542',
       '662', '829', '1,068', '580', '565', '1,970', '575', '479', '610',
       '612', '555', '512', '745', '694', '537', '783', '800', '834',
       '589', '527', '485', '675', '730', '524', '854', '540', '716',
       '740', '1,845', '560', '741', '908', '701', '588', '1,029', '667',
       '655', '693', '523', '649', '625', '552', '769', '592', '613',
       '640', '720', '628', '668', '2,632', '458', '855', '3,232', '568',
       '1,224', '2,598', '605', '407', '950', '797', '528', '569', '532',
       '709', '2,560', '1,050', '725', '689', '754', '533', '830', '820',
       '1,190', '420', '520', '645', '428', '547', '624', '535', '525',
       '434', '766', '3,602', '1,184', '840', '843', '452', '708', '514',
       '513', '1,150', '2,978', '410', '779', '1,902', '3,080', '409',
       '617', '744', '517', '1,139', '742', '1,327', '850', '2,220',
       '710', '1,200', '593', '620', '758', '627', '3,344', '990',
       '1,774', '1,415', '672', '2,837', '3,004', '519', '502', '774',
       '618', '751', '747', '603', '3,880', '643', '581', '877', '695',
       '748', '735', '696', '663', '634', '648', '1,100', '602', '630',
       '2,132', '721', '642', '792', '544', '3,120', '980', '915', '644',
       '3,168', '546', '714', '1,056', '765', '470', '608', '460', '563',
       '703', '732', '499', '920', '492', '825', '867', '467', '1,201',
       '1,500', '2,800', '558', '890', '872', '459', '435', '851', '530',
       '471', '870', '480', '2,886', '536', '866', '756', '562', '679',
       '3,554', '487', '483', '635', '387', '719', '607', '760', '1,207',
       '1,520', '805', '641', '945', '895', '715', '1,022', '577',
       '2,294', '963', '728', '862', '676', '698', '888', '405', '975',
       '1,017', '597', '911', '2,520', '892', '498', '930', '518', '780',
       '531', '678', '839', '585', '2,295', '1,058', '3,027', '424',
       '827', '938', '677', '739', '551', '504', '637', '925', '437',
       '2,155', '1,476', '3,242', '590', '802', '614', '929', '734',
       '804', '566', '874', '828', '632', '656', '543', '860', '549',
       '996', '683', '631', '770', '927', '475', '738', '726', '687',
       '727', '666', '699', '752', '729', '837', '629', '809', '583',
       '633', '711', '755', '488', '959', '935', '898', '807', '713',
       '3,090', '2,720', '3,834', '654', '3,024', '810', '595', '684',
       '2,444', '785', '3,522', '669', '545', '707', '724', '746', '956',
       '1,189', '638', '736', '704', '567', '826', '430', '4,922', '325',
       '681', '842', '7,038', '1,495', '673', '767', '1,008', '1,712'],
      dtype=object)

In [427]:
import numpy as np

In [430]:
ALL_ZIP_CODES_1.replace('--',np.NaN)

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",None,"1,736",None,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",None,"2,454",None,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",None,"1,745",None,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",None,"1,461",None,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",None,"1,700",None,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",None,"1,242",None,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",None,"1,860",None,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",None,"1,895",None,22205

In [435]:
ALL_ZIP_CODES_1['sqft'].unique()

array([nan, '690', '600', '521', '550', '621', '450', '400', '650', '700',
       '651', '973', '680', '775', '564', '686', '490', '955', '674',
       '574', '750', '2,810', '425', '646', '944', '463', '718', '507',
       '688', '3,844', '1,000', '974', '665', '1,007', '883', '578',
       '510', '660', '900', '503', '670', '500', '506', '542', '662',
       '829', '1,068', '580', '565', '1,970', '575', '479', '610', '612',
       '555', '512', '745', '694', '537', '783', '800', '834', '589',
       '527', '485', '675', '730', '524', '854', '540', '716', '740',
       '1,845', '560', '741', '908', '701', '588', '1,029', '667', '655',
       '693', '523', '649', '625', '552', '769', '592', '613', '640',
       '720', '628', '668', '2,632', '458', '855', '3,232', '568',
       '1,224', '2,598', '605', '407', '950', '797', '528', '569', '532',
       '709', '2,560', '1,050', '725', '689', '754', '533', '830', '820',
       '1,190', '420', '520', '645', '428', '547', '624', '535', '525',
       '434', '766', '3,602', '1,184', '840', '843', '452', '708', '514',
       '513', '1,150', '2,978', '410', '779', '1,902', '3,080', '409',
       '617', '744', '517', '1,139', '742', '1,327', '850', '2,220',
       '710', '1,200', '593', '620', '758', '627', '3,344', '990',
       '1,774', '1,415', '672', '2,837', '3,004', '519', '502', '774',
       '618', '751', '747', '603', '3,880', '643', '581', '877', '695',
       '748', '735', '696', '663', '634', '648', '1,100', '602', '630',
       '2,132', '721', '642', '792', '544', '3,120', '980', '915', '644',
       '3,168', '546', '714', '1,056', '765', '470', '608', '460', '563',
       '703', '732', '499', '920', '492', '825', '867', '467', '1,201',
       '1,500', '2,800', '558', '890', '872', '459', '435', '851', '530',
       '471', '870', '480', '2,886', '536', '866', '756', '562', '679',
       '3,554', '487', '483', '635', '387', '719', '607', '760', '1,207',
       '1,520', '805', '641', '945', '895', '715', '1,022', '577',
       '2,294', '963', '728', '862', '676', '698', '888', '405', '975',
       '1,017', '597', '911', '2,520', '892', '498', '930', '518', '780',
       '531', '678', '839', '585', '2,295', '1,058', '3,027', '424',
       '827', '938', '677', '739', '551', '504', '637', '925', '437',
       '2,155', '1,476', '3,242', '590', '802', '614', '929', '734',
       '804', '566', '874', '828', '632', '656', '543', '860', '549',
       '996', '683', '631', '770', '927', '475', '738', '726', '687',
       '727', '666', '699', '752', '729', '837', '629', '809', '583',
       '633', '711', '755', '488', '959', '935', '898', '807', '713',
       '3,090', '2,720', '3,834', '654', '3,024', '810', '595', '684',
       '2,444', '785', '3,522', '669', '545', '707', '724', '746', '956',
       '1,189', '638', '736', '704', '567', '826', '430', '4,922', '325',
       '681', '842', '7,038', '1,495', '673', '767', '1,008', '1,712'],
      dtype=object)

In [432]:
ALL_ZIP_CODES_1 = ALL_ZIP_CODES_1.fillna(value=np.nan)
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",NaN,"1,736",NaN,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",NaN,"2,454",NaN,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009","2,995",,690,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",NaN,"1,745",NaN,20009
4,"1919 19th St NW #401, Washington, DC 20009","1,950",,600,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",NaN,"1,461",NaN,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",NaN,"1,700",NaN,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",NaN,"1,242",NaN,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",NaN,"1,860",NaN,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",NaN,"1,895",NaN,22205

In [434]:
ALL_ZIP_CODES_1.loc[ALL_ZIP_CODES_1['sqft'] == '--','sqft'] = np.nan

In [437]:
ALL_ZIP_CODES_1['sqft'] = ALL_ZIP_CODES_1['sqft'].str.replace('[^.0-9]', '', regex=True)

In [444]:
ALL_ZIP_CODES_1['price_monthly'] = ALL_ZIP_CODES_1['price_monthly'].str.replace('[^.0-9]', '', regex=True)

In [445]:
ALL_ZIP_CODES_1['also_price'] = ALL_ZIP_CODES_1['also_price'].str.replace('[^.0-9]', '', regex=True)

In [440]:
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code
0,"Highview & Castle Manor | 2505 13th St NW, Was...",NaN,1736,NaN,20009
1,"Reed Row | 2101 Champlain St NW, Washington, DC",NaN,2454,NaN,20009
2,"1845 Kalorama Rd NW #3, Washington, DC 20009",2995,,690,20009
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",NaN,1745,NaN,20009
4,"1919 19th St NW #401, Washington, DC 20009",1950,,600,20009
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",NaN,1461,NaN,22205
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",NaN,1700,NaN,22205
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",NaN,1242,NaN,22205
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",NaN,1860,NaN,22205
1766,"Birchwood | 545 N Pollard St, Arlington, VA",NaN,1895,NaN,22205

In [460]:
ALL_ZIP_CODES_1['price_monthly'] = ALL_ZIP_CODES_1['price_monthly'].fillna(0)
ALL_ZIP_CODES_1['also_price'] = ALL_ZIP_CODES_1['also_price'].fillna(0)

ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code,Price
0,"Highview & Castle Manor | 2505 13th St NW, Was...",0,1736.0,NaN,20009,1736.0
1,"Reed Row | 2101 Champlain St NW, Washington, DC",0,2454.0,NaN,20009,2454.0
2,"1845 Kalorama Rd NW #3, Washington, DC 20009",2995,0.0,690,20009,NaN
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",0,1745.0,NaN,20009,1745.0
4,"1919 19th St NW #401, Washington, DC 20009",1950,0.0,600,20009,NaN
...,...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",0,1461.0,NaN,22205,1461.0
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",0,1700.0,NaN,22205,1700.0
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",0,1242.0,NaN,22205,1242.0
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",0,1860.0,NaN,22205,1860.0
1766,"Birchwood | 545 N Pollard St, Arlington, VA",0,1895.0,NaN,22205,1895.0

In [461]:
ALL_ZIP_CODES_1.dtypes

address           object
price_monthly      int64
also_price       float64
sqft              object
Zip Code          object
Price            float64
dtype: object

In [462]:
ALL_ZIP_CODES_1['price_monthly'] = pd.to_numeric(ALL_ZIP_CODES_1['price_monthly'])
ALL_ZIP_CODES_1['also_price'] = pd.to_numeric(ALL_ZIP_CODES_1['also_price'])

In [463]:
ALL_ZIP_CODES_1['Price'] = ALL_ZIP_CODES_1['price_monthly']+ALL_ZIP_CODES_1['also_price']
ALL_ZIP_CODES_1

,address,price_monthly,also_price,sqft,Zip Code,Price
0,"Highview & Castle Manor | 2505 13th St NW, Was...",0,1736.0,NaN,20009,1736.0
1,"Reed Row | 2101 Champlain St NW, Washington, DC",0,2454.0,NaN,20009,2454.0
2,"1845 Kalorama Rd NW #3, Washington, DC 20009",2995,0.0,690,20009,2995.0
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",0,1745.0,NaN,20009,1745.0
4,"1919 19th St NW #401, Washington, DC 20009",1950,0.0,600,20009,1950.0
...,...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",0,1461.0,NaN,22205,1461.0
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",0,1700.0,NaN,22205,1700.0
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",0,1242.0,NaN,22205,1242.0
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",0,1860.0,NaN,22205,1860.0
1766,"Birchwood | 545 N Pollard St, Arlington, VA",0,1895.0,NaN,22205,1895.0

In [464]:
ALL_ZIP_CODES_2 = ALL_ZIP_CODES_1[["address", "Zip Code", "Price", "sqft"]]
ALL_ZIP_CODES_2

                                                address Zip Code   Price sqft
0     Highview & Castle Manor | 2505 13th St NW, Was...    20009  1736.0  NaN
1       Reed Row | 2101 Champlain St NW, Washington, DC    20009  2454.0  NaN
2          1845 Kalorama Rd NW #3, Washington, DC 20009    20009  2995.0  690
3     The Melwood | 1803 Biltmore St NW, Washington, DC    20009  1745.0  NaN
4            1919 19th St NW #401, Washington, DC 20009    20009  1950.0  600
...                                                 ...      ...     ...  ...
1762      West Broad | 301 W Broad St, Falls Church, VA    22205  1461.0  NaN
1763  The Maxwell | 4200 N Carlin Springs Rd, Arling...    22205  1700.0  NaN
1764  Roosevelt Towers | 500 N Roosevelt Blvd, Falls...    22205  1242.0  NaN
1765       The Waycroft | 750 N Glebe Rd, Arlington, VA    22205  1860.0  NaN
1766        Birchwood | 545 N Pollard St, Arlington, VA    22205  1895.0  NaN

[1767 rows x 4 columns]

In [468]:
ALL_ZIP_CODES_2.dtypes

address      object
Zip Code     object
Price       float64
sqft        float64
dtype: object

In [467]:
ALL_ZIP_CODES_2['sqft'] = pd.to_numeric(ALL_ZIP_CODES_2['sqft'])

<ipython-input-467-a65c89f170ec>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ALL_ZIP_CODES_2['sqft'] = pd.to_numeric(ALL_ZIP_CODES_2['sqft'])

In [469]:
ALL_ZIP_CODES_2['Price/Sqft'] = ALL_ZIP_CODES_2['Price']/ALL_ZIP_CODES_2['sqft']
ALL_ZIP_CODES_2

<ipython-input-469-a34696813065>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ALL_ZIP_CODES_2['Price/Sqft'] = ALL_ZIP_CODES_2['Price']/ALL_ZIP_CODES_2['sqft']

,address,Zip Code,Price,sqft,Price/Sqft
0,"Highview & Castle Manor | 2505 13th St NW, Was...",20009,1736.0,NaN,NaN
1,"Reed Row | 2101 Champlain St NW, Washington, DC",20009,2454.0,NaN,NaN
2,"1845 Kalorama Rd NW #3, Washington, DC 20009",20009,2995.0,690.0,4.34058
3,"The Melwood | 1803 Biltmore St NW, Washington, DC",20009,1745.0,NaN,NaN
4,"1919 19th St NW #401, Washington, DC 20009",20009,1950.0,600.0,3.25000
...,...,...,...,...,...
1762,"West Broad | 301 W Broad St, Falls Church, VA",22205,1461.0,NaN,NaN
1763,"The Maxwell | 4200 N Carlin Springs Rd, Arling...",22205,1700.0,NaN,NaN
1764,"Roosevelt Towers | 500 N Roosevelt Blvd, Falls...",22205,1242.0,NaN,NaN
1765,"The Waycroft | 750 N Glebe Rd, Arlington, VA",22205,1860.0,NaN,NaN
1766,"Birchwood | 545 N Pollard St, Arlington, VA",22205,1895.0,NaN,NaN

In [470]:
ALL_ZIP_CODES_2.to_csv("All_Addresses.csv")

In [471]:
MEDIAN_RENT_ZIP = ALL_ZIP_CODES_2.groupby(["Zip Code"])['Price'].median()

MEDIAN_RENT_ZIP

Zip Code
20001    1875.0
20002    1612.5
20003    1850.0
20004    2300.0
20005    2000.0
20007    1700.0
20008    1750.0
20009    1899.0
20010    1600.0
20011    1524.0
20015    1599.0
20016    1752.0
20017    1489.5
20018    1512.5
20019    1250.0
20020    1197.5
20024    1801.5
20032    1067.5
20036    1999.5
20037    2095.0
22201    1667.5
22202    1600.0
22203    1695.0
22204    1454.0
22205    1472.0
22206    1600.0
22207    1547.5
22209    1650.0
22213    1472.0
22301    1595.0
22302    1562.5
22305    1421.0
22314    1645.0
Name: Price, dtype: float64

In [475]:
MEDIAN_RENT_ZIP_df = pd.DataFrame(MEDIAN_RENT_ZIP)
MEDIAN_RENT_ZIP

Zip Code
20001    1875.0
20002    1612.5
20003    1850.0
20004    2300.0
20005    2000.0
20007    1700.0
20008    1750.0
20009    1899.0
20010    1600.0
20011    1524.0
20015    1599.0
20016    1752.0
20017    1489.5
20018    1512.5
20019    1250.0
20020    1197.5
20024    1801.5
20032    1067.5
20036    1999.5
20037    2095.0
22201    1667.5
22202    1600.0
22203    1695.0
22204    1454.0
22205    1472.0
22206    1600.0
22207    1547.5
22209    1650.0
22213    1472.0
22301    1595.0
22302    1562.5
22305    1421.0
22314    1645.0
Name: Price, dtype: float64

In [493]:
MEDIAN_RENT_ZIP_df

           Price
Zip Code
20004     2300.0
20037     2095.0
20005     2000.0
20036     1999.5
20009     1899.0
20001     1875.0
20003     1850.0
20024     1801.5
20016     1752.0
20008     1750.0
20007     1700.0
22203     1695.0
22201     1667.5
22209     1650.0
22314     1645.0
20002     1612.5
20010     1600.0
22202     1600.0
22206     1600.0
20015     1599.0
22301     1595.0
22302     1562.5
22207     1547.5
20011     1524.0
20018     1512.5
20017     1489.5
22213     1472.0
22205     1472.0
22204     1454.0
22305     1421.0
20019     1250.0
20020     1197.5
20032     1067.5

In [485]:
MEDIAN_RENT_ZIP_df = MEDIAN_RENT_ZIP_df.sort_values('Price', ascending = False)

In [478]:
MEDIAN_PRICE_PER_SQFT_ZIP = ALL_ZIP_CODES_2.groupby(["Zip Code"])['Price/Sqft'].median()

MEDIAN_PRICE_PER_SQFT_ZIP

Zip Code
20001    2.825490
20002    2.434783
20003    2.866071
20004    3.076121
20005    3.182131
20007    2.592593
20008    2.645161
20009    3.190000
20010    2.460317
20011    2.300000
20015    2.935780
20016    2.680339
20017    1.852273
20018    2.107143
20019    2.016807
20020    1.838462
20024    2.715858
20032    0.441912
20036    3.309859
20037    3.539139
22201    2.545455
22202    2.547551
22203    2.442890
22204    2.232667
22205    1.811986
22206    2.245764
22207    2.132647
22209    2.274852
22213    2.216667
22301    2.333333
22302    2.173077
22305    2.477974
22314    2.807927
Name: Price/Sqft, dtype: float64

In [479]:
MEDIAN_PRICE_PER_SQFT_ZIP_df = pd.DataFrame(MEDIAN_PRICE_PER_SQFT_ZIP)
MEDIAN_PRICE_PER_SQFT_ZIP_df

          Price/Sqft
Zip Code
20001       2.825490
20002       2.434783
20003       2.866071
20004       3.076121
20005       3.182131
20007       2.592593
20008       2.645161
20009       3.190000
20010       2.460317
20011       2.300000
20015       2.935780
20016       2.680339
20017       1.852273
20018       2.107143
20019       2.016807
20020       1.838462
20024       2.715858
20032       0.441912
20036       3.309859
20037       3.539139
22201       2.545455
22202       2.547551
22203       2.442890
22204       2.232667
22205       1.811986
22206       2.245764
22207       2.132647
22209       2.274852
22213       2.216667
22301       2.333333
22302       2.173077
22305       2.477974
22314       2.807927

In [489]:
MEDIAN_PRICE_PER_SQFT_ZIP_df = MEDIAN_PRICE_PER_SQFT_ZIP_df.sort_values('Price/Sqft', ascending = False)

In [492]:
MEDIAN_PRICE_PER_SQFT_ZIP_df

          Price/Sqft
Zip Code
20037       3.539139
20036       3.309859
20009       3.190000
20005       3.182131
20004       3.076121
20015       2.935780
20003       2.866071
20001       2.825490
22314       2.807927
20024       2.715858
20016       2.680339
20008       2.645161
20007       2.592593
22202       2.547551
22201       2.545455
22305       2.477974
20010       2.460317
22203       2.442890
20002       2.434783
22301       2.333333
20011       2.300000
22209       2.274852
22206       2.245764
22204       2.232667
22213       2.216667
22302       2.173077
22207       2.132647
20018       2.107143
20019       2.016807
20017       1.852273
20020       1.838462
22205       1.811986
20032       0.441912

In [481]:
MEDIAN_SQFT_ZIP = ALL_ZIP_CODES_2.groupby(["Zip Code"])['sqft'].median()

MEDIAN_SQFT_ZIP

Zip Code
20001     673.5
20002     650.0
20003     650.0
20004     760.0
20005     699.0
20007     700.0
20008     734.0
20009     650.0
20010     675.0
20011     678.5
20015     628.0
20016     707.0
20017     900.0
20018     710.5
20019     636.0
20020     640.0
20024     688.0
20032    2720.0
20036     700.0
20037     701.5
22201     656.5
22202     668.0
22203     689.5
22204     700.0
22205     715.0
22206     711.0
22207     690.0
22209     757.0
22213     770.0
22301     675.0
22302     735.0
22305     700.0
22314     641.0
Name: sqft, dtype: float64

In [482]:
MEDIAN_SQFT_ZIP_df = pd.DataFrame(MEDIAN_SQFT_ZIP)
MEDIAN_SQFT_ZIP_df

            sqft
Zip Code
20001      673.5
20002      650.0
20003      650.0
20004      760.0
20005      699.0
20007      700.0
20008      734.0
20009      650.0
20010      675.0
20011      678.5
20015      628.0
20016      707.0
20017      900.0
20018      710.5
20019      636.0
20020      640.0
20024      688.0
20032     2720.0
20036      700.0
20037      701.5
22201      656.5
22202      668.0
22203      689.5
22204      700.0
22205      715.0
22206      711.0
22207      690.0
22209      757.0
22213      770.0
22301      675.0
22302      735.0
22305      700.0
22314      641.0

In [487]:
MEDIAN_SQFT_ZIP_df = MEDIAN_SQFT_ZIP_df.sort_values('sqft', ascending = False)

In [494]:
MEDIAN_SQFT_ZIP_df

            sqft
Zip Code
20032     2720.0
20017      900.0
22213      770.0
20004      760.0
22209      757.0
22302      735.0
20008      734.0
22205      715.0
22206      711.0
20018      710.5
20016      707.0
20037      701.5
20036      700.0
22204      700.0
20007      700.0
22305      700.0
20005      699.0
22207      690.0
22203      689.5
20024      688.0
20011      678.5
22301      675.0
20010      675.0
20001      673.5
22202      668.0
22201      656.5
20002      650.0
20009      650.0
20003      650.0
22314      641.0
20020      640.0
20019      636.0
20015      628.0

In [491]:
MEDIAN_RENT_ZIP_df.to_csv("Median_rent_by_zip.csv")
MEDIAN_PRICE_PER_SQFT_ZIP_df.to_csv("Median_price_persqft_zip.csv")
MEDIAN_SQFT_ZIP_df.to_csv("Median_sqft_by_zip.csv")